LineEdit Upgrades
space-wizards/RobustToolbox pull request #1010
Opened 2020-02-27 18:36 UTC by tentekal

Addresses issue space-wizards/space-station-14/#639 in the Content repo and #748 in RobustToolbox.

I'm planning to enhance further with text selection via cursor, copy-paste implemented, etc..

2020-02-28 15:50 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        public string TextBuffer
You really should not be using a separate text buffer just to keep track of what to display.

Just automatically calculate an offset in the current text stored to keep track of where to start drawing.

2020-02-28 15:50 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                    _cursorPosition -= _text.Length;
Shouldn't you be able to achieve this by just setting current position to 0?

2020-02-28 15:51 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                    _cursorPosition += _text.Length;
You should set it to text.length, not add. Like this you'll have cursor position going out of bounds.

2020-02-28 15:52 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                    for (int index = 0; index < individualWords.Length; index++)
Uh, can't you just iterate over characters until you find two characters that form a word bound?

2020-03-03 00:17 UTC, tentekal commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        public string TextBuffer
Set this up, but left it as a property because each render cycle would reset the offset

2020-03-06 18:41 UTC, PJB3005 requested changes

2020-03-06 18:41 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +            foreach (var chr in renderedText.Substring(startRenderPos))
```suggestion
            foreach (var chr in renderedText.AsSpan(startRenderPos))
```
Use a span here so that you don't have to allocate the sub string. Decent performance boost.

2020-03-06 18:41 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +            if ( IsValid != null )
What?

2020-03-06 18:41 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                _updatePseudoClass();
This should not modify the pseudo class. The text buffer is still the same.

2020-03-06 18:41 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                if (value == null)
It's impossible to actually hit this if, as comparing an `int` with `null` will always fail.

2020-03-06 20:19 UTC, tentekal commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +            foreach (var chr in renderedText.Substring(startRenderPos))
Is this a pointer to a portion of the existing string? I didn't know that was possible, thanks.

2020-03-06 20:30 UTC, tentekal commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                if (value == null)
So that's what Rider was warning me about on compile...

2020-03-09 17:01 UTC, tentekal commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +            if ( IsValid != null )
Removing this actually broke the ability to backspace and I have no idea why. Could you provide some insight?

2020-03-11 16:43 UTC, tentekal commented
I need to clean out some unneeded code, and I'm not happy with how highlighted characters are rendered (I don't see a performance hit, but I haven't profiled). 

Looking to apply best practices to this, but I believe it's ready to be out of draft as the functionality is there.

2020-03-15 08:42 UTC, PJB3005 requested changes

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Shared/Input/KeyFunctions.cs
> +        public static readonly BoundKeyFunction TextShiftLeft = "TextShiftLeft";
You should not refer to `ShiftLeft` or `CtrlLeft` directly. Should instead use terms like "select left" or "move words left".

Also you need a combined select + words move version.

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/Input/EngineContexts.cs
> +            common.AddFunction(EngineKeyFunctions.TextEnd);
You're not registering ShiftLeft here.

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        private string _selectedText = "";
You should not have a separate selected text buffer. You should create a copy of the buffer (or better yet, create a `ReadOnlySpan<char>`) when necessary instead.

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        private int _startSelection;
Your functions for modifying the selection don't modify these.

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                if ( _selectedText != "" && Enumerable.Range(selectionStart, _selectedText.Length).Contains(count) )
Keep track of the index of the current char while iterating and then just start rendering when said index is greater than `selectionStart`.

Also for performance it would be best if you stored the pixel position at which the selection starts and ends (by calculating it while rendering the main text) and then drew one rectangle after all text is drawn.

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
>          private int _cursorPosition;
Does it still make sense to have a `_cursorPosition` when you have a selection start and end?

I know you'll still need to keep track of "which side of the selection is the cursor at" but otherwise it should match, shouldn't it?

2020-03-15 08:42 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                        if (boundary.Index < _cursorPosition)
Shouldn't this be `>`?

2020-05-03 14:06 UTC, PJB3005 commented
This PR is completely stale and I'd like to get this in.

2020-05-04 15:13 UTC, closed without merging