Gravity
space-wizards/RobustToolbox pull request #1031
Opened 2020-04-21 19:03 UTC by InquisitivePenguin

Link to relevant content PR: \<coming soon\>

### What this PR does

In order to add Gravity to SS14, a few minor engine changes must be made:
- Each grid should keep track of whether or not it has gravity
- The physics system should not apply friction to moving objects in zero gravity

In addition, I fixed a bug involving asymmetric collisions. This bug would happen whenever two objects collided, one of which had a `PreventCollide` override that returned true, and the other that did not. The former would not collide with the later, but the later would still act as if it had collided with the former.

#### Completion Checklist
- [X] Grid has a gravity property
- [X] Friction is not applied to objects moving in zero gravity
- [ ] Space will always have zero gravity

2020-04-22 15:55 UTC, PJB3005 requested changes

2020-04-22 15:55 UTC, PJB3005 commented on Robust.Shared/Physics/PhysicsManager.cs
> +                    foreach (var othermods in othercollisionmodifiers)
Does this have to be inside the other loop? This doesn't have to process based on `mods` does it?

2020-04-22 15:57 UTC, InquisitivePenguin commented on Robust.Shared/Physics/PhysicsManager.cs
> +                    foreach (var othermods in othercollisionmodifiers)
You're right, I'll fix that.

2020-04-23 14:49 UTC, PJB3005 approved these changes

2020-04-23 14:49 UTC, merged