Add system for using flag names in YAML
space-wizards/RobustToolbox pull request #1047
Opened 2020-05-05 23:27 UTC by ComicIronic

It's now possible to hook an enum into the serialization and deserialization of a field by name, using an attribute. This allows for bitflags in the engine to be defined by name in the content, in a way that lets content creators write flag names in prototype YAML.

This works by annotating an enum with the [FlagsFor(<fieldname>)] attribute, which the YamlObjectSerializer picks up through the ReflectionManager to use as a special serializer for fields of that name.

Fixes #974.

2020-05-06 13:51 UTC, ComicIronic commented
I'm not sure the matching on field name strings is necessarily the best choice, but I don't see a clear alternative. If someone is comfortable with `TypeSerializer`s, we might be able to make the `FlagsFor` attribute take a type argument as well.

2020-05-08 11:35 UTC, PJB3005 reviewed
Would be nice if this could be extended to other types of values too, like `DrawDepth`.

2020-05-08 11:35 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
Doing this in the static constructor is a very bad idea for two reasons:

1. It means the data is shared between different IoC instances, which could be a problem for stuff such as integration tests which use it to split client/server instances.
2. There's no real good guarantee that the static constructor runs *after* content has been initialized, in which case this would break.

2020-05-08 11:35 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +                    return flagSerializer.NodeToFlags(node, this);
Tying this to the name of the node isn't gonna be sufficient. For example then we'd need to have multiple `[FlagsFor]` attributes on collision layers, which would then also mark ANY variable called `layer` and `mask` as collision layers.

2020-05-08 12:34 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
I tried to avoid it with `IPostInjectInit`, but I didn't see how to get `YamlObjectSerializer` to be injected into by the IoC system. How should I do that?

2020-05-08 12:43 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +                    return flagSerializer.NodeToFlags(node, this);
Like I say, I don't immediately see a better alternative.

Unless you would prefer some kind of newtype wrapper around `int` in the engine, that then gets custom-serialization based on an attribute in the content? Which would solve the multiple-attributes/field-name problems, but would require rewriting a lot of engine code, probably.

The main complication for me is the use of `DataField`. Otherwise some kind of metadata attribute could go directly on the property being serialized.

2020-05-08 14:38 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +                    return flagSerializer.NodeToFlags(node, this);
I would love if serialization was instead to-object for flexibility and performance reasons like this, yeah.

Could maybe provide some simple options parameter to `DataField` and friends that can contain flexible options like this? Something like `serializer.DataField(..., SerializationOptions.EnumType("CollisionLayer")`

2020-05-09 00:18 UTC, ComicIronic commented
@PJB3005 How's this? It's made the PR a bit chunkier, but the new system should be extensible enough to allow for future custom serialization/deserialization, including using enum names as constants.

2020-05-09 11:07 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
You're gonna have to store this data on a manager *somewhere*, not sure where the best place would be. Probably ReflectionManager?

2020-05-09 11:19 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
The new code no longer does this in a static initializer. Do your comments still apply?

2020-05-10 23:26 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlCustomFormatSerializer.cs
> +                if (_serializer == null)
Any reason you're not just initializing this in the declaration? It'd solve a theoretical race condition here and just be cleaner.

2020-05-11 13:41 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlCustomFormatSerializer.cs
> +                if (_serializer == null)
Can't refer to `this` in a static initializer. I could lock it, but this constructor will be called a lot in serialization, and the race condition doesn't have any affect at the moment.

2020-05-15 11:11 UTC, snowsignal requested changes

2020-05-15 11:11 UTC, snowsignal commented on Robust.Shared/Serialization/YamlCustomFormatSerializer.cs
> +    /// Conveniece class for static access to custom formatters.
Ultra-minor nitpick but this should be 'convinience'.

2020-05-15 11:11 UTC, InquisitivePenguin commented on Robust.Shared/Serialization/YamlFlagSerializer.cs
> +                                            flagsforAttribute.Tag));
Maybe use string interpolation instead, e.g. `"Multiple bitflag enums declared for the tag ${flagsforAttribute.Tag}"`

2020-05-15 11:11 UTC, InquisitivePenguin commented on Robust.Shared/Serialization/YamlFlagSerializer.cs
> +                flags |= (int)Enum.Parse(_flagType, flagName);
Is this cast guarenteed to succeed?

2020-05-15 11:35 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlFlagSerializer.cs
> +                flags |= (int)Enum.Parse(_flagType, flagName);
For the default declaration of enums, yes,  they are backed by `int`. For enums which are not `int`, using this flag serialization is a mistake, since it only works for fields which are `int` underneath. I'll add a check for that to `WithFlagRepresentation`, but I think that's the earliest it can happen.

2020-05-15 14:08 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlFlagSerializer.cs
> +                                            flagsforAttribute.Tag));
Weirdly, I do that below.

2020-05-20 15:38 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
I missed this but yes there is still the issue of, because it uses a static, this could theoretically be shared between two separate game instances.

2020-05-21 09:46 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
So what should I do? Add a `ICustomFormatManager`, and register an instance with every IoC instance?

2020-05-21 22:28 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
Probably, yeah.

2020-05-23 22:58 UTC, ComicIronic commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            var reflectionManager = IoCManager.Resolve<IReflectionManager>();
Alright, done.

2020-05-24 20:43 UTC, merged