Implement audio occlusion and upgrade to OpenTK 4
space-wizards/RobustToolbox pull request #1068
Opened 2020-05-23 13:40 UTC by Clyybber

also fix a bug with IntersectRayWithPredicate, where the predicate would be called on everything, ignoring the CollisionMask

2020-05-23 14:09 UTC, PJB3005 commented
I don't like that this is all a massive single PR but oh well.

2020-05-24 17:07 UTC, PJB3005 requested changes

2020-05-24 17:07 UTC, PJB3005 commented on Robust.Client/Robust.Client.csproj
> +    <PackageReference Include="OpenTK" Version="4.0.0-pre9.1" />
Please add direct dependencies on `OpenToolkit.Graphics` and `OpenToolkit.OpenAL` instead of relying on the meta package.

2020-05-24 17:07 UTC, PJB3005 commented on Robust.Client/Robust.Client.csproj
> +    <ProjectReference Include="..\..\Content.Shared\Content.Shared.csproj" />
This is definitely an accident.

2020-05-24 17:07 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            AL.Source(source, ALSourcei.EfxDirectFilter, filter);
Should we really instantiate a filter here even if it might not ever be used?

2020-05-24 17:07 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +        private readonly ConcurrentQueue<(int, int)> _sourceDisposeQueue = new ConcurrentQueue<(int, int)>();
These tuple members should be named for clarity.

2020-05-24 17:07 UTC, PJB3005 commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +                            IoCManager.Resolve<IPhysicsManager>().IntersectRayWithPredicate(
Thanks to the physics rewrite you can actually get a proper list of results now I believe, so you don't need to do this hack of mutating inside the predicate anymore.

2020-05-24 17:27 UTC, Clyybber commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +                            IoCManager.Resolve<IPhysicsManager>().IntersectRayWithPredicate(
Yeah, but this is faster I think.

2020-05-24 17:47 UTC, Clyybber commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +                            IoCManager.Resolve<IPhysicsManager>().IntersectRayWithPredicate(
I had it count the results before, but figured this might be faster.

2020-05-24 17:50 UTC, Clyybber commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            AL.Source(source, ALSourcei.EfxDirectFilter, filter);
When would it not be used?

2020-05-24 17:54 UTC, Clyybber commented on Robust.Client/Robust.Client.csproj
> +    <PackageReference Include="OpenTK" Version="4.0.0-pre9.1" />
Also had to add `OpenToolkit.Windowing.GraphicsLibraryFramework`

2020-05-24 19:09 UTC, PJB3005 commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +                            IoCManager.Resolve<IPhysicsManager>().IntersectRayWithPredicate(
Mutating inside a predicate like this is *generally* considered an anti-pattern so I would say it's better to get a proper list and check the count.

If it performs a performance issue later we can optimize it.

2020-05-24 19:13 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            AL.Source(source, ALSourcei.EfxDirectFilter, filter);
Global sounds, sounds that aren't occluded (short sounds like keyboard sounds).

2020-05-24 19:14 UTC, PJB3005 commented on Robust.Client/Robust.Client.csproj
> +    <PackageReference Include="OpenTK" Version="4.0.0-pre9.1" />
> OpenToolkit.Windowing.GraphicsLibraryFramework

You shouldn't need that since we already include it in-repo. You might have to implement the `IBindingsContext` yourself though but that's triviail.

2020-05-27 15:36 UTC, PJB3005 approved these changes

2020-05-27 15:50 UTC, merged