Input Handling + other cleanups to support click drag functionality
space-wizards/RobustToolbox pull request #1132
Opened 2020-06-13 22:02 UTC by chairbender

Add some various capabilities related to clickdrag functionality, also a few small cleanups here and there as I noticed them.

New stuff:

- copy spritecomponent from another (used for the drag drop shadow)
- "replay" in InputHandler, allows clientside to "store" an input to be later re-triggered, this is used so that drag and drop can block the mousedown event when you mousedown on a draggable item, then re-fire that event if the mouseup happens before the interaction turns into a drag

2020-06-14 00:38 UTC, PJB3005 reviewed
I'm not 100% sure on those input system changes but I'll have to check the content-side PR to see.

2020-06-14 00:38 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +        public void CopyFrom(SpriteComponent other)
Is this supposed to only do a copy at the time it's called or is it supposed to keep the visual data in sync? Because this doesn't do keep copies of various things like the `Layers` list, it's gonna entangle those parts of the sprite while other stuff like `color` will stay separate.

If these are supposed to stay perfectly in sync, I feel a different API is necessary (maybe a way to hook into the renderer so the other entity can be visually copied immediately?).  If it's not then this should do deeper copies of things like `Layers` and such to prevent entanglement.

2020-06-14 11:10 UTC, ComicIronic commented on Robust.Shared/Input/InputCmdHandler.cs
> +namespace Robust.Shared.Input.Binding
You should move this file.

2020-06-19 18:36 UTC, chairbender commented
@ComicIronic @PJB3005 thanks, fixed

2020-07-01 15:10 UTC, PJB3005 requested changes

2020-07-01 15:10 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +            this._baseRsi = other._baseRsi == null ? null : new RSI(other._baseRsi);
RSIs aren't mutable so this deep copy isn't necessary.

2020-07-01 15:10 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +            this.Layers = new List<Layer>(other.Layers);
The actual objects *inside* the layer list also need to be cloned.

2020-07-01 15:10 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +            this.PostShader = other.PostShader?.Duplicate();
You can check if `PostShared.Mutable` is false here and if it is you don't have to duplicate it.

2020-07-03 21:23 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                this.Layers.Add(new Layer(otherLayer));
This `Layer` constructor doesn't actually duplicate the shader in it (even if necessary) so still gotta do that.

2020-07-06 19:18 UTC, PJB3005 approved these changes

2020-07-06 19:21 UTC, merged