FloatMathDSL, Shader Dev Window, Color Slider Breakout
space-wizards/RobustToolbox pull request #1145
Opened 2020-06-23 04:16 UTC by Tyler-IN

add shader dev window

break out color Slider

add ColorRect control

add FloatMathDsl & flavors

2020-06-23 11:59 UTC, Zumorica commented on Robust.Client/UserInterface/Control.cs
> +        ///     Make the provided control a parent of this control.
Shouldn't this be the opposite?

2020-06-23 11:59 UTC, Zumorica commented on Robust.Shared/Utility/FloatMathDsl.cs
> +    /// Represents a language to that handles basic mathematics out-of-game.
```suggestion
    /// Represents a language that handles basic mathematics out-of-game.
```

2020-06-23 11:59 UTC, Zumorica commented on Robust.Shared/Utility/InGameFloatMathDsl.cs
> +    /// Represents a language to that handles basic mathematics in-game.
```suggestion
    /// Represents a language that handles basic mathematics in-game.
```

2020-06-23 15:57 UTC, Tyler-IN commented on Robust.Client/UserInterface/Control.cs
> +        ///     Make the provided control a parent of this control.
```suggestion
        ///     Make the provided control a child of this control.
```
Was copy pasta.

2020-06-26 12:45 UTC, PJB3005 requested changes

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Control.Styling.cs
> +        public ICollection<string> StyleClasses { get; set; }
This should absolutely not be public set. It gets set to a special collection implementation that correctly updates the internal set and queues for style updates.

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Control.cs
> +            DebugTools.Assert(!Disposed, "Control has been disposed.");
Unify these precondition checks with `AddChild()`.

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ColorRect.cs
> +            if (!TryGetStyleProperty("color", out Color color))
You've got this backwards. Local properties (like `Color` here) should override the style properties. Not the other way around.

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ColorRect.cs
> +            handle.DrawRect(UIBox2.FromDimensions(Vector2.Zero, PixelSize), color);
```suggestion
            handle.DrawRect(PixelSizeBox, color);
```

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ColorSlider.cs
> +﻿#nullable enable
`Robust.Client` is already nullable enabled. This isn't necessary.

2020-06-26 12:45 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ColorSlider.cs
> +        public ColorSlider(string styleClass) : this()
This kind of styling should instead be done with a CSS child selector:

```css
ColorSlider .fooClass > Slider {
	/* Properties */
}
```

2020-11-27 00:01 UTC, AJCM-git commented
superseded by #1407

2020-11-27 00:01 UTC, closed without merging