De-lagging clickcode - pt 1
space-wizards/RobustToolbox pull request #115
Opened 2017-05-06 22:34 UTC by CrAzYPiLoT-SS13

Removes one of the most costly parts of clickcode, the copy of textures from the GPU VRAM to RAM to check for opaque pixels. Also removes a stray folder in a project. This reduces lag on click significantly, with a bit still left over - a WIP.

Oh, and the limit for considering a pixel clickthrough is currently an alpha of 64, easily changed.

2017-05-06 22:43 UTC, PJB3005 commented on SS14.Client.Interfaces/Resource/IResourceManager.cs
> +        Dictionary<Texture, string> textureToKey
Make this only take one line please.

2017-05-06 22:43 UTC, psykzz commented on SS14.Client.Services/ResourceManagment/ResourceManagerZip.cs
> +                int pos = 0; //easier than to calculate the position every time down in the loops
Does this not need an increment somewhere in your loop?

2017-05-06 22:43 UTC, PJB3005 commented on SS14.Client.Services/ResourceManagment/ResourceManagerZip.cs
> +        public Dictionary<Texture, string> textureToKey
Use `=> _textureToKey;` here.

2017-05-06 22:44 UTC, PJB3005 commented on SS14.Client.Services/ResourceManagment/ResourceManagerZip.cs
> +                bool[] clickthrough = new bool[img.Size.X * img.Size.Y];
Use a 2D array here.

That or stack bits so you can fit 8 bits into one byte.

2017-05-06 22:46 UTC, psykzz commented on SS14.Client.Services/ResourceManagment/ResourceManagerZip.cs
> +                int pos = 0; //easier than to calculate the position every time down in the loops
Should you not increment this in your loop?

2017-05-06 22:47 UTC, RemieRichards commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            bool[] clickthrough = TextureCache.Textures[textureKey].Item2; //get our clickthrough 'map'
need us some sweet C# 7 named tuples, fuck ```.ItemN```

2017-05-06 22:49 UTC, PJB3005 commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            bool[] clickthrough = TextureCache.Textures[textureKey].Item2; //get our clickthrough 'map'
I don't think Mono supports C# yet.

2017-05-06 22:50 UTC, RemieRichards commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            bool[] clickthrough = TextureCache.Textures[textureKey].Item2; //get our clickthrough 'map'
It doesn't, but a girl can dream!

Just make a note somewhere: "< C#7 tuples suck pls fix"

2017-05-06 23:03 UTC, BobdaBiscuit requested changes

2017-05-06 23:03 UTC, BobdaBiscuit commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            IResourceManager _resManager = IoCManager.Resolve<IResourceManager>();
Add this to AnimatedSpriteComponent.cs aswell to deal with the remaining lag, it's from the player entity which is obviously animated.

2017-05-06 23:22 UTC, RemieRichards commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            bool[] clickthrough = TextureCache.Textures[textureKey].Item2; //get our clickthrough 'map'
Also @CrAzYPiLoT-SS13 ```clickthrough``` is a bad name I feel, since the true case is an opaque pixel, where clickthrough implies it would be a transparent or "click-through-able" pixel.

Don't have much of an idea for an alternate name though. (```bool[] opaquePixels```?)

2017-05-07 06:12 UTC, CrAzYPiLoT-SS13 commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            IResourceManager _resManager = IoCManager.Resolve<IResourceManager>();
Aye.

2017-05-07 06:14 UTC, CrAzYPiLoT-SS13 commented
I realized I made a hilarious math fuck-up which didn't allow me to sleep last night, but it'll be deprecated anyway once I introduce 2D arrays, so yeah.

2017-05-08 00:40 UTC, ComicIronic commented on SS14.Client.GameObjects/Component/Renderable/SpriteComponent.cs
> +            bool[] clickthrough = TextureCache.Textures[textureKey].Item2; //get our clickthrough 'map'
C# 7.0 : Eventually we will be functional and Java will die.

2017-05-08 11:03 UTC, CrAzYPiLoT-SS13 commented
There we go, not a smidge of lag left. Although you cannot pick up items anymore due to how ridiculous oldcoders are and thought this could ever work without checking the TAI. Fixing that is outside the scope of this PR.

2017-05-08 11:23 UTC, ComicIronic commented on SS14.Client.GameObjects/Component/Renderable/AnimatedSpriteComponent.cs
> +            if(!tmp.ContainsKey(spriteToCheck.Texture)) return false; //if it doesn't exist, something's fucked
Don't use unbraced ifs.

2017-05-08 11:24 UTC, ComicIronic commented on SS14.Client.Interfaces/Resource/IResourceManager.cs
> +        Dictionary<Texture, string> textureToKey { get; }
Public properties should be capitalised.

2017-05-08 11:25 UTC, ComicIronic commented on SS14.Client.Graphics/Sprite/SpriteInfo.cs
> +        public const byte ClickthroughLimit = 64;
Could you add a comment to this explaining that it's the alpha value?

2017-05-08 11:25 UTC, ComicIronic commented
Other than those things, LGTM.

2017-05-08 11:31 UTC, ComicIronic approved these changes

2017-05-08 14:45 UTC, psykzz approved these changes

2017-05-08 21:33 UTC, merged