Atmos changes
space-wizards/RobustToolbox pull request #1186
Opened 2020-07-19 16:38 UTC by Zumorica

Changes needed for atmos.
Some of these changes aren't needed anymore and I'll remove them in due time

2020-07-27 18:44 UTC, Zumorica commented
Ready for review.

2020-08-01 14:49 UTC, PJB3005 requested changes

2020-08-01 14:49 UTC, PJB3005 commented on Robust.Shared.Maths/Direction.cs
> +        public static Angle ToAngle(this Vector2i vec)
You can already do this by doing `new Angle(vec)`

2020-08-01 14:49 UTC, PJB3005 commented on Robust.Shared/Map/Coordinates.cs
> +            return new MapIndices((int)MathF.Floor(X), (int)MathF.Floor(Y));
Grids are not guaranteed to have a tile size of one. This method is incorrect.

2020-08-01 14:49 UTC, PJB3005 commented on Robust.Shared/Map/MapIndices.cs
> +            return new GridCoordinates(X, Y, gridId);
Again, these are not necessarily correct.

2020-08-01 14:49 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            if (type.IsArray)
You messed this merge up, and accidentally removed the `TryGenericReadOnlyCollectionType` code.

2020-08-02 00:58 UTC, Zumorica commented on Robust.Shared.Maths/Direction.cs
> +        public static Angle ToAngle(this Vector2i vec)
Done.

2020-08-02 01:00 UTC, gradientvera commented on Robust.Shared/Map/Coordinates.cs
> +            return new MapIndices((int)MathF.Floor(X), (int)MathF.Floor(Y));
Fixed this. Now it gets the actual tile indices from the grid.

2020-08-02 01:00 UTC, Zumorica commented on Robust.Shared/Map/MapIndices.cs
> +            return new GridCoordinates(X, Y, gridId);
Changed this to multiply X and Y by the grid's tile size. I think that should be correct?

2020-08-02 01:00 UTC, Zumorica commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            if (type.IsArray)
Oops. Fixed now, I think?

2020-08-02 01:00 UTC, Zumorica commented
Reviews addressed.

2020-08-02 15:32 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +                    }
```suggestion
                    AssignTag<object?>(element, entry, null, entryNode);
```

2020-08-02 15:33 UTC, PJB3005 approved these changes

2020-08-02 16:39 UTC, merged