1464 Ignore text functions if no keyboard is focused
space-wizards/RobustToolbox pull request #1199
Opened 2020-07-29 21:08 UTC by StrawberryMoses

Fixes https://github.com/space-wizards/space-station-14/issues/1464

If there's no keyboard focused, ignore all commands that have "Text". IE: TextSelectAll which makes control A not moving left.

2020-07-29 22:40 UTC, Zumorica commented on Robust.Client/Input/InputManager.cs
> +                    || (_userInterfaceManagerInternal.KeyboardFocused == null && binding.Function.FunctionName.Contains("Text")))
I feel like basing this on the name of the function is not a good idea exactly...

2020-07-29 22:43 UTC, StrawberryMoses commented on Robust.Client/Input/InputManager.cs
> +                    || (_userInterfaceManagerInternal.KeyboardFocused == null && binding.Function.FunctionName.Contains("Text")))
It was mostly just because I'm lazy. All of the functions that appeared to need blocking in normal movement mode (in KeyFunctions.cs) are all prepended with "Text". The other option that I considered was to add specific ones to a list and then check if the list contained the function name.

2020-07-29 23:23 UTC, PJB3005 requested changes
Yeah this really isn't a good solution. The proper solution I can think of would be to consider keycombos with subset of the best match (instead of ONLY the best match) if the key handlers aren't getting handled.

2020-08-04 23:44 UTC, StrawberryMoses commented
Ok- so I really dunno if this is the correct solution, but it seems to work. It adds to the bindsDown list if it matches (but isn't the combo or a sub pattern), then the foreach on 169 tests if things were handled. Oddly enough it makes it seem like this used to work.

2020-11-20 22:39 UTC, SweptWasTaken commented
Someone review this.

2021-01-07 01:26 UTC, metalgearsloth commented
Superseded by #1473

2021-01-07 01:26 UTC, closed without merging