Add nullable API methods for getting components and user interfaces
space-wizards/RobustToolbox pull request #1241
Opened 2020-08-19 21:51 UTC by DrSmugleaf

Needed for a future pr that tests adding all components to an entity.

Because writing this is getting a bit old:
```cs
private BoundUserInterface? UserInterface =>
            Owner.TryGetComponent(out ServerUserInterfaceComponent ui) &&
            ui.TryGetBoundUserInterface(MagicMirrorUiKey.Key, out var boundUi)
                ? boundUi
                : null;
```

Instead of:
```cs
private BoundUserInterface? UserInterface => Owner.TryGetComponent<ServerUserInterfaceComponent>()?.TryGetBoundUserInterface(MagicMirrorUiKey.Key);
```

CanBeNull is used in one place because otherwise the generic would have to be restricted to being a class.

2020-08-20 13:12 UTC, PJB3005 requested changes

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs
> +        public BoundUserInterface? TryGetBoundUserInterface(object uiKey)
This should probably be called `GetBoundUserInterfaceOrNull` instead

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Shared/GameObjects/Entity.cs
> +        public T TryGetComponent<T>() where T : IComponent
1. Make this `GetComponentOrNull`.
2. The nullability anotations are wrong here. Do `[return: MaybeNull]` instead (and get rid of the `!` down below)

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Shared/GameObjects/Entity.cs
> +        public IComponent? TryGetComponent(Type type)
`GetComponentOrNull`

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Shared/GameObjects/Entity.cs
> +        public IComponent? TryGetComponent(uint netId)
`GetComponentOrNull`

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Shared/Interfaces/GameObjects/IEntity.cs
> +        [CanBeNull]
`CanBeNull` are JetBrains annotations, not C# 8 ones. You still need `[return: MaybeNull]` here.

2020-08-20 13:12 UTC, PJB3005 commented on Robust.Shared/Interfaces/GameObjects/IEntity.cs
> +        T TryGetComponent<T>() where T : IComponent;
I think you know what I'm about to say here.

2020-08-21 17:12 UTC, DrSmugleaf commented
Reviews addressed.

2020-08-22 11:56 UTC, PJB3005 approved these changes

2020-08-22 11:56 UTC, merged