Replace every usage of GridCoordinates with EntityCoordinates
space-wizards/RobustToolbox pull request #1280
Opened 2020-09-04 16:00 UTC by DrSmugleaf

Requires https://github.com/space-wizards/RobustToolbox/pull/1277

2020-09-04 16:02 UTC, Zumorica commented
(This will require a merge/rebase after #1277 is merged) 
:+1:

2020-09-04 16:39 UTC, Zumorica requested changes
MapGrid needs some name changes. EntityCoordinates are ALWAYS relative, so treating them as "world" coordinates is bad, even if just in method and argument names

2020-09-04 16:39 UTC, Zumorica commented on Robust.Client/Graphics/ClientEye/EyeManager.cs
> +        public ScreenCoordinates WorldToScreen(EntityCoordinates point)
See: https://discordapp.com/channels/310555209753690112/310555209753690112/751473320116879370

2020-09-04 16:39 UTC, Zumorica commented on Robust.Server/GameObjects/ServerEntityManager.cs
>                  newEntity.Transform.AttachParent(GetEntity(gridEntityId));
Attach the new entity to the `EntityId` in `EntityCoordinates` instead of the grid.

2020-09-04 16:39 UTC, Zumorica commented on Robust.Server/GameObjects/ServerEntityManager.cs
> +            var grid = _mapManager.GetGrid(gridId);
Same as above. If we don't change this, making EntityCoordinates will have been for nothing :pensive:

2020-09-04 16:39 UTC, Zumorica commented on Robust.Server/Interfaces/Player/IPlayerManager.cs
> +        List<IPlayerSession> GetPlayersInRange(EntityCoordinates worldPos, int range);
Maybe this should take in a `MapCoordinates` instead, since it's meant to be world position. Feel free to add an overload that takes in `EntityCoordinates` tho, though that one should just use `.ToMap()` and forward to the one using `MapCoordinates`

2020-09-04 16:40 UTC, gradientvera commented
Also this broke some tests it seems :cold_sweat:

2020-09-05 22:04 UTC, exp111 reviewed
There is also `Set both an AttachedEntityUid and GridCoordinates on an EffectSystemMessage ...` in EffectSystem.CreateEffect

2020-09-05 22:04 UTC, exp111 commented on Robust.Shared/Map/MapIndices.cs
> +        public EntityCoordinates ToGridCoordinates(IMapManager mapManager, GridId gridId)
Confusing name

2020-09-05 22:04 UTC, exp111 commented on Robust.Client/Placement/PlacementMode.cs
> +        public IEnumerable<EntityCoordinates> GridCoordinates()
Name

2020-09-05 22:04 UTC, exp111 commented on Robust.Shared/Network/Messages/MsgPlacement.cs
> +        public EntityCoordinates GridCoordinates { get; set; }
Here too

2020-09-06 13:10 UTC, Zumorica commented on Robust.Client/Placement/PlacementMode.cs
> +        public IEnumerable<EntityCoordinates> GridCoordinates()
let this server as a reminder

2020-09-06 14:09 UTC, merged