Add YAML serialization for nullable primitive types
space-wizards/RobustToolbox pull request #1299
Opened 2020-09-30 19:20 UTC by DrSmugleaf

Otherwise it believes its a struct and fails the YamlMappingNode cast.

Needed for https://github.com/space-wizards/space-station-14/pull/2074

2020-10-02 12:55 UTC, PJB3005 requested changes

2020-10-02 12:55 UTC, PJB3005 commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            if (str.Equals("null", StringComparison.InvariantCultureIgnoreCase))
So if I have a string with the exact contents `"null"`...

Honestly I would use type tags to encode "really really null" for this instead.

2020-10-02 20:27 UTC, DrSmugleaf commented on Robust.Shared/Serialization/YamlObjectSerializer.cs
> +            if (str.Equals("null", StringComparison.InvariantCultureIgnoreCase))
As it turns out I didn't even need that check at all, it already handles nulls just fine. Oops.

2020-10-02 20:27 UTC, DrSmugleaf commented
Reviews addressed.

2020-10-03 13:29 UTC, PJB3005 approved these changes

2020-10-03 13:29 UTC, merged