Things needed for singulo
space-wizards/RobustToolbox pull request #1306
Opened 2020-10-05 11:07 UTC by PaulRitter

2020-10-05 23:57 UTC, PJB3005 requested changes

2020-10-05 23:57 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +        public event EventHandler<ValueChangedEventArgs> ValueChanged = null!;
Don't `= null!` this. Define the event as type `EventHandler<ValueChangedEventArgs>?` instead, because that's what it actually is. (events are null if nothing is registered to them).

2020-10-06 07:08 UTC, PaulRitter commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +        public event EventHandler<ValueChangedEventArgs> ValueChanged = null!;
you're right. i've worked with events before, just not when using the nullable annotation.

2020-10-07 08:37 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +        public void SetLineEditDisabled(bool disabled)
Make this a property instead?

2020-10-07 08:37 UTC, PJB3005 commented on Robust.Server/Placement/PlacementManager.cs
> +                    normal = new Angle(deltaVec).GetCardinalDir().ToVec();
What's this do?

2020-10-07 15:04 UTC, PaulRitter commented on Robust.Server/Placement/PlacementManager.cs
> +                    normal = new Angle(deltaVec).GetCardinalDir().ToVec();
a fix to a runtime introduced by deltaVec being zero and then getting the cardinal dir `-123124124124`. you get it, some arbitrary high number, which then throws due to the tovec() loopup I introduced

it will literally fail every time without this fix. as far as i can tell it works, my assumption is that deltaVec was always 0,0 and it just went unnoticed.

2020-10-09 09:41 UTC, PJB3005 approved these changes

2020-10-09 12:55 UTC, merged