Componentdependency
space-wizards/RobustToolbox pull request #1311
Opened 2020-10-09 22:22 UTC by PaulRitter

ToDo:
- [x] write unit tests
- [x] fix retrieverdelegate
- [X] ~~restrict attribute to be only allowed on fields who are subclasses of component so the linter complains (?)~~ just dont be a dumbdumb
- [x] consider componentreference attribute for dependencies (?)

2020-10-10 23:14 UTC, PJB3005 requested changes
Definitely gonna want to look into ref abuse stuff to make these assignments less painful.

2020-10-10 23:14 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +            Dictionary<Type, object> entityComponents = new Dictionary<Type, object>();
Making this copy dictionary is *extremely* wasteful and expensive, especially because this method gets called any time a component gets added to an entity.

Why not just `TryGetComponent` in the loop on line 69 where you're iterating the types that need to be injected?

2020-10-10 23:14 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +        /// Sets all dependencies onto compType's references, which are present in entity, to the value of comp
```suggestion
        /// Updates all dependencies to type compType on the entity (in fields on components), to the value of comp
```
Slightly more clear what this does since this took me 30 seconds of reading to figure out.

2020-10-10 23:14 UTC, PJB3005 commented on Robust.Shared/Utility/NullableHelper.cs
> +        private static void CacheGetNullableFlag(Assembly assembly)
This seems really overengineered when you can just use `FieldInfo.GetValue()` for this instead. It's not a critical code path and reflection isn't THAT slow.

2020-10-12 07:47 UTC, RemieRichards commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +        private readonly Dictionary<Type, (Type, int)[]> _componentDependencyQueries = new Dictionary<Type, (Type, int)[]>();
Please name your tuple fields. None of this `.Item1` `.Item2` nonsense.

```cs
(SomeType someName, SomeType2, someName2, ...)
```

2020-10-12 07:48 UTC, RemieRichards commented on Robust.Shared/Utility/NullableHelper.cs
> +            if (flags.Length != 0 && flags[0] == 2) return true;
What is this magical `2` you speak of? Make a named constant please.

2020-10-12 07:56 UTC, RemieRichards commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                    throw new Exception($"Field {field} of Type {objType} is marked as ComponentDependecy, but does not have ?(Nullable)-Flag!");
Dependecy isn't a word :P

2020-10-12 07:57 UTC, RemieRichards commented on Robust.Shared/Utility/NullableHelper.cs
> +        private static Dictionary<Assembly, (Type, FieldInfo)> _nullableAttributeTypeCache = new Dictionary<Assembly, (Type, FieldInfo)>();
Same as before, name your tuple fields.

2020-10-12 11:59 UTC, PaulRitter commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +        private readonly Dictionary<Type, (Type, int)[]> _componentDependencyQueries = new Dictionary<Type, (Type, int)[]>();
I CAN NAME TUPLE FIELDS?!?!?!?!

2020-10-12 11:59 UTC, PaulRitter commented on Robust.Shared/Utility/NullableHelper.cs
> +            if (flags.Length != 0 && flags[0] == 2) return true;
https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md

2020-10-12 11:59 UTC, PaulRitter commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                    throw new Exception($"Field {field} of Type {objType} is marked as ComponentDependecy, but does not have ?(Nullable)-Flag!");
😬

2020-10-12 12:02 UTC, PaulRitter commented on Robust.Shared/Utility/NullableHelper.cs
> +            if (flags.Length != 0 && flags[0] == 2) return true;
`Each type reference in metadata may have an associated NullableAttribute with a byte[] where each byte represents nullability: 0 for oblivious, 1 for not annotated, and 2 for annotated.`
where would i create constants for this?

2020-10-12 12:04 UTC, RemieRichards commented on Robust.Shared/Utility/NullableHelper.cs
> +            if (flags.Length != 0 && flags[0] == 2) return true;
Yes, I'm aware of what it means, it's just not clear to an outside reader.
if you had a const int called say, `AnnotatedNullableFlag`:

```cs
if (flags.Length != 0 && flags[0] == 2) return true;

//vs

if (flags.Length != 0 && flags[0] == AnnotatedNullableFlag) return true;

```

One of these is much more readable!

2020-10-12 12:06 UTC, RemieRichards commented on Robust.Shared/Utility/NullableHelper.cs
> +            if (flags.Length != 0 && flags[0] == 2) return true;
@PaulRitter you're just using 2, so realistically you'd only have to define 2 (the others, 0 and 1 would complain about never being used, which is lame)

Since they're only used in this file (as far as I can see?) just stick it at the top of the class.

`public static int AnnotatedNullableFlag = 2;`

2020-10-12 12:07 UTC, RemieRichards commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +        private readonly Dictionary<Type, (Type, int)[]> _componentDependencyQueries = new Dictionary<Type, (Type, int)[]>();
yep. very useful feature.

2020-10-12 15:03 UTC, PJB3005 requested changes

2020-10-12 15:03 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                var offset = @delegate(obj);
I would prefer if you moved this entire bit into its own method.

2020-10-12 15:03 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +            foreach (var field in attributeFields)
If you are going to keep track of an `i` counter like that then make the loop over `attributeFields` a normal for loop instead.

2020-10-12 15:03 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                if (!NullableHelper.IsMarkedAsNullable(field))
You should probably explicitly check that the fields here are reference types so that the attribute on e.g. `Vector2 position` gets rejected early.

2020-10-12 15:03 UTC, PJB3005 commented on Robust.Shared/Utility/NullableHelper.cs
> +        private static Dictionary<Assembly, (Type AttributeType, FieldInfo FlagsField)> _nullableContextAttributeTypeCache = new Dictionary<Assembly, (Type AttributeType, FieldInfo FlagsField)>();
You have two problems here with this cache:
1. No locking so this is completely non-threadsafe. And yes, threads will definitely touch this because of integration testing.
2. This can cause issues with assembly unloading if we ever explore that.

You can solve (2) by using a [`ConditionalWeakTable<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=netcore-3.1) instead of a normal dictionary.

2020-10-12 15:03 UTC, PJB3005 commented on Robust.Shared/Utility/NullableHelper.cs
> +                throw new Exception($"No System.Runtime.CompilerServices.NullableAttribute found in Assembly {assembly}");
This is something that can totally reasonably happen from the assembly just being compiled without any nullable annotations. You should not log an error here and treat the entire assembly as being oblivious (0).

2020-10-13 12:02 UTC, PJB3005 commented on Robust.Shared/Utility/NullableHelper.cs
> +            lock (_nullableAttributeTypeCache)
Do not lock it again inside these cache methods. The lock is and MUST already held by the calling Get* method and locking twice like this is generally frowned upon.

2020-10-13 12:13 UTC, PaulRitter commented on Robust.Shared/Utility/NullableHelper.cs
> +            lock (_nullableAttributeTypeCache)
got it

2020-10-13 12:22 UTC, PJB3005 approved these changes

2020-10-13 12:22 UTC, merged