adds onadd & onremove methods to componentdependencies
space-wizards/RobustToolbox pull request #1336
Opened 2020-10-15 22:05 UTC by PaulRitter

2020-10-19 09:07 UTC, PaulRitter commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                    throw new NotImplementedException();//todo check if attribute null
@PJB3005 should i really check if it failed to get the attribute? it only runs the select (l139) on fields where `Attribute.IsDefined(f, typeof(ComponentDependencyAttribute)`

2020-10-19 10:16 UTC, PaulRitter commented
Ready for review.
Idea behind this is to have a place to sanely (un)subscribe to component events etc

2020-10-20 07:21 UTC, PJB3005 requested changes

2020-10-20 07:21 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +            Dictionary<Type, (Type Query, int FieldMemoryOffset, MethodInfo? OnAddMethod, MethodInfo? OnRemoveMethod)[]>
1. At this point these tuples are so large you should switch them to a full blown class.
2. Caching `MethodInfo` instances and calling `.Invoke()` on them is like 90x slower than caching a delegate and calling it. See https://codeblog.jonskeet.uk/2008/08/09/making-reflection-fly-and-exploring-delegates/

2020-10-28 13:19 UTC, PaulRitter commented
@PJB3005 ready for review

2020-10-30 00:18 UTC, PJB3005 requested changes

2020-10-30 00:18 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +                    getterMethod = typeof(ComponentDependencyManager).GetMethod("GetEventMethodDelegate",
Move this method get to outside the two if statements so you don't duplicate it. If you care about not bothering with it when no add/remove methods are specified just wrap the entire thing in a check for either not being null.

2020-10-30 00:18 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
> +    public abstract class ComponentDependencyInvalidMethodName : Exception
This name needs to end with `Exception`.

2020-10-30 00:18 UTC, PJB3005 commented on Robust.UnitTesting/Shared/GameObjects/ComponentDependencies_Tests.cs
> +            [ComponentDependency("ABCDEF")] public TestFiveComponent? thing;
Mute these compiler warnings.

2020-10-30 15:21 UTC, PaulRitter commented
reviews adressed

2020-11-01 22:24 UTC, PJB3005 approved these changes

2020-11-01 22:24 UTC, merged