Add timer component
space-wizards/RobustToolbox pull request #1358
Opened 2020-10-28 15:14 UTC by DrSmugleaf

For pausing timers if their entity is paused.
Content PR pending.

2020-10-28 15:21 UTC, PJB3005 requested changes

2020-10-28 15:21 UTC, PJB3005 commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public void AddTimer(Timer timer, CancellationTokenSource? cancellationToken = null)
You don't take in a `CancellationTokenSource`. You take in the `CancellationToken` itself.

2020-10-29 00:00 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public void AddTimer(Timer timer, CancellationTokenSource? cancellationToken = null)
Fixed.

2020-10-29 00:00 UTC, DrSmugleaf commented
Reviews addressed.

2020-10-29 00:01 UTC, RemieRichards commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        private readonly List<(Timer timer, CancellationToken source)>
name your tuple fields!!!!

2020-10-29 00:30 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/TimerSystem.cs
> +            foreach (var timer in ComponentManager.EntityQuery<TimerComponent>())
Use false here and you can remove the paused check from the component itself.

The paused property might be removed from the entity someday if someone can make the checks faster but this just means you won't need to refactor it.

2020-10-29 00:35 UTC, metalgearsloth requested changes

2020-10-29 00:35 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +            _timers.RemoveAll(timer => !timer.Item1.IsActive || (timer.source.IsCancellationRequested));
linq bad

2020-10-29 00:35 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public Task Delay(int milliseconds, CancellationToken cancellationToken = default)
Should there be an async version

2020-10-29 07:01 UTC, metalgearsloth commented
Fixes #894

2020-10-29 09:21 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public Task Delay(int milliseconds, CancellationToken cancellationToken = default)
Probably, ye

2020-10-29 11:40 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Systems/TimerSystem.cs
> +            foreach (var timer in ComponentManager.EntityQuery<TimerComponent>())
Done.

2020-10-29 12:15 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public Task Delay(int milliseconds, CancellationToken cancellationToken = default)
Done, tell me if that's correct or not.

2020-10-29 12:16 UTC, DrSmugleaf commented
Reviews addressed.

2020-10-29 12:21 UTC, metalgearsloth approved these changes

2020-10-29 15:24 UTC, PJB3005 commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public Task Delay(int milliseconds, CancellationToken cancellationToken = default)
That makes no sense. `async` is purely the *implementation* of the method. This method already *is* the async version since it returns a `Task`

2020-10-29 18:20 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
> +        public Task Delay(int milliseconds, CancellationToken cancellationToken = default)
Reverted.

2020-10-30 00:01 UTC, PJB3005 approved these changes

2020-10-30 00:01 UTC, merged