Rotatable bounding boxes
space-wizards/RobustToolbox pull request #1360
Opened 2020-10-29 01:04 UTC by PaulRitter

wha- is it actually? might zumo actually be able to start using edge-firelocks?!?!?

no stackoverflow copypasta, i offered my sleep for this, its 2am

needs fixing:
- [ ] debug draw fill

pics:
![grafik](https://user-images.githubusercontent.com/16618384/97512838-cf5b9900-198a-11eb-8e8a-c12cfb76fd8e.png)
(sprite doesn't rotate non-cardinal dirs, just imagine a 45° light there)
![grafik](https://user-images.githubusercontent.com/16618384/97512845-d2ef2000-198a-11eb-8377-89657d35db0b.png)
![grafik](https://user-images.githubusercontent.com/16618384/97512848-d5ea1080-198a-11eb-926b-620a4e183b6f.png)

2020-10-29 08:54 UTC, PaulRitter commented on Robust.Shared.Maths/Box2Rotated.cs
> +            float[] allY = new float[4];
this seems to alloc alot of ram... any idea of optimizing this? @PJB3005

2020-10-30 16:55 UTC, PaulRitter commented
ready for review

2020-11-01 07:55 UTC, metalgearsloth requested changes
Looks fine to me, would need to see how it profiles. I'd also need to see how it works ingame as all of the Box2 methods were built under the assumption it's an AABB (I don't know how much PhysShapeRect was used in the past).

2020-11-01 07:55 UTC, metalgearsloth commented on Robust.Shared.Maths/Box2Rotated.cs
> +            float[] allY = new float[4];
Spans?

2020-11-01 07:55 UTC, metalgearsloth commented on Robust.Shared/Physics/PhysShapeRect.cs
> +            List<BoundingBoxOverridePrototype> overrides = new List<BoundingBoxOverridePrototype>();
var

2020-11-01 07:55 UTC, metalgearsloth commented on Robust.Shared/Physics/PhysShapeRect.cs
> +    /// A physics shape that represents an Axis-Aligned Bounding Box.
(No longer axis-aligned). Represents an OBB more now.

2020-11-01 13:33 UTC, PaulRitter commented
>  I'd also need to see how it works ingame as all of the Box2 methods were built under the assumption it's an AABB (I don't know how much PhysShapeRect was used in the past).

if i understand what an AABB is correctly, what im doing is converting the OBB (PhysShapeRect) into an AABB in `CalcBoundingBox`

at least it works ingame :D

2020-11-04 00:55 UTC, PJB3005 reviewed
The bounding box override stuff would probably be better served as something explicitly supported by collidable component so certain phys shapes are only selected at certain angles.

That said, it seems like a *really* bad idea so I would like to know what problem it's actually solving here.

2020-11-04 00:55 UTC, PJB3005 commented on Robust.Client/ViewVariables/Editors/VVPropEditorUIBox2.cs
> +                    hBoxContainer.AddChild(right);
This should most definitely stay `LBTR` order. I know prototypes have stupid ordering here, those should be fixed instead. X coordinate naturally comes before Y.

2020-11-04 08:34 UTC, PaulRitter commented
> That said, it seems like a _really_ bad idea so I would like to know what problem it's actually solving here.

imo you will have cases where the the sprite wont rotate according to origin (example: poweredlight)
altough maybe making another physshape and defining all cardinal dirs would probably be a better solution here(?)

2020-11-04 15:18 UTC, PJB3005 commented
For those kinds of cases the hitbox literally does not matter and can *never* be correct anyways because the sprite is always dependent on camera rotation, so it's impossible to ever match a hitbox to.

2020-11-16 00:45 UTC, PJB3005 commented on Robust.Shared/Physics/PhysShapeRect.cs
> +            var m = Matrix3.Identity;
Get rid of all of this and get rid of the `angle` parameter aswell. That's what `modelMatrix` is for. (Yes I know this was here because of the now-gone override code)

2020-11-16 00:51 UTC, PJB3005 commented on Robust.Shared.Maths/Box2Rotated.cs
> +            Span<float> allX = stackalloc float[4];
Don't these modifications make the method SIGNIFICANTLY more expensive? You're doing sin/cos 4 times now by fetching corners like that.

Why did you change this? Was the previous method broken?

2020-11-16 21:00 UTC, PaulRitter commented on Robust.Shared.Maths/Box2Rotated.cs
> +            Span<float> allX = stackalloc float[4];
the previous method would rotate along the bb center, instead of the entity center.

2020-11-19 02:39 UTC, PJB3005 commented on Robust.Shared.Maths/Box2Rotated.cs
> +            Span<float> allX = stackalloc float[4];
I would prefer if the previous implementation was fixed then to fix the problem. If not, at the very least some unit tests please.

2020-12-07 12:20 UTC, Zumorica approved these changes
The SSE math looks good to me

2020-12-07 16:01 UTC, merged