Numerics Helpers: SIMD accelerated array math methods
space-wizards/RobustToolbox pull request #1380
Opened 2020-11-02 16:36 UTC by Zumorica

**Important note: Do NOT merge without @PJB3005's review & explicit approval.**

- Should this take in `Span<float>` instead?

2020-11-02 16:37 UTC, moonheart08 commented
I'll take a peek later tonight as well.

2020-11-02 16:39 UTC, moonheart08 commented
Quick cursory glance shows that it seems to require alignment of the arrays. The SSE functions don't have an entry loop that handles being 1-3 doublewords unaligned, it just starts with the SSE loop and then ends with an alignment handle.

2020-11-02 16:43 UTC, moonheart08 requested changes
None of the functions handle alignment
Once you fix alignment, you can also use the unaligned SSE loads for a small boost.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +                fixed (float* ptrB = b)
Handle unaligned entry?

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            {
Handle unaligned entry here too.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            {
And here.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
Here.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
and here.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
Heeere.

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
aaaaaaa

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            {
I think the only reason this works is because LoadVector doesn't mandate alignment...

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
abcdef

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
[INSERT COPY PASTE HERE]

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            {
[INSERT COPY PASTE HERE]

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
[INSERT COPY PASTE HERE]

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            {
[INSERT COPY PASTE HERE]

2020-11-02 16:43 UTC, moonheart08 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +            fixed (float* ptr = a)
abcdef

2020-11-03 20:16 UTC, PJB3005 reviewed
All readonly input spans should be, well, `ReadOnlySpan<float>` instead of `Span<float>`.

2020-11-04 11:00 UTC, Zumorica commented
Resolved all reviews regarding loadvector alignment as we agreed on just doing unaligned.

2020-11-04 11:08 UTC, Zumorica commented
> All readonly input spans should be, well, `ReadOnlySpan<float>` instead of `Span<float>`.
@PJB3005 Done. I changed the readonly input spans to be `ReadOnlySpan<float>`.

2020-11-04 20:12 UTC, Zumorica commented
@PJB3005 Should I make a `SseEnabled` static property in `NumericsHelpers` that allows us to dynamically disable/enable the SSE paths? This would be useful for unit tests and benchmarks, along other things.

2020-11-04 20:17 UTC, Zumorica commented
I'm also thinking of coding AVX support, but disabling it and defaulting to the SSE/naive paths unless you enable a CVar for it.

2020-11-09 10:45 UTC, PJB3005 commented
Yes to a static property for disabling it.

The problem with making it a CVar is that you NEED this to be behind a static readonly which you can't read CVars from sanely. You'll have to make it an env var I guess.

2020-11-11 00:58 UTC, Zumorica commented
.NET 5 dropped, so I'm coding ARM support for this now.

2020-11-12 15:16 UTC, Zumorica commented
I added ARM support for this now, so I think this is ready now.
The only thing 'missing' is unit tests.

2020-11-12 22:43 UTC, Zumorica commented
Ready for merge.
Fails to compile on master because the `nuget.config` file also needs to be added to content. Added in space-station-14#2479

2020-11-13 00:22 UTC, PJB3005 requested changes
You should be able to put a `nuget.config` file next to the unit testing project directly, so we don't have to modify content for this. Can you try that?

2020-11-13 00:22 UTC, PJB3005 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +        public const string AvxEnvironmentVariable = "NUMERICS_AVX";
Prefix these with `ROBUST_`

2020-11-13 00:22 UTC, PJB3005 commented on Robust.Shared.Maths/NumericsHelpers.cs
> +        private static bool AvxLengthValid(int arrayLength)
As you've probably already realized, these have pretty awkward names when considering ARM. Maybe make them something like `128SingleLengthValid`?

2020-11-13 12:09 UTC, Zumorica commented on Robust.Shared.Maths/NumericsHelpers.cs
> +        private static bool AvxLengthValid(int arrayLength)
Indeed, renamed them to `LengthValid128Single` and `LengthValid256Single` now. (Can't start method names with numbers sadly)

2020-11-13 12:09 UTC, Zumorica commented on Robust.Shared.Maths/NumericsHelpers.cs
> +        public const string AvxEnvironmentVariable = "NUMERICS_AVX";
Done

2020-11-13 12:11 UTC, Zumorica commented
> You should be able to put a `nuget.config` file next to the unit testing project directly, so we don't have to modify content for this. Can you try that?

Hmm, I've done this but now any content projects that reference `Robust.UnitTesting` (only `Content.Tests` and `Content.IntegrationTests`) fail to build due to not finding the dependency on nuget. Should I add the config to these projects as well?

2020-11-13 19:25 UTC, PJB3005 commented
Eh in that case leave it.

2020-11-23 23:52 UTC, PJB3005 approved these changes

2020-11-25 09:47 UTC, merged