remove an unnecessary, probably remnant calculation
space-wizards/RobustToolbox pull request #139
Opened 2017-05-09 03:10 UTC by gbasood

`x - x = 0`

2017-05-09 16:44 UTC, ComicIronic commented
This actually looks like an error in a previous refactor. Someone replaced two different values with the same one, which is why it's `x - x`.

The second `bounds` should be `_equipBg.GetLocalBounds()` instead, as seen in https://github.com/gbasood/space-station-14/commit/653e2deab21da267e057c515323ab2c69051a37c

2017-05-09 16:44 UTC, ComicIronic requested changes
Actually fix the maths.

2017-05-16 17:04 UTC, gbasood commented
This entire file is a mess, by the way. New vectors are defined over and over and over again when they don't really need to be.

2017-05-18 23:11 UTC, ZoldorfTheWizard approved these changes

2017-05-18 23:12 UTC, merged