EntityPrototypeIcon SpriteSpecifier
space-wizards/RobustToolbox pull request #1401
Opened 2020-11-12 11:15 UTC by PaulRitter

what it says on the tin, really useful for building ui

2020-11-12 16:53 UTC, PaulRitter commented
This PR now also features a slight refactor of Texturerect as well as a new method for the containermanager for the objectives pr

2020-11-13 00:02 UTC, PJB3005 requested changes

2020-11-13 00:02 UTC, PJB3005 commented on Robust.Server/GameObjects/Components/Container/ContainerManagerComponent.cs
> +        public int CountPrototypeOccurencesRecursive(string prototypeId)
This method really should not be in the engine, IMO.

2020-11-14 17:30 UTC, PaulRitter commented on Robust.Server/GameObjects/Components/Container/ContainerManagerComponent.cs
> +        public int CountPrototypeOccurencesRecursive(string prototypeId)
moved to content extension-func

2020-11-16 00:52 UTC, PJB3005 approved these changes

2020-11-16 00:52 UTC, merged