Implemented erasing rectangular areas
space-wizards/RobustToolbox pull request #1419
Opened 2020-11-21 15:25 UTC by ManelNavola

> Ctrl+Click can now be used (the same way as for grid placing) while erasing to delete entities in a free rectangular area (ignores entities with either IMapComponent or IActorComponent)
> Disabled the placing options drop-down menu while erasing to avoid confusion (?)

2020-11-22 14:53 UTC, metalgearsloth requested changes

2020-11-22 14:53 UTC, metalgearsloth commented on Robust.Client/Placement/PlacementManager.cs
> +            var ent = PlayerManager.LocalPlayer!.ControlledEntity;
```suggestion
            var ent = PlayerManager.LocalPlayer?.ControlledEntity;
```

2020-11-22 14:53 UTC, metalgearsloth commented on Robust.Client/Placement/PlacementManager.cs
> +            coordinates = EntityCoordinates.FromMap(ent!.EntityManager, MapManager,
```suggestion
            coordinates = EntityCoordinates.FromMap(ent.EntityManager, MapManager,
```

2020-11-22 14:53 UTC, metalgearsloth commented on Robust.Server/Placement/PlacementManager.cs
> +            EntityCoordinates center = new EntityCoordinates(start.EntityId, (start.Position + end.Position) / 2.0f);
Position is relative to their parent so if their parents are different then this won't work as intended.

2020-11-22 14:53 UTC, metalgearsloth commented on Robust.Server/Placement/PlacementManager.cs
> +                    if (entity.Transform.Coordinates.Y < low || entity.Transform.Coordinates.Y > high)
This as well for example

2020-11-22 14:53 UTC, metalgearsloth commented on Robust.Client/Placement/PlacementManager.cs
> +
Not sure if it needs changing to screenspace or shader needs changing but the rectangle is affected by lighting.

2020-11-22 15:22 UTC, ManelNavola commented
Thanks for the review! I'll fix the code asap

2020-11-22 22:32 UTC, ManelNavola commented on Robust.Server/Placement/PlacementManager.cs
> +            EntityCoordinates center = new EntityCoordinates(start.EntityId, (start.Position + end.Position) / 2.0f);
This should be fixed in the latest commit, let me know if I misunderstood the issue!

2020-11-27 23:57 UTC, PJB3005 commented
While I appreciate the work here, the problem is that `PlacementManager` will have to be torn out sooner or later for legal reasons.

2020-11-28 12:16 UTC, ManelNavola commented
> While I appreciate the work here, the problem is that `PlacementManager` will have to be torn out sooner or later for legal reasons.

Yeah that is true, but maybe it can be of help until then? I mean if the PlacementManager it's going to be rewritten very soon then there's no real reason to merge this.

2020-11-28 14:39 UTC, PJB3005 commented on Robust.Client/Placement/PlacementManager.cs
> +
To make it not affected by lighting you add `light_mode unshaded;` to the top of the shader.

2020-11-29 10:04 UTC, ManelNavola commented on Robust.Client/Placement/PlacementManager.cs
> +
Added the "unshaded" shader which should use `light_mode unshaded;`, now it isn't affected by lighting, but it is affected by shadows nonetheless.

2020-12-14 09:57 UTC, metalgearsloth commented
> 
> 
> > While I appreciate the work here, the problem is that `PlacementManager` will have to be torn out sooner or later for legal reasons.
> 
> Yeah that is true, but maybe it can be of help until then? I mean if the PlacementManager it's going to be rewritten very soon then there's no real reason to merge this.

The main people who'd need it would be moony or swept I think, and moony's just started rewriting the placementmanager now (though who knows whether or not they finish).

2021-02-11 06:45 UTC, Acruid commented
Since it won't be merged, should this stay open?

2021-02-27 04:52 UTC, Acruid commented
Who knows when the placement system will be rewritten, so in the meantime I'm merging this so people can enjoy it.

2021-02-27 04:52 UTC, merged