Add EnsureComponentWarn methods
space-wizards/RobustToolbox pull request #1431
Opened 2020-12-02 20:29 UTC by DrSmugleaf

Ensures a component, if it doesn't exist it logs a warning. A lot of components in content were repeating this pattern manually in different places.

2020-12-03 14:07 UTC, PJB3005 requested changes

2020-12-03 14:07 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentExt.cs
> +                        + $"at {entity.Transform.MapPosition} did not have a {nameof(T)}";
1. Entities already have their prototype ID in their `ToString()` so you can at least cut that part out.
2. `nameof(T)` just returns `"T"`. You need `typeof(T)` here.

2020-12-03 14:07 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentExt.cs
> +                        + $"at {entity.Transform.MapPosition} did not have a {nameof(T)}";
Same problems apply here.

2020-12-04 11:08 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/ComponentExt.cs
> +                        + $"at {entity.Transform.MapPosition} did not have a {nameof(T)}";
Fixed.

2020-12-04 11:08 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/ComponentExt.cs
> +                        + $"at {entity.Transform.MapPosition} did not have a {nameof(T)}";
Fixed.

2020-12-04 11:08 UTC, DrSmugleaf commented
Reviews addressed.

2020-12-04 11:52 UTC, PJB3005 approved these changes

2020-12-04 11:53 UTC, merged