Fixed handling keybinds.yml with no binds
space-wizards/RobustToolbox pull request #1433
Opened 2020-12-03 22:48 UTC by JohnGinnane

If the user's keybinds.yml file existed but does not contain any "binds" of "leaveEmpty" then "**KeyNotFoundException**" was being thrown in InputManager.cs

I have tested the following permutations:

1. No user keybinds.yml exists
2. User keybinds.yml exists and contains "binds" and "leaveEmpty"
3. User keybinds.yml exists and is a valid YML file but does not contain "binds" or "leaveEmpty" - This would cause exceptions for missing keys
4. User keybinds.yml exists but only contains "binds" - This originally caused exception on a missing "leaveEmpty" key
5. User keybinds.yml exists but only contains "leaveEmpty" - This originally caused exception on a missing "binds" key

2020-12-03 22:57 UTC, PJB3005 requested changes

2020-12-03 22:57 UTC, PJB3005 commented on Robust.Client/Input/InputManager.cs
> +            try
Using try catch on a `KeyNotFoundException` is *never* the correct choice. You should use a function like `TryReadDataField` instead of `ReadDataField` if you want to make it optional.

2020-12-03 23:01 UTC, JohnGinnane commented on Robust.Client/Input/InputManager.cs
> +            try
Right, will do that tomorrow, thanks

2020-12-04 10:07 UTC, PJB3005 approved these changes

2020-12-04 10:08 UTC, merged