Post shader will use real sprite bounding box
space-wizards/RobustToolbox pull request #1536
Opened 2021-02-05 23:42 UTC by Macoron

- Sprite can calculate its world-space bounding box
- Works with any scale, offset or rotation
- Works with multiple layers sprites. BB will be based on layers union size
- PostShader will use render texture based on screen-space size of sprite BB. Prior this PR render texture size was hardcoded.

Also fixed bug when sprite offset was scaled by its Scale
**Breaking:** offset will now move sprite in world-space cords, not rotated by 90 degrees like it was before. I believe this is more consistent way to do it.

2021-02-08 16:54 UTC, PJB3005 reviewed
Changing `SpriteComponent.Offset` to ignore world rotation is definitely incorrect. While the 90 degree bug should be fixed, it should still consider rotation. It's e.g. used for melee lunge animations and those should still rotate correctly when the world rotates.

Otherwise, looks good.

2021-02-08 17:36 UTC, Macoron commented
> While the 90 degree bug should be fixed, it should still consider rotation

Okay, I can ignore rotation bug and leave for another PR. Need to rewrite sprite BB function a bit. 
I also found out that after my PR scale also ignores world rotation. Looks like changing multiplication order broke something.

2021-02-23 16:56 UTC, Macoron commented
After #1551 it all just start working. I only added support for layers offset with new BB logic.
Remove all code related to -90 rotations hacks. Ready for review.

2021-02-23 21:46 UTC, PJB3005 requested changes
I'll just fix this real quick myself but I'll still leave the review comment so you see it.

2021-02-23 21:46 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                    highestTopRight.Y = topRight.Y;
You can use `Box2.Union` for this instead, much shorter.

2021-02-23 21:51 UTC, PJB3005 approved these changes

2021-02-23 21:54 UTC, merged