Add individual layer offset
space-wizards/RobustToolbox pull request #1583
Opened 2021-02-20 14:57 UTC by DrSmugleaf

2021-02-21 01:22 UTC, PJB3005 commented
Conflicts.

2021-02-21 11:26 UTC, PJB3005 requested changes

2021-02-21 11:26 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                    "Layer with index '{0}' does not exist, cannot set auto animated! Trace:\n{1}",
> cannot set auto animated

🤔

2021-02-21 11:26 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                Logger.ErrorS(LogCategory, "Layer with key '{0}' does not exist, cannot set auto animated! Trace:\n{1}",
Ditto

2021-02-21 15:50 UTC, DrSmugleaf commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                    "Layer with index '{0}' does not exist, cannot set auto animated! Trace:\n{1}",
Copy pasta strong. Fixed in https://github.com/space-wizards/RobustToolbox/pull/1583/commits/f6d393e448c353b072ef163be0a85cbd2ac62fbf

2021-02-21 15:50 UTC, DrSmugleaf commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +                Logger.ErrorS(LogCategory, "Layer with key '{0}' does not exist, cannot set auto animated! Trace:\n{1}",
Fixed in https://github.com/space-wizards/RobustToolbox/pull/1583/commits/f6d393e448c353b072ef163be0a85cbd2ac62fbf

2021-02-22 19:10 UTC, Acruid commented
There were a bunch of SpriteComponent changes yesterday, you need to verify this still works.

2021-02-22 20:08 UTC, DrSmugleaf commented
> There were a bunch of SpriteComponent changes yesterday, you need to verify this still works.

It does still work yes.
![image](https://user-images.githubusercontent.com/10968691/108763847-2268e580-7552-11eb-89dc-c3aa1bc6e1ce.png)

2021-02-23 11:55 UTC, merged