Unbuckling Closes Inventory UI
space-wizards/RobustToolbox pull request #1723
Opened 2021-04-25 09:52 UTC by MehimoNemo

What a fucking mudcrawl this was.
Fixes a line of code that caused parented objects to receive incorrect positions, causing, apparently, all sorts of icky stuff.
My brain is hot mush.

2021-04-25 10:30 UTC, ShadowCommander requested changes

2021-04-25 10:30 UTC, ShadowCommander commented on Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
> +            SetPosition(WorldPosition - newParent.WorldPosition);
Move this to just above `_parent = newParentEnt.Uid;` on line 556.

2021-04-25 10:30 UTC, ShadowCommander commented on Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
> +
Remove the unnecessary blank lines so we have clean formatting.

2021-04-25 19:23 UTC, MehimoNemo commented
Okay, I think that fixes it? Probably

2021-04-25 23:20 UTC, ShadowCommander approved these changes

2021-04-26 19:26 UTC, merged

2021-04-27 19:01 UTC, MehimoNemo commented
Not sure if this is all green, UI bug still occurring???

2021-04-27 19:16 UTC, ShadowCommander commented
> Not sure if this is all green, UI bug still occurring???

The bug will still be there until we update the RobustToolbox submodule in the space-station-14 repo, so don't worry. It's fixed, the server just hasn't been updated.