Make serialization work with backing fields automatically
space-wizards/RobustToolbox pull request #1727
Opened 2021-04-25 12:09 UTC by DrSmugleaf

This removes the need to write [field: DataField(...)] on get-only properties with a backing field, for which the only warning was a line in the serialization doc and an error after starting up the game.

2021-04-25 13:13 UTC, PaulRitter requested changes
i only have limited braincells due to exams but looks ok aside from the few notes i had.
i also saw you using generics and nullability and got a bit scared but as i said my mental capacity is nearing a 5 year low point so i just skipped that part and trusted you. pls dont disappoint

2021-04-25 13:13 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +                if (attr == null || abstractFieldInfo.IsBackingField())
this disables the [field: ]-variant. why?

2021-04-25 13:13 UTC, PaulRitter commented on Robust.Shared/Utility/TypeHelpers.cs
> +                    BindingFlags.NonPublic | BindingFlags.Instance);
i am 99% sure there is a property on the propertyinfo object for this

2021-04-25 13:13 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +        }
please yeet this out of the class and into the type, make it an extension or smth. exposing basefielddefinitions as a readonly list is cleaner than having this in the class imo

2021-04-25 13:15 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +                if (attr == null || abstractFieldInfo.IsBackingField())
That is to skip registering both the property and the backing field, though you are right if field: is used then it should not be skipped.

2021-04-25 13:16 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +        }
It is only for the rest but will do.

2021-04-25 13:16 UTC, PaulRitter commented on Robust.Shared/Utility/TypeHelpers.cs
> +                    BindingFlags.NonPublic | BindingFlags.Instance);
i was 99% wrong disregard

2021-04-25 13:18 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +                if (attr == null || abstractFieldInfo.IsBackingField())
On second thought this is already a test case. I changed it so looking up attributes on the property object also returns the ones on its backing field.

2021-04-27 11:59 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
> +        }
Done in https://github.com/space-wizards/RobustToolbox/pull/1727/commits/5aa025da6611792b0a83a7190f27c670f3a30538

2021-04-27 12:11 UTC, merged

2021-04-27 12:11 UTC, RemieRichards commented on Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
> +            // Set only property with backing field, property targeted
This comment, and the one below, refer to a "Set only" property.
Yet the two asserts are against a get only property.

So 1 of 3 things it at play.

1. The comments are wrong (i.e. "Set" vs "Get")
2. The code is wrong (Using wrong field, field defined wrong, etc.)
3. The comments are misleading and should be reworded (Halp brain melt)

2021-05-04 12:34 UTC, DrSmugleaf commented on Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
> +            // Set only property with backing field, property targeted
1 was correct, the comments were wrong. I have fixed up some of the other comments as well to make them consistent with the rest.
Fixed in https://github.com/space-wizards/RobustToolbox/commit/61113d24349c6e2a10b4b908e17c3e87d0a9a34c