MIDI improvements
space-wizards/RobustToolbox pull request #1756
Opened 2021-05-14 10:30 UTC by Zumorica

Just some minor midi improvements that I coded a while back and forgot to push.

2021-05-14 12:01 UTC, PJB3005 requested changes

2021-05-14 12:01 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                    stream.ReadExact(span);
This violates Fluidsynth's API which states that, on failure, the buffer should be unmodified. That's why that code did what it did.

2021-05-14 12:02 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                    stream.ReadExact(span);
Add a comment instead for clarity, I guess?

2021-05-14 12:10 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                    stream.ReadExact(span);
done, my bad

2021-05-15 15:57 UTC, PaulRitter approved these changes

2021-05-16 17:28 UTC, merged