ComponentHandleState event
space-wizards/RobustToolbox pull request #1778
Opened 2021-05-30 08:37 UTC by Zumorica

This is a directed component event. What this means is that this will only be dispatched directed to the component and its references. (I changed the enumerator method so it'll be dispatched to the component AFTER the references)
This allows us to handle component states from entity systems, therefore removing *even more* logic from component, and moving us closer to struct components, maybe.

The reason I haven't coded an event for getting the state is because that change wouldn't be backwards-compatible, we'd have to change EVERY SINGLE COMPONENT'S GET COMPSTATE to use the event instead.

Anyway, **do NOT merge without @Acruid and @PJB3005's explicit approvals.**

2021-06-08 23:59 UTC, Acruid commented
Is this a good idea? The component states are technically part of networking, they are not game logic. Component structs *can* have methods and properties on them to help access the data they contain.

2021-06-09 06:47 UTC, Zumorica commented
Mmmm, how would component structs handling states look? Would they use an interface or something?

2021-06-11 23:53 UTC, PJB3005 requested changes

2021-06-11 23:53 UTC, PJB3005 commented on Robust.Shared/GameObjects/Component.cs
> +        [Obsolete("Use the ComponentHandleState event instead.")]
Probably a good idea to curb your enthusiasm on this and *not* mark something like this obsolete yet.

2021-06-11 23:53 UTC, PJB3005 commented on Robust.Shared/GameObjects/EntityEventBus.Directed.cs
> +                }
`IComponentRegistration` makes no guarantee that the first element is the type itself. Filter to ignore the type in the inner loop and then do a final `yield return` at the end instead.

2021-06-12 10:35 UTC, Zumorica commented on Robust.Shared/GameObjects/Component.cs
> +        [Obsolete("Use the ComponentHandleState event instead.")]
My YEAST is SLOW.
Done.

2021-06-12 10:35 UTC, Zumorica commented on Robust.Shared/GameObjects/EntityEventBus.Directed.cs
> +                }
Done, that's indeed better

2021-06-12 13:50 UTC, PJB3005 approved these changes

2021-06-12 13:50 UTC, merged