Add joint support for CollisionWakeComponent
space-wizards/RobustToolbox pull request #1794
Opened 2021-05-31 12:03 UTC by metalgearsloth

If the component has any joints then it can't disable itself until all of them are removed.

2021-05-31 22:34 UTC, ShadowCommander approved these changes

2021-06-03 21:14 UTC, Zumorica requested changes

2021-06-03 21:14 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/CollisionWakeComponent.cs
> +        }
Logic in component detected.
HERESY! HERESY!

2021-06-03 21:14 UTC, Zumorica commented on Robust.Shared/Physics/JointMessages.cs
> +    }
Despite `Joint` having both bodies, these events don't and they should.
This will make it confusing when you're using the directed events and want to, for example, get the other body to perform logic on it. I'd rather not have to check each body in the joint to check it's not "mine"...

2021-06-03 21:14 UTC, Zumorica commented on Robust.Shared/Physics/Dynamics/PhysicsMap.cs
> +            _entityManager.EventBus.RaiseEvent(EventSource.Local, new JointAddedEvent(joint));
allocating three times? sad
Apply the review below and then reduce the allocations here to two events only, imo.
**(THIS REVIEW APPLIES TO THE JOINTREMOVEDEVENT BELOW AS WELL)**

2021-06-05 07:49 UTC, metalgearsloth commented on Robust.Shared/Physics/JointMessages.cs
> +    }
In that instance that means 2 events getting allocated if that's okay?

2021-06-05 08:02 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/CollisionWakeComponent.cs
> +        }
![image](https://user-images.githubusercontent.com/31366439/120884722-2c59b480-c628-11eb-85f5-2d62dd0d35cf.png)

2021-06-05 08:16 UTC, merged