Add SetAndDirtyIfChanged extension method
space-wizards/RobustToolbox pull request #1816
Opened 2021-06-08 16:43 UTC by DrSmugleaf

In the interest of replacing this
![](https://cdn.discordapp.com/attachments/560845886263918612/851800371466076160/rider64_kIUf3gPJ8Q.png)

With this 
![](https://cdn.discordapp.com/attachments/560845886263918612/851800380144091156/unknown.png)

It works like [RaiseAndSetIfChanged in ReactiveUI](https://www.reactiveui.net/api/reactiveui/ireactiveobjectextensions/554ad0a8) but it returns the component instead of the value being set for method chaining.

2021-06-08 23:23 UTC, PJB3005 requested changes

2021-06-08 23:23 UTC, PJB3005 commented on Robust.Shared/GameObjects/ComponentExt.cs
> +        public static TValue SetAndDirtyIfChanged<TComp, TValue>(
I don't think you need a generic for `TComp` here?

2021-06-10 12:24 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/ComponentExt.cs
> +        public static TValue SetAndDirtyIfChanged<TComp, TValue>(
Correct my bad, I'll fix it soon.

2021-06-10 12:33 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/ComponentExt.cs
> +        public static TValue SetAndDirtyIfChanged<TComp, TValue>(
Fixed in https://github.com/space-wizards/RobustToolbox/pull/1816/commits/30073ffd260826d17711514dad578c6d1a6fcf2a

2021-06-11 19:41 UTC, PaulRitter approved these changes
attaboy

i gotta ask one thing though: would this still work on struct components?

2021-06-11 23:44 UTC, PJB3005 commented
> i gotta ask one thing though: would this still work on struct components?

There are *way* more problems to solve with struct components than this minor one. The mere presence of the dirty flag is problematic for struct components. Not really worth considering at the moment.

2021-06-11 23:44 UTC, PJB3005 approved these changes

2021-06-11 23:44 UTC, merged