#1607 deprecate IEntityQuery
space-wizards/RobustToolbox pull request #1837
Opened 2021-06-19 13:36 UTC by GalacticChimp

Fixes #1607

2021-06-19 13:39 UTC, GalacticChimp commented on Robust.Shared/GameObjects/EntityManager.cs
> +        }
the standard GetEntities iterates over AllEntities List and uses indexes, to fetch entitities, I could not do that easily with Where() so I added this little code snippet to simplify things

2021-06-19 13:41 UTC, GalacticChimp commented on Robust.UnitTesting/Server/GameObjects/ThrowingEntityDeletion_Test.cs
> +            Assert.That(EntityManager.GetEntities(p => p.Prototype?.ID == prototypeName), Is.Empty);
turns out this is broken and the test hid it, the thrownInAdd etc entities do get spawned in, and they were spawned even without my code changes.

2021-06-19 13:42 UTC, metalgearsloth requested changes

2021-06-19 13:42 UTC, metalgearsloth commented on Robust.Shared/GameObjects/IEntityManager.cs
> +
This shouldn't exist IMO and should just use components.

This is because you need to iterate every entity which is atrociously expensive.

2021-06-19 13:42 UTC, metalgearsloth commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +
Delete? SpriteComp shouldn't have these in an ideal world.

2021-06-19 13:42 UTC, metalgearsloth commented on Robust.Shared/GameObjects/ComponentManager.cs
> +        }
This is silly when it has to iterate every component when it can just directly look at the dictionary instead. What code's even using this still? As ideally they'd probably just use a helper with generics IMO (also why aggressively inline it?)

2021-06-19 13:42 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Entity.cs
> +
Anyone needing this should just be calling ComponentManager directly IMO.

2021-06-19 13:42 UTC, metalgearsloth commented on Robust.Shared/GameObjects/EntityManager.cs
> +        }
This is also needlessly expensive and should be deleted.

2021-06-19 13:44 UTC, metalgearsloth commented
I also should've mentioned anything that *really* needs EntityManager.AllEntities should be managing it itself because iterating it is hella expensive.

2021-06-19 14:13 UTC, GalacticChimp commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +
this is in a SpriteComp's private class: private class DummyIconEntity : IEntity 
where most of the IEntity stuff isn't actually used

2021-06-20 13:30 UTC, GalacticChimp commented on Robust.Shared/GameObjects/ComponentManager.cs
> +        }
decided to go with returning IEntities instead of Components, because we want the Entities which have all inputted components, not the components themselves (see FindEntitiesWithComponents and DeleteEntitiesWithComponent) for use cases

2021-06-20 15:59 UTC, metalgearsloth requested changes

2021-06-20 15:59 UTC, metalgearsloth commented on Robust.Shared/GameObjects/ComponentManager.cs
> +            }
Try to avoid just making tab or whitespace changes coz it can bloat reviews, this was done in a few spots.

2021-06-20 15:59 UTC, metalgearsloth commented on Robust.Shared/GameObjects/ComponentManager.cs
> +        }
Won't this allocate out the ass because of multiple ToList calls + a HashSet call? Also this is just duplicating what EntityQuery already does but in a less-robust way (e.g. doesn't check for deleted components).

IMO just delete.

2021-06-20 15:59 UTC, metalgearsloth commented on Robust.Shared/GameObjects/EntityManager.cs
> +            Parallel.ForEach(
IMO just have the regular GetEntities. I'm suss of having it parallel because there's a bunch of non-thread-safe APIs someone may inadvertantly use (e.g. most of the public physics methods).

2021-06-20 16:40 UTC, GalacticChimp commented on Robust.Shared/GameObjects/EntityManager.cs
> +            Parallel.ForEach(
this one isn't used actually, forgot to delete it

2021-06-21 05:06 UTC, metalgearsloth approved these changes

2021-06-21 07:09 UTC, Zumorica commented on Robust.Shared/GameObjects/ComponentManager.cs
> +            ComponentRemoved?.Invoke(this, new RemovedComponentEventArgs(component, uid));
You forgot to unintend these lines, it's inconsistent right now.

2021-06-27 03:36 UTC, metalgearsloth approved these changes

2021-06-27 03:40 UTC, merged