Replace most VBox/HBoxContainers with BoxContainers
space-wizards/RobustToolbox pull request #1867
Opened 2021-07-16 03:09 UTC by Visne

2021-07-17 16:01 UTC, PJB3005 requested changes

2021-07-17 16:01 UTC, PJB3005 commented on Robust.Client/Console/Commands/Debug.cs
> +            	Orientation = LayoutOrientation.Vertical
Your IDE is misconfigured and inserting tabs here instead of spaces. Please fix it.

This goes for many other lines in the PR diff too.

2021-07-18 15:42 UTC, Visne commented on Robust.Client/Console/Commands/Debug.cs
> +            	Orientation = LayoutOrientation.Vertical
Fixed. I replaced with `\t` instead of four spaces.

2021-07-18 16:28 UTC, Visne commented
I'm not sure what to do with that failing testt, apart from that this can be reviewed again.

2021-07-18 16:42 UTC, PJB3005 commented
Failing test isn't your fault.

2021-07-18 16:42 UTC, merged