Add support for struct directed events.
space-wizards/RobustToolbox pull request #1931
Opened 2021-08-06 08:38 UTC by Zumorica

Also turns transform events into readonly structs.
As a gotcha, as struct events aren't passed by reference, they can only be informative events, and they can't be used to communicate between handlers or with the event raiser.

2021-08-06 11:01 UTC, PaulRitter requested changes
I'm gonna be honest i dont really like the `object args` signature.

What speaks against having an `IEntityEventArgs` interface that all args have to implement, would work with classes as well as structs? Could then use that interface in the generic methods, as well as the non-generic ones.

This might just be me, but i dont like when signatures are being typed as object since you can pass virtually anything (as far as c# and the linter knows).

2021-08-06 11:01 UTC, PaulRitter commented on Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
> +    public readonly struct MoveEvent
This used to be a handled Event. Intended?

2021-08-06 11:02 UTC, PaulRitter commented
Besides that, i obviously think struct args rock. Good job :)

2021-08-06 11:02 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
> +    public readonly struct MoveEvent
Yes, intended. we discussed it in discord and concluded that it was accidentally made handled.

2021-08-06 11:05 UTC, Zumorica commented
> I'm gonna be honest i dont really like the `object args` signature.

Same signature as in the broadcast eventbus, it's fine.

> What speaks against having an `IEntityEventArgs` interface that all args have to implement, would work with classes as well as structs? Could then use that interface in the generic methods, as well as the non-generic ones.

Interfaces, and boxing are really slow. We don't need an interface for this, at all.

> This might just be me, but i dont like when signatures are being typed as object since you can pass virtually anything (as far as c# and the linter knows).

It's always been this way with broadcast events and we've never had a problem

2021-08-06 11:07 UTC, metalgearsloth commented
I said this on discord but putting here for brevity: would like a benchmark of the physics MoveEvents with this change sooooooooo tumbler when

2021-08-06 11:11 UTC, PaulRitter commented
> Interfaces, and boxing are really slow. We don't need an interface for this, at all.

While i dont think "we've always done it like this" is a proper argument, i think this is. Consider it sorted

2021-08-06 11:11 UTC, PaulRitter approved these changes

2021-08-15 16:13 UTC, PJB3005 requested changes

2021-08-15 16:13 UTC, PJB3005 commented on Robust.Shared/GameObjects/EntityEventBus.Directed.cs
> -            where TEvent : EntityEventArgs
You *only* changed this generic bound, which measn that the `_eventTables.Dispatch` call, which is not generic, will do a boxing allocation for your struct. This makes struct directed events rather useless with this implementation since at best their performance is just worse than ref types.

2021-08-16 09:37 UTC, Zumorica commented on Robust.Shared/GameObjects/EntityEventBus.Directed.cs
> -            where TEvent : EntityEventArgs
I think I addressed this now. Would be nice if you could give this another review

2021-08-17 10:35 UTC, Zumorica commented
Requesting another review from @PJB3005 as I increased the scope of this PR significantly

2021-08-20 13:35 UTC, PJB3005 approved these changes
I am now implicit in the impending `Unsafe` disaster this PR has become so...

2021-08-21 09:36 UTC, Zumorica commented
if this ever actually becomes an issue, feel free to throw rotten tomatoes at me

2021-08-21 09:37 UTC, merged