Joints refactor
space-wizards/RobustToolbox pull request #1954
Opened 2021-08-18 14:53 UTC by metalgearsloth

Dusting off this PR. Will need updating after #1953 so do that first.

* Joints moved to their own component reducing physics state + code clutter
* Joints now have their own state classes rather than serializing the whole thing over the network
* PhysicsMap no longer stores joints so JointComponent + JointSystem can work with prediction on its own.

There's still some mess internally but I don't really know a way to make it "clean" so it is what it is for now I guess.

2021-09-27 05:32 UTC, metalgearsloth commented
Good for review now I guess.

2021-10-03 10:14 UTC, PaulRitter requested changes
nice work proud of ya

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Client/Debugging/DebugPhysicsSystem.cs
> +            var color = new Color(0.5f, 0.8f, 0.8f);
could just make this static readonly, no?

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Client/Debugging/DebugPhysicsSystem.cs
> +            }
why arent we drawing other types of joints?

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
> +            joint.WarmStarting = configManager.GetCVar(CVars.WarmStarting);
these wont get updated when the cvar gets updated unless i've missed something. do we care? i'd say yes

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/Dynamics/Joints/FrictionJoint.cs
> +            return base.Equals(other);
afaict you dont compare force & torque anymore, as well as the anchor points. is this intentional, and why?

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
> +            return base.Equals(other);
afaict this only compares both uids now. why not compare the rest of the fields?

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/Dynamics/Joints/RevoluteJoint.cs
> +    public class RevoluteJoint : Joint
how come no iequatable on this?

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/Dynamics/SharedPhysicsMapComponent.cs
> +        /// Temporary joint storage during solving
cant comment on non-diff entries so: remove `_entityManager` in L39 of this file, its unused now

2021-10-03 10:14 UTC, PaulRitter commented on Robust.Shared/Physics/JointComponent.cs
> +    public sealed class JointComponent : Component
would p be good to restrict access to jointsystem with a friend attribute

2021-10-03 11:32 UTC, metalgearsloth commented on Robust.Client/Debugging/DebugPhysicsSystem.cs
> +            }
None of the other types I've actually implemented have drawing stuff on box2d https://github.com/erincatto/box2d/blob/95f74a46c077825478f989df6a81003ca538c2c2/src/dynamics/b2_joint.cpp

Just distance, mouse, and pulley. In the future I'll think of a good way to visualize it.

2021-10-03 12:04 UTC, metalgearsloth commented on Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
> +            joint.WarmStarting = configManager.GetCVar(CVars.WarmStarting);
SharedJointSystem subscribes and updates all joints; realistically these would only ever be touched in debugging (and even then I've never touched it).

2021-10-03 12:13 UTC, metalgearsloth commented on Robust.Shared/Physics/Dynamics/Joints/RevoluteJoint.cs
> +    public class RevoluteJoint : Joint
Simple ![image](https://user-images.githubusercontent.com/31366439/135753129-0eb2e828-5f7f-4603-ae89-3920af0f73c2.png)

2021-10-04 04:32 UTC, metalgearsloth commented on Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
> +            joint.WarmStarting = configManager.GetCVar(CVars.WarmStarting);
(Realistically LinearSlop needs to be a constant as well but baby steps)

2021-10-04 04:34 UTC, merged