EntityLookup flags for PVS optimisations
space-wizards/RobustToolbox pull request #1983
Opened 2021-08-26 03:15 UTC by metalgearsloth

Given anchored entities are handled by chunk for PVS we no longer need to store them in EntityLookup's DynamicTrees leading to a nice memory and performance savings.

I also added approximate to the flag as it was a bit weird to have a bool and then flags for a bunch of other stuff. Eventually I'll add grids to it too (given most of the time callers don't want it) and (potentially) containermanagers.

Content PR: https://github.com/space-wizards/space-station-14/pull/4531

2021-08-28 12:29 UTC, Zumorica requested changes

2021-08-28 12:29 UTC, Zumorica commented on Robust.Shared/GameObjects/Systems/EntityLookup.cs
> +                }
Needs to check lookup flags for the anchored flag

2021-08-28 12:29 UTC, Zumorica commented on Robust.Shared/GameObjects/Systems/EntityLookup.cs
> +                list.Add(ent);
Probably needs to check the flags for the anchored flag

2021-08-28 12:29 UTC, Zumorica commented on Robust.Shared/GameObjects/Systems/EntityLookup.cs
> +            }
Probably needs to check the flags for the anchored flag

2021-08-29 03:55 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/EntityLookup.cs
> +                }
I double-checked and GetAnchored already checks for the flag and will yield break. I mainly added it as a helper for entitylookup internally to avoid duplicating it (especially when more methods get added in future).

2021-08-29 04:03 UTC, merged