Change serialization reading to only do type checks once per type
space-wizards/RobustToolbox pull request #2018
Opened 2021-09-10 13:20 UTC by DrSmugleaf

TryReadRaw is no longer necessary.
Also removes the non generic DeserializationResult.Value method and changes DeserializedArray to use an array instead of an enumerable.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

```
|                       Method |        Mean |     Error |    StdDev |      Median | Gen 0 | Allocated |
|----------------------------- |------------:|----------:|----------:|------------:|-------:|----------:|
|                   OldReadString |    230.5 ns |   4.09 ns |   3.83 ns |    230.1 ns | 0.0210 |      88 B |
|                   NewReadString |   111.9 ns |   3.07 ns |   8.86 ns | - | 0.0057 |      24 B |
|                  OldReadInteger |    261.4 ns |   5.22 ns |   9.14 ns |    261.5 ns | 0.0324 |     136 B |
|                  NewReadInteger |   124.8 ns |   2.51 ns |   5.83 ns | - |0.0172  |      72 B |
| OldReadDataDefinitionWithString |    747.4 ns |  14.68 ns |  15.71 ns |    753.8 ns | 0.0648 |     272 B |
| NewReadDataDefinitionWithString |   351.4 ns |   6.38 ns |   7.09 ns | - | 0.0343  |     144 B |
|       OldReadSeedDataDefinition | 12,835.2 ns | 256.14 ns | 383.37 ns | 12,755.0 ns | 1.3275  |    5569 B |
|       NewReadSeedDataDefinition | 8,039.0 ns | 118.47 ns | 105.02 ns | - | 1.0147  |    4249 B |

Arrays:

|                       Method |       Mean |    Error |    StdDev |     Median |  Gen 0 | Allocated |
|----------------------------- |-----------:|---------:|----------:|-----------:|-------:|----------:|
|        OldReadEmptyString |   596.6 ns |  11.61 ns |  10.29 ns | - | 0.1278 |     536 B |
|              NewReadEmptyString |   111.8 ns |  2.24 ns |   2.49 ns |   111.6 ns | 0.0191 |      80 B |
|          OldReadOneString |   894.5 ns |  17.73 ns |  38.92 ns | - | 0.1640 |     688 B |
|                NewReadOneString |   149.5 ns |  2.28 ns |   2.02 ns |   149.7 ns | 0.0286 |     120 B |
|         OldReadTenStrings | 3,476.6 ns |  67.79 ns | 107.53 ns | - | 0.4272 |    1792 B |
|               NewReadTenStrings |   495.4 ns |  9.87 ns |  10.13 ns |   495.7 ns | 0.1144 |     480 B |
|           OldReadEmptyInt |   603.1 ns |  12.03 ns |  20.43 ns | - | 0.1278 |     536 B |
|                 NewReadEmptyInt |   118.4 ns |  2.40 ns |   2.85 ns |   118.7 ns | 0.0191 |      80 B |
|             OldReadOneInt |   893.6 ns |  16.37 ns |  13.67 ns | - | 0.1698 |     712 B |
|                   NewReadOneInt |   175.1 ns |  3.53 ns |   3.13 ns |   174.3 ns | 0.0343 |     144 B |
|            OldReadTenInts | 3,727.3 ns |  73.25 ns |  64.94 ns | - | 0.4730 |    1992 B |
|                  NewReadTenInts |   670.8 ns | 13.63 ns |  38.67 ns |   667.2 ns | 0.1621 |     680 B |
| OldReadEmptyStringDataDef |   587.7 ns |  14.34 ns |  40.44 ns | - | 0.1278 |     536 B |
|       NewReadEmptyStringDataDef |   126.1 ns |  2.12 ns |   1.99 ns |   125.9 ns | 0.0191 |      80 B |
|   OldReadOneStringDataDef | 1,511.3 ns |  30.22 ns |  87.19 ns | - | 0.2079 |     872 B |
|         NewReadOneStringDataDef |   488.5 ns |  9.70 ns |  10.78 ns |   484.4 ns | 0.0572 |     240 B |
|  OldReadTenStringDataDefs | 8,698.7 ns | 165.21 ns | 247.28 ns | - | 0.8545 |    3632 B |
|        NewReadTenStringDataDefs | 3,568.2 ns | 70.99 ns |  84.51 ns | 3,579.7 ns | 0.4005 |    1680 B |
| NewReadEmptySealedStringDataDef |   126.2 ns |  2.31 ns |   3.08 ns |   125.8 ns | 0.0191 |      80 B |
|   NewReadOneSealedStringDataDef |   415.2 ns |  8.30 ns |   9.56 ns |   412.5 ns | 0.0572 |     240 B |
|  NewReadTenSealedStringDataDefs | 3,361.8 ns | 66.23 ns | 135.29 ns | 3,310.3 ns | 0.4005 |    1680 B |

2021-09-10 15:48 UTC, PaulRitter requested changes
note: partial review

seems gucci, just got a few almond activations

2021-09-10 15:48 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/Result/DeserializationResult.cs
> +        public abstract T? Value { get; }
you putting nullables (explanation below image, meme was too big, pls scroll)
![image](https://user-images.githubusercontent.com/16618384/132878902-b9d5de83-ef11-4dd3-a66b-5c40772bee05.png)

this should in every case of the good lord be `T`, not `T?`. If i do a `DeserializationResult<int>`, i do not want value to be `int?`, i want it to be `int`. Now if i do `DeserializationResult<int?>` it will be `int?`.
```suggestion
        public abstract T Value { get; }
```

2021-09-10 15:48 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/Result/DeserializedArray.cs
> +            return new DeserializedArray(values, results);
chief converting `results` into an array causes loop 2 to overwrite the values of loop 1. no clue about the implications of this, but should probably be noted

2021-09-10 15:48 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/Result/DeserializedValue.cs
> +        public override T? Value { get; }
this mf. see my explanation on the prior thingy

2021-09-11 15:35 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/Result/DeserializedValue.cs
> +        public override T? Value { get; }
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2018/commits/0d2ec32d0fb6ee2ba845024940728ff26f0804ad

2021-09-11 15:35 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/Result/DeserializationResult.cs
> +        public abstract T? Value { get; }
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2018/commits/0d2ec32d0fb6ee2ba845024940728ff26f0804ad

2021-09-12 10:24 UTC, metalgearsloth approved these changes
![image](https://user-images.githubusercontent.com/31366439/132984029-d1065ade-e38a-4c4f-a72d-a7e31d729aea.png)

2021-09-12 19:18 UTC, PaulRitter approved these changes

2021-09-12 19:18 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.Reading.cs
> -                return new DeserializedValue<T[]>(null);
ideally we would still use T here, since if we serialize a non-nullable type we'd want to return anything but null, so it should rather throw.

regardless, this should be fine for now

2021-09-12 19:21 UTC, PaulRitter requested changes

2021-09-12 19:21 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.Instantiation.cs
> +                var generator = method.GetRobustGen();
btw robustgen was suppose to be a debug thingy for reading out the emitted il. it doesnt really make sense to use this in release, please just use the regular generator here

2021-09-13 11:36 UTC, DrSmugleaf commented on Robust.Shared/Serialization/Manager/SerializationManager.Instantiation.cs
> +                var generator = method.GetRobustGen();
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2018/commits/c3b00225d55f2069e4220e1620ddec9be3b0d8d2

2021-09-13 16:14 UTC, PaulRitter approved these changes

2021-09-13 16:14 UTC, merged