Makes BoundUserInterfaces partially ECS.
space-wizards/RobustToolbox pull request #2033
Opened 2021-09-13 10:51 UTC by Zumorica

- All received BoundUserInterfaceMessages will be raised as directed events.
- Base BoundUserInterfaceMessage now has fields for the entity UID, UI key and relevant player session.
    - Please note that these are *only* set before raising the directed event, for ECS purposes.
- Made UserInterfaceSystem public, added a bunch of *proxy* methods to it.
    - These proxy methods call into the actual BoundUserInterface methods. In the future the logic will be moved into the systems though.
    - This means you can start using these methods to ECS your bound user interfaces!
- Added BoundUserInterfaceClosedEvent for when a bound user interface is closed. Yay, ECS!

I think this is done now. Please review and give me feedback on these changes!
For an example of the changes in this PR being used, refer to this content PR: <link here>

2021-09-13 22:53 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    public class BoundUserInterfaceClosedEvent : EntityEventArgs
How much to rename it to something like BUIClosedEvent instead

2021-09-14 00:22 UTC, mirrorcult commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    }
why not have this inherit BoundUserInterfaceMessage, has all the same fields

2021-09-14 07:58 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    public class BoundUserInterfaceClosedEvent : EntityEventArgs
BUI sounds bad tho :pensive:

2021-09-14 10:22 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    public class BoundUserInterfaceClosedEvent : EntityEventArgs
I'll sell you BoundUIClosedEvent for 3.50

2021-09-15 14:07 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    public class BoundUserInterfaceClosedEvent : EntityEventArgs
fair, that doesnt' sound bad

2021-09-15 14:15 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    }
done

2021-09-16 09:37 UTC, PaulRitter requested changes

2021-09-16 09:37 UTC, PaulRitter commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    }
shouldn't this still have a ctor and fill all of the properties inherited from `BoundUserInterfaceMessage`?

2021-09-16 09:37 UTC, PaulRitter commented on Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs
> +            owner.EntityManager.EventBus.RaiseLocalEvent(owner.Uid, new BoundUIClosedEvent());
see other comment, this should be given the appropriate values via ctor

2021-09-16 14:05 UTC, Zumorica commented on Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
> +    }
when you address reviews so fast you forget something this vital

2021-09-17 21:54 UTC, PaulRitter approved these changes

2021-09-18 08:41 UTC, merged