Adds everything else OpenDream needs to the sandbox
space-wizards/RobustToolbox pull request #2060
Opened 2021-09-24 20:20 UTC by ike709

https://github.com/wixoaGit/OpenDream/issues/374

2021-09-24 20:21 UTC, ike709 commented on Robust.Shared/ContentPack/Sandbox.yml
> +- OpenDreamShared
This isn't ideal in the long run but PJB caved so... /shrug

2021-09-24 20:22 UTC, ike709 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    JsonIgnoreAttribute: { All: True }
This is actually just for the ctor, should I change it or does it not really matter?

2021-09-24 20:22 UTC, ike709 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    CancelEventArgs: { All: True }
This is actually just for the setter, should I change it or does it not really matter?

2021-09-24 20:28 UTC, PJB3005 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    JsonIgnoreAttribute: { All: True }
doesn't really matter, though you won't be able to actually make use of these attributes ever anyways as it's reflection-heavy deserialization we can't allow.

2021-09-26 00:44 UTC, ike709 commented
oops I goofed the whitespace

2021-09-26 00:57 UTC, ike709 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    NumberStyles: { All: True } # Enum
```suggestion
    NumberStyles: { } # Enum
```

2021-09-26 01:56 UTC, ike709 commented
OpenDream now has everything whitelisted that it needs whitelisted.

2021-09-29 19:38 UTC, PaulRitter approved these changes

2021-10-05 12:53 UTC, PJB3005 requested changes

2021-10-05 12:53 UTC, PJB3005 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    Path: { All: True }
Sorry for looking at this so late but `Path` can be used to probe file system layout (Short path expansion in `Path.GetFullPath()`) and OS setup (is the user on Windows or Linux?).

![image](https://user-images.githubusercontent.com/8107459/136026358-36608bcf-5b42-424d-a59f-dc0df80b6597.png)

This API should not be exposed to content.

2021-10-05 18:05 UTC, ike709 commented on Robust.Shared/ContentPack/Sandbox.yml
> +    Path: { All: True }
```suggestion
```
Path is no longer needed as I moved the entirety of the compiler out of shared.

2021-10-06 20:50 UTC, PJB3005 approved these changes

2021-10-06 20:50 UTC, merged