Opt out of shadow casting for sufficiently small lights
space-wizards/RobustToolbox pull request #2085
Opened 2021-10-02 06:33 UTC by mirrorcult

@PJB3005 

not a CVar since setting it sufficiently high essentially disables lighting. impetus of this PR is to make sure that https://github.com/space-wizards/space-station-14/pull/4709 doesn't lag too much and we can have a lot of pretty lights. every light added in that PR is <= 2.0 radius, and really small lights -essentially- don't cast lights at all so it's a waste to do the occlusion depth calcs for this. Maybe this doesn't optimize that much, I can't really tell (seems to save a bit of FPS on my machine, 3-5 or so, might be better on igpu)

Things we might want to do
- Increase the distance?
- Make sure walllights/emergency lights in SS14 have AlwaysCastShadows set
- Maybe opt out of shadow casting for -every- light unless it explicitly opts in? idk about this one it'd probably be annoying

2021-10-02 06:36 UTC, mirrorcult commented
also might want to increase max lights but 128 seems okay especially for saltern

2021-10-02 06:37 UTC, mirrorcult commented
an example of the difference visually (literally the only place on saltern where I could find a visual difference)

no shadow casting for this small light:
![image](https://user-images.githubusercontent.com/19853115/135706381-3ee0963a-d61d-4211-b9dd-e9009aec3cba.png)

yes shadow casting:
![image](https://user-images.githubusercontent.com/19853115/135706388-6e4e9ceb-99aa-4ce4-9225-dde566d62120.png)

2021-10-02 06:49 UTC, mirrorcult commented
nvm this makes them visible through walls lol

2021-10-02 06:53 UTC, mirrorcult commented
actually this is salvageable i just made the minimum radius smaller

2021-10-02 13:16 UTC, PJB3005 commented
1.5 feels a little high to me because that feels like it could still show through walls in some edge cases. Conservatively I'd say it should be no more than 1 (because that's how thick walls are).

2021-10-02 13:19 UTC, PJB3005 commented
My understanding is that stuff like the computer lights are too large to fit under 1 radius, but they can't clip because they're always fixed in the center of the tile, right? Maybe make it a flag on the light itself to disable shadow casting?

2021-10-03 20:34 UTC, mirrorcult commented
opted to remove the culling-by-radius thing and i'll just make every light opt in to not cast shadows, will make a content PR for this later

2021-10-04 13:41 UTC, PaulRitter commented
> 1.5 feels a little high to me because that feels like it could still show through walls in some edge cases. Conservatively I'd say it should be no more than 1 (because that's how thick walls are).

terrible idea imo, since we might have occluders that are < 1 tile in all directions

suppose this is a tricky one

2021-10-09 13:12 UTC, PJB3005 commented
> terrible idea imo, since we might have occluders that are < 1 tile in all directions

Cross that bridge when we actually *have* such occluders, because this is completely non-trivial to actually add due to how the occlusion system actually works.

2021-10-09 13:17 UTC, PJB3005 requested changes

2021-10-09 13:17 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +                        if (!light.CastShadows) continue;
I just realized that because you're only doing a continue here, you're still taking up a slot in the shadow atlas and still trying to *draw* a shadow aswell (just you end up drawing no shadow) so this doesn't perform as well as it could either.

2021-10-09 16:15 UTC, PJB3005 approved these changes

2021-10-09 16:21 UTC, merged