Added set English language checkbox
space-wizards/RobustToolbox pull request #2136
Opened 2021-10-16 06:51 UTC by lvvova1

Engine part

For this issue
https://github.com/space-wizards/space-station-14/issues/4712
For this PR
https://github.com/space-wizards/space-station-14/pull/4898

2021-10-16 06:53 UTC, mirrorcult commented
@PJB3005

2021-10-22 07:18 UTC, PJB3005 requested changes

2021-10-22 07:18 UTC, PJB3005 commented on Robust.Shared/CVars.cs
> +            CVarDef.Create("display.use_english_hotkeys", false, CVar.CLIENTONLY | CVar.ARCHIVE);
This should be referred to as "use US QWERTY hotkeys" everywhere, not "English"

2021-10-22 07:18 UTC, PJB3005 commented on Robust.Client/Input/InputManager.cs
> +
This event should be fired automatically when the input mode/CVar changes, not be raised manually by content.

2021-10-22 07:18 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Keys.cs
> +            [Dependency] private readonly IConfigurationManager _cfgg = default!;
You can use `_clyde._cfg` instead so you don't have to cache it here.

2021-10-22 07:18 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Keys.cs
> +                    string name = "";
```suggestion
                    string name;
```

Don't initialize this variable to anything since you're assigning it in both code paths.

2021-10-22 07:19 UTC, PJB3005 commented on Robust.Client/Input/IInputManager.cs
> +        event Action OnKeyUpdated;
One last thing: Change this to something like `OnInputModeChanged`

2021-11-04 21:47 UTC, lvvova1 commented on Robust.Client/Input/IInputManager.cs
> +        event Action OnKeyUpdated;
Done

2021-11-04 21:47 UTC, lvvova1 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Keys.cs
> +                    string name = "";
Done

2021-11-04 21:47 UTC, lvvova1 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Keys.cs
> +            [Dependency] private readonly IConfigurationManager _cfgg = default!;
Done

2021-11-04 21:48 UTC, lvvova1 commented on Robust.Shared/CVars.cs
> +            CVarDef.Create("display.use_english_hotkeys", false, CVar.CLIENTONLY | CVar.ARCHIVE);
I'm made DisplayUSQWERTYHotkeys name

2021-11-05 00:36 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.cs
> +                    _cfg.UnsubValueChanged(CVars.DisplayUSQWERTYHotkeys, x => InitKeyMap());
This doesn't actually work, the lambda you are unsubscribing will be different from the one you're subscribing with. You should make a separate function that receives the event if you want to unsubscribe it.

2021-11-05 20:05 UTC, PJB3005 commented on Robust.Client/Input/InputManager.cs
> +        private void InputModeChanged(bool onValueChanged) => OnInputModeChanged?.Invoke();
This even should be invoked by Clyde instead.

2021-11-05 21:25 UTC, lvvova1 commented on Robust.Client/Input/InputManager.cs
> +        private void InputModeChanged(bool onValueChanged) => OnInputModeChanged?.Invoke();
You mean put 
`_cfg.OnValueChanged(CVars.DisplayUSQWERTYHotkeys,_inputManager.InputModeChanged);`
Into `Clyde.InitializePreWindowing`?

2021-11-07 00:33 UTC, PJB3005 commented on Robust.Client/Input/InputManager.cs
> +        private void InputModeChanged(bool onValueChanged) => OnInputModeChanged?.Invoke();
Clyde should be invoking the event on input manager from whatever code hooks the `DisplayUSQWERTYHotkeys` yes. You should not be registering a second `OnValueChanged` handler for it.

2021-11-07 21:28 UTC, lvvova1 commented
So, I got problem, when I moved `OnValueChanged` into "Clyde" 

Because I had 2 `OnValueChanged` they called in wrong order, it's worked like:
> "first called "reDraw letters" after that reInit letters whos will used for reDrawing"

And I move `OnValueChanged` into Glfw where i'm reinit all letters by `OnValueChanged` also, here it's works as expected.

2021-11-10 00:01 UTC, PJB3005 commented
Yep, that is exactly why you should only have a single `OnValueChanged`.

2021-11-10 00:01 UTC, PJB3005 approved these changes

2021-11-10 00:12 UTC, merged