Make autogenerated XAML UI fields access level settable
space-wizards/RobustToolbox pull request #2148
Opened 2021-10-22 02:01 UTC by Visne

Access level of XAML UI controls can now be set. If no level is set, the old behaviour is used (`protected` by default, or `private` for `sealed`).

2021-10-22 02:04 UTC, mirrorcult approved these changes

2021-10-22 12:21 UTC, PaulRitter commented
I'm sorry, but no. Encapsulation of nested XAML controls has nothing to do with OOP bad, its important for custom controls. you dont want anyone dicking around in your nested controls.

If anything this should be implemented as a field on controls in xaml, indicating if their field should be public.

2021-10-22 16:09 UTC, Visne commented
Access level can now be set manually, ready for rereview.

2021-10-22 18:40 UTC, PJB3005 requested changes

2021-10-22 18:40 UTC, PJB3005 commented on Robust.Client/UserInterface/Control.cs
> +        public AccessLevel? Access { get; set; }
```suggestion
        public AccessLevel? Access { set {  } }
```

So that no field gets allocated and this does nothing except trick Rider.

2021-10-22 18:40 UTC, PJB3005 commented on Robust.Client.NameGenerator/XamlUiPartialClassGenerator.cs
> +                        accessText != null ? accessText.Text : "Default");
```suggestion
                        accessText?.Text ?? "Default");
```

2021-10-23 16:28 UTC, Visne commented
Can be reviewed again.

2021-10-24 00:08 UTC, PJB3005 approved these changes

2021-10-24 11:12 UTC, ShadowCommander approved these changes

2021-10-24 12:50 UTC, PaulRitter requested changes
otherwise lgtm

2021-10-24 12:50 UTC, PaulRitter commented on Robust.Client/UserInterface/Control.cs
> +    }
missing:
- internal
- protected internal
- private protected

2021-10-24 12:50 UTC, PaulRitter commented on Robust.Client.NameGenerator/XamlUiPartialClassGenerator.cs
> +                return $"        {access} global::{type} {name} => this.FindControl<global::{type}>(\"{name}\");";
two things:
- when the class is sealed, `protected` should be converted to `private`, `protected internal` should be converted to `internal` and `private protected` should be converted to `private`.
- please parse the string into the enum to validate the value & throw an exception if it fails. just throw a descriptive exception in this function, the calling function will catch it and log it as an msbuild error.

2021-10-24 20:49 UTC, ShadowCommander approved these changes

2021-10-24 21:20 UTC, PaulRitter approved these changes
lgtm

2021-10-24 21:20 UTC, merged