Make client console check perms locally
space-wizards/RobustToolbox pull request #2188
Opened 2021-11-01 14:13 UTC by metalgearsloth

I nuked my admin perms locally and tested chat works and togglefov / togglelight don't work.

Content PR is https://github.com/space-wizards/space-station-14/pull/5124

2021-11-02 16:58 UTC, PJB3005 requested changes
Checking this means that you can't run any client-side commands (because those aren't understood by the con group controller)

2021-11-03 00:30 UTC, metalgearsloth commented
Do you mean engine-wise without SS14? I checked with and without admin perms and it *seemed* to work as intended (the content test failure is because it doesn't have "disconnect" allowed which has a PR up).

2021-11-03 23:36 UTC, PJB3005 commented
I ran the SS14 client without connecting to a server and I couldn't use any command.

2021-11-03 23:38 UTC, moonheart08 commented
> I ran the SS14 client without connecting to a server and I couldn't use any command.

It wouldn't be a very effective fix if you could simply `togglelight` before connecting

2021-11-03 23:41 UTC, PJB3005 commented
I should, however, be capable of running `devwindow` offline to test UI stuff.

If running `togglelight` is a problem then we can have content reset it on connect. Or the engine.

2021-11-03 23:43 UTC, metalgearsloth commented
Content needs a way to reset commands anyway because people leave stuff on after sandbox rounds are over so if the client isn't InGame we should probably just skip the check?

2021-11-24 01:37 UTC, metalgearsloth commented
gucci 100 for check

2021-11-28 13:59 UTC, PJB3005 commented on Robust.Client/Console/ClientConsoleHost.cs
> +                if (!_conGroup.CanCommand(commandName) && playerManager.LocalPlayer?.Session.Status > SessionStatus.Connecting)
`CanCommand()` defaults to returning false so this will break console commands on repos that doesn't implement `IClientConGroupImplementation` still.

2021-11-29 11:06 UTC, PaulRitter commented on Robust.Client/Console/ClientConsoleHost.cs
> +                if (!_conGroup.CanCommand(commandName) && playerManager.LocalPlayer?.Session.Status > SessionStatus.Connecting)
wouldnt true be a more sensible default?

2021-11-29 12:11 UTC, PJB3005 commented on Robust.Client/Console/ClientConsoleHost.cs
> +                if (!_conGroup.CanCommand(commandName) && playerManager.LocalPlayer?.Session.Status > SessionStatus.Connecting)
Probably, yes.

2021-12-01 09:00 UTC, PaulRitter approved these changes

2021-12-12 23:43 UTC, merged