SharedPhysicsSystem: convert parents' angular velocity to linear when leaving
space-wizards/RobustToolbox pull request #2208
Opened 2021-11-08 11:07 UTC by Efruit

As with last time, thanks to @ElectroJr and @Tomeno for whacking some math in to me.

<p align="center"><b>Caveat: does not perform the reverse.</b></p>

![rotation fun](https://user-images.githubusercontent.com/602406/140731296-e7fdbfa5-3c05-49d2-9bf5-6a50164dd41b.png)

2021-11-10 00:06 UTC, PJB3005 approved these changes
Looks good to me but @metalgearsloth please double check.

2021-11-10 07:08 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                var v = new Angle(MathHelper.PiOver2).RotateVec(r);
I'm not a maths guy but:
- You probably want centre of mass not origin (LocalCenter is the property and needs to be converted to a world position)
- This is just a world angle?

2021-11-11 22:34 UTC, Efruit commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                var v = new Angle(MathHelper.PiOver2).RotateVec(r);
- Yeah, COM would be preferred. Can't test it yet (t. no .NET 6), but it should be a quick fix.
- I'm not a maths guy either; your guess is as good as mine (probably significantly better).

2021-11-23 01:17 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                var r = (oldParent.Transform.WorldPosition + oldBody.LocalCenter) - entity.Transform.WorldPosition;
Will need to consider parent's rotation, i.e. if the parent is rotated 180 degrees the actual spot is different and you can't just add the vectors together. You can probably just use the worldmatrix of oldParent to transform the localcenter. 

Also might need to consider the entity's centre of mass?

2021-12-05 02:56 UTC, metalgearsloth requested changes

2021-12-05 02:56 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                // TODO: Apply child's linear as angular on the parent?
nope

2021-12-05 02:56 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                    entity.Transform.WorldPosition; // TODO: Use entity's LocalCenter/center of mass somehow
Cache these into local variables where possible because they're expensive please.

2021-12-05 02:56 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                nRT.Multiply(-1f);
same as above, please cache because this method will be very expensive.

2021-12-05 15:25 UTC, Efruit commented on Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
> +                // TODO: Apply child's linear as angular on the parent?
well it was a nice thought

2021-12-06 03:19 UTC, metalgearsloth requested changes
Needs more caching, also use the new GetWorldPositionRotation method.

I tried to just push the changes but it was blocked so

2021-12-06 03:48 UTC, Efruit commented
> Needs more caching,

That's it. There's nothing left to cache.

> also use the new GetWorldPositionRotation method.

The one that this PR predates? Guess that gives me a rebase pass.

2021-12-06 10:30 UTC, metalgearsloth approved these changes
![image](https://user-images.githubusercontent.com/31366439/144830503-c8c40428-7cc7-4ac0-b004-d1d9e2367508.png)

FYI it's more the fact it halves the GetComponent calls being done which are the most expensive part of calculating world stuff.

2021-12-09 20:18 UTC, merged