Rich text redux
space-wizards/RobustToolbox pull request #2213
Opened 2021-11-09 17:20 UTC by Efruit

The preparation for Books and #2101 begins.

2021-11-27 20:35 UTC, Efruit commented
The content side is on [my fork's branch of the same name](https://github.com/Efruit/SS14/tree/rich-text-redux). Not gonna bother PRing it (yet) since this one still needs to be torn to shreds first.

2021-11-30 19:45 UTC, Efruit commented
Content side at https://github.com/space-wizards/space-station-14/pull/5625

2021-11-30 19:57 UTC, Efruit commented
Future Improvements:
- `Section.Meta` flag for color not being set
- `ISectionable` that replaces sections with `Section.Meta`'s `Localized` flag (requires extra metadata)
- Clickable links (also requires extra metadata)

2021-12-09 20:15 UTC, Acruid requested changes
All of the obsolete 'FormattedMessage.Builder' warnings need to be fixed.

2021-12-09 20:15 UTC, Acruid commented on Robust.Shared/Utility/CollectionExtensions.cs
> +    public static partial class Extensions
Why was this turned into a partial class?

2021-12-09 20:32 UTC, Efruit commented on Robust.Shared/Utility/CollectionExtensions.cs
> +    public static partial class Extensions
[strictly for personal reasons](https://github.com/space-wizards/RobustToolbox/pull/2213/commits/5b70986c5cb8d226cfcfbe8e76bf8aa0bc9683e9)

(Because having `Robust.Shared.Utility.Extensions` and `Robust.Shared.Utility.TextExtensions` seemed messy, and I didn't want to rename the existing `Extensions` to `CollectionExtensions`.)

2021-12-09 20:51 UTC, Efruit commented
> All of the obsolete 'FormattedMessage.Builder' warnings need to be fixed.

It'll have to be an ongoing process. `Builder` was only added as a stopgap to make the transition easier. It's a warning because it should NOT be used in new code. After `Content` has caught up, and no longer needs it, we can make it `internal` and nix the warning.

2021-12-10 04:44 UTC, Efruit commented
To expand a bit on that, `Builder` is *not*, in fact, obsolete. It has sanctioned (engine-internal) uses within markup parsers, since they need something that does exactly what `Builder` does.

Content, on the other hand, should either be putting `Section`s together manually (it's not hard), or using a markup parser.

But I haven't been able to find the `[PleaseDontUseThisExceptInThesePlaces]` attribute, so I went with `[Obsolete]` instead.

2021-12-12 00:45 UTC, Acruid approved these changes

2021-12-12 22:35 UTC, merged