Lighting de-lagging
space-wizards/RobustToolbox pull request #222
Opened 2017-06-07 19:40 UTC by Quantomicus

The client no more has extra lag when running, only the 'normal' amount of lag from the delta thing.

Please no more Texture.CopyToImage(), thanks.

2017-06-07 19:44 UTC, Quantomicus commented on SS14.Client/State/States/GameScreen.cs.rej
> +diff a/SS14.Client/State/States/GameScreen.cs b/SS14.Client/State/States/GameScreen.cs	(rejected hunks)
what the fuck

2017-06-08 09:23 UTC, psykzz requested changes
Any chance we can move to using a class to abstract away your huge messy dictionary?

We can still use the string name as key but instead of saving an opacity map and an image, just store a class that handles all that for us.

This is almost impossible to maintain as it is.

2017-06-08 09:36 UTC, PJB3005 commented
Yeah this is getting ridiculous.

2017-06-08 20:19 UTC, psykzz approved these changes

2017-06-08 23:40 UTC, ZoldorfTheWizard approved these changes
Its another hacky fix but it does fix the performance loss caused by reading the texture then immediately writing the changes

2017-06-08 23:41 UTC, merged