The End of Entity (Komm, Süsser Todd: Part 1.0)
space-wizards/RobustToolbox pull request #2295
Opened 2021-11-30 14:47 UTC by Zumorica

- Makes `IEntity` a sealed class instead of an interface.
- Removes `Entity`.
- Makes all `Entity` usages use `IEntity` instead.

See commits.
I won't change `IEntity` to be called `Entity` because it'd be a massive, breaking refactor for a type we're removing soon anyway.

"It all returns to nothing...
It all comes tumbling down,
tumbling down, tumbling down"

2021-11-30 14:50 UTC, metalgearsloth commented
https://www.youtube.com/watch?v=6kguaGI7aZg

2021-11-30 14:58 UTC, gradientvera commented
(tests failing unrelated to PR, blame PaulVS instead)

2021-11-30 22:58 UTC, PaulRitter requested changes

2021-11-30 22:58 UTC, PaulRitter commented on Robust.Shared/GameObjects/IEntity.cs
> +            return (T)EntityManager.GetComponent(Uid, typeof(T));
why not
```suggestion
            return EntityManager.GetComponent<T>(Uid);
```
?

2021-11-30 22:59 UTC, PaulRitter commented
i reran tests bc master tests dont fail anymore

2021-11-30 22:59 UTC, Zumorica commented on Robust.Shared/GameObjects/IEntity.cs
> +            return (T)EntityManager.GetComponent(Uid, typeof(T));
doesn't matter either way, oldcode

2021-11-30 23:00 UTC, Zumorica commented
> i reran tests bc master tests dont fail anymore

a bit useless if master isn't merged to this branch...

2021-11-30 23:00 UTC, PaulRitter commented
> > i reran tests bc master tests dont fail anymore
> 
> a bit useless if master isn't merged to this branch...

good point good point

2021-12-01 10:59 UTC, PaulRitter commented
tests failing for real now

2021-12-01 11:32 UTC, gradientvera commented
> tests failing for real now

Paul, I'm gonna fucking remove your certified git user card.

2021-12-02 13:50 UTC, PaulRitter commented
> > tests failing for real now
> 
> Paul, I'm gonna fucking remove your certified git user card.

excuse?

2021-12-02 13:51 UTC, Zumorica commented
> > > tests failing for real now
> > 
> > 
> > Paul, I'm gonna fucking remove your certified git user card.
> 
> excuse?

cause you still hadn't merged master into this branch lol

2021-12-02 14:07 UTC, PaulRitter commented
> > > > tests failing for real now
> > > 
> > > 
> > > Paul, I'm gonna fucking remove your certified git user card.
> > 
> > 
> > excuse?
> 
> cause you still hadn't merged master into this branch lol

![grafik](https://user-images.githubusercontent.com/16618384/144437693-750a788a-88a9-449f-bafd-48d3a35a08c0.png)

2021-12-03 10:01 UTC, merged