Remove Entity Transform/MetaData Component Cache
space-wizards/RobustToolbox pull request #2296
Opened 2021-12-01 02:50 UTC by Acruid

Removes transform/metadata caching on Entity, disposes components after calling event so systems can properly access comps to cleanup.

2021-12-02 13:04 UTC, Zumorica commented
Depends on https://github.com/space-wizards/space-station-14/pull/5657 being merged on content

2021-12-02 13:49 UTC, PaulRitter requested changes

2021-12-02 13:49 UTC, PaulRitter commented on Robust.Shared/GameObjects/Entity.cs
> +        }
```suggestion
        public TransformComponent Transform => EntityManager.GetComponent<TransformComponent>(Uid);
```

2021-12-02 13:49 UTC, PaulRitter commented on Robust.Shared/GameObjects/Entity.cs
>          }
should be
```csharp
        public MetaDataComponent MetaData => EntityManager.GetComponent<MetaDataComponent>(Uid);
```

2021-12-02 13:49 UTC, PaulRitter commented on Robust.Shared/GameObjects/Entity.cs
>          public Entity(IEntityManager entityManager, EntityUid uid)
```suggestion
        public Entity(EntityUid uid)
```

2021-12-02 13:49 UTC, PaulRitter commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
i think this means we can now replace this with
```csharp
AddComponent<MetadataComponent>(entity);
```

2021-12-02 15:33 UTC, Zumorica commented
@PaulRitter Except for the `AddComponent<MetaDataComponent>()` changes, all the changes you proposed are already part of #2295 so I'm not gonna do them here as well

2021-12-02 15:41 UTC, Zumorica commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
We can't do this yet because of how `AddComponent<T>(EntityUid)` works
```csharp
        public T AddComponent<T>(EntityUid uid) where T : Component, new()
        {
            if (!TryGetEntity(uid, out var entity)) throw new ArgumentException("Entity is not valid or deleted.", nameof(uid));

            return AddComponent<T>(entity);
        }
```

2021-12-03 08:13 UTC, PaulRitter commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
In L401, the entity gets added to the internal cache meaning the trygetent will go through. thats also why in L411, right below this, the `AddComponent<TransformComponent>(entity);` works without a hitch

2021-12-03 08:52 UTC, Zumorica commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
I literally tested and it didn't work...

2021-12-03 09:02 UTC, PaulRitter commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
I assume you used `AddComponent<MetadataComponent>(uid.Value);` instead of `AddComponent<MetadataComponent>(entity);`, what i said. Using the uid variant will try to get the entity and call the other variant.
I was wrong on the trygetent tho, weird that it falls through. Only reason i could see it being marked as Deleted but uhhhh, that shouldnt happen should it.

2021-12-03 09:25 UTC, PaulRitter commented on Robust.Shared/GameObjects/Entity.cs
> -        public bool Paused { get => MetaData.EntityPaused; set => MetaData.EntityPaused = value; }
absolutely based

2021-12-03 09:31 UTC, PaulRitter commented on Robust.Shared/GameObjects/EntityManager.cs
>              AddComponentInternal(uid.Value, metadata);
nvm

2021-12-03 09:33 UTC, merged