UserInterface/RichTextEntry: Apparently calling `Update` is optional before `Draw`.
space-wizards/RobustToolbox pull request #2340
Opened 2021-12-13 17:54 UTC by Efruit

Fixes whatever the hell was going wrong with the tooltip thing in Content.

2021-12-14 08:54 UTC, Zumorica approved these changes

2021-12-15 08:56 UTC, PaulRitter approved these changes

2021-12-15 08:56 UTC, PaulRitter commented on Robust.Client/UserInterface/RichTextEntry.cs
> +        // Same as above, but for the UI scale.
```suggestion
        // Last UI scale
```

2021-12-15 08:56 UTC, PaulRitter requested changes
fix the comment and we merg

2021-12-15 09:25 UTC, PaulRitter approved these changes

2021-12-15 09:25 UTC, merged