changes needed for inventory refactor
space-wizards/RobustToolbox pull request #2350
Opened 2021-12-17 00:23 UTC by PaulRitter

dnm for the love of god

2021-12-17 00:25 UTC, mirrorcult commented on Robust.Shared/Containers/BaseContainer.cs
> +                return false;
huh?

2021-12-17 00:25 UTC, mirrorcult commented on Robust.Shared/Containers/BaseContainer.cs
> +                return false;
nvm these are on two separte entities

2021-12-17 04:05 UTC, moonheart08 requested changes

2021-12-17 04:05 UTC, moonheart08 commented on Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
>              {
Why does this take an entitymanager ref and then never use it?

2021-12-17 14:39 UTC, PaulRitter commented on Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
>              {
good point!

2021-12-19 03:01 UTC, metalgearsloth approved these changes

2021-12-21 06:33 UTC, ElectroJr approved these changes

2021-12-28 10:26 UTC, metalgearsloth approved these changes

2021-12-28 10:26 UTC, metalgearsloth approved these changes

2021-12-30 21:54 UTC, merged