Engine changes for more server-pushed lighting variables
space-wizards/RobustToolbox pull request #2367
Opened 2021-12-23 02:02 UTC by Matz05

More of the variables on a client-side PointLight are now replicated from the server.
There's some controversy over whether this is the right way to do things, and even if it is I'm not sure I did it right as I just imitated existing structures in the code with limited understanding of their inner workings, but it seems to work in my testing.
This is necessary for bulbs inserted into PoweredLights to change more than just the colour, and have the values replicate to clients correctly, using the same logic already used for colour changes. An implementation of this is found in the corresponding content PR.

2021-12-23 02:39 UTC, metalgearsloth requested changes
Some of the others are virtual because the rendertree needs to update their bounds (and for color it can probably be removed).

2021-12-23 02:39 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/SharedPointLightComponent.cs
>      }
These don't need to be virtual.

2021-12-23 03:04 UTC, Matz05 commented on Robust.Shared/GameObjects/Components/Light/SharedPointLightComponent.cs
>      }
Fixed in the following commit.

2021-12-23 08:46 UTC, PaulRitter approved these changes

2022-01-04 15:57 UTC, metalgearsloth approved these changes

2022-01-04 15:57 UTC, merged