Adds config file support for Content.Client
space-wizards/RobustToolbox pull request #2373
Opened 2021-12-27 04:39 UTC by ike709

This is just lifted directly from an old commit on Acruid's fork.

Useful for OpenDream development so we don't have to tell people to pass any cvars as program arguments.

2021-12-28 16:34 UTC, PJB3005 requested changes

2021-12-28 16:34 UTC, PJB3005 commented on Robust.Client/GameController/GameController.cs
> +                _configurationManager.LoadFromFile(contentPath);
1. This should be loaded *before* appdata config, or at least not override the settings in it.
2. You should make this work even if there's no disk path available. It would be really confusing if this file only worked in development builds.

2022-01-13 14:28 UTC, metalgearsloth commented
@ike709 you coming back to this?

2022-01-13 16:29 UTC, ike709 commented
oops I forgot it existed, yeah I'll get back to it soon

2022-01-24 03:51 UTC, ike709 commented on Robust.Client/GameController/GameController.cs
> +                    var contentFile = Path.Combine(userDataDir, Options.ContentConfigFileName);
If this isn't what PJB meant then I have no idea what he did mean.

2022-01-25 12:33 UTC, PJB3005 commented on Robust.Client/GameController/GameController.cs
> +                    var contentFile = Path.Combine(userDataDir, Options.ContentConfigFileName);
This still isn't loading the config file from VFS, now you just made it fall back and try to load it from AppData if VFS is a zip file.

2022-01-25 12:34 UTC, PJB3005 commented on Robust.Client/GameController/GameController.cs
> +                    var contentFile = Path.Combine(userDataDir, Options.ContentConfigFileName);
You need to somehow allow ConfigurationManager to load from a stream (or something) and then read it in with `IResourceManager.ContentFileRead()`. None of this.

2022-01-25 22:15 UTC, closed without merging