No events on stopping components
space-wizards/RobustToolbox pull request #2378
Opened 2021-12-28 23:13 UTC by wrexbe

This change prevents a system from receiving an event for a component if its life cycle is stopping, or later. The lifecycle events seem to go through the bus on a different path, so they are unaffected by this change.

2021-12-28 23:14 UTC, ShadowCommander commented
Dose this work for player detached and mind detached?

2021-12-28 23:14 UTC, Zumorica commented
What's the rationale behind this?

2021-12-28 23:26 UTC, wrexbe commented
@ShadowCommander Seems to be fine, I went ghost, and back, suicided, and respawned.
@Zumorica It prevents about 7500 events from going off when the round restarts, and it lets a unit test pass in a different PR I made that is failing because a power event is happening after the entity is partially deleted.

2021-12-29 02:26 UTC, metalgearsloth commented
I've already run into issues where the eventbus is silently failing on other events so I'm not a huge fan of the change https://github.com/space-wizards/space-station-14/issues/5609

2021-12-29 02:31 UTC, Acruid requested changes
https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Atmos/EntitySystems/AirtightSystem.cs#L58
Existing code depends on the ability to raise an event from inside the `ComponentShutdown` and `ComponentRemove` lifestage events. This atmos code would break if this PR is merged.

> It prevents about 7500 events from going off when the round restarts

If this can be optimized, it needs to be done on a per-system basis, and address *why* that is happening.

> failing because a power event is happening after the entity is partially deleted.

You can check the component's lifestage inside the event for the same effect.

This PR as it is right now should not be merged.

2021-12-29 23:31 UTC, PaulRitter commented
> This PR as it is right now should not be merged.


damn, if even acruid is saying it.

jokes aside though, i also think this is a bad idea, same reasoning as sloth.

2021-12-29 23:45 UTC, closed without merging