Automatic Component Names (Alternate ending)
space-wizards/RobustToolbox pull request #2389
Opened 2022-01-02 00:06 UTC by wrexbe

This is a different implementation of automatic component names, based off of @Acruid's suggestions.

2022-01-02 00:20 UTC, Acruid approved these changes

2022-01-02 00:20 UTC, Acruid commented on Robust.Shared/GameObjects/Component.cs
> +        public string Name => IoCManager.Resolve<IComponentFactory>().GetComponentName(GetType());
Needs to be virtual if you want to keep compatibility with content (and to fix failing tests).

2022-01-02 00:21 UTC, wrexbe commented on Robust.Shared/GameObjects/Component.cs
> +        public string Name => IoCManager.Resolve<IComponentFactory>().GetComponentName(GetType());
Yeah, I have an idea. I'm doing it

2022-01-25 13:10 UTC, merged

2022-01-25 13:18 UTC, PaulRitter requested changes
why remove the compiler-if?

2022-01-25 13:18 UTC, PaulRitter commented on Robust.Client/GameObjects/ClientComponentFactory.cs
> -#if DEBUG
this

2022-01-25 13:18 UTC, PaulRitter commented on Robust.Server/GameObjects/ServerComponentFactory.cs
> -#if DEBUG
this

2022-01-25 13:18 UTC, PaulRitter commented on Robust.Shared/GameObjects/Components/DebugExceptionComponents.cs
> -#if DEBUG
this