Give container attempt events an optional reason output.
space-wizards/RobustToolbox pull request #2420
Opened 2022-01-13 08:14 UTC by ElectroJr

Useful for giving feedback to players when they are attempting to insert an entity into some container.

2022-01-13 09:37 UTC, PaulRitter requested changes
could do with a [notnullwhen(false)], otherwise lgtm.

2022-01-13 10:38 UTC, ElectroJr commented
> could do with a [notnullwhen(false)] 

I don't think you should be required to provide a reason string every time you want to cancel an insertion (or removal). While its useful as feedback for directly user initiated interactions, for things like lockers closing and failing to grab/insert other nearby lockers, I don't think you should have to provide localized reason strings for that. Similarly you'd have to add localised reason strings for failing to insert a map or grid entity into a container, which ideally a user should never even see.

And AFAIK there is no `[AlwaysNullWhen(true)]` or `[MaybeNotNullWhen(false)]` attribute.

2022-01-13 10:41 UTC, metalgearsloth commented
I'm a bit suss having this in engine tbh

2022-01-13 13:18 UTC, ElectroJr commented
> I'm a bit suss having this in engine tbh

It does feel a bit weirs having a reason field (which transparently exists for the content's `PopupSystem`) to exist in engine. But the alternative is for the storage, item-slots, and maybe eventually other systems to each create duplicates of these 4 events, which also feels icky to me. Especially as the more general engine event would then probably just go unused. But if that is preferred I'm ok with just doing that instead.

2022-01-13 13:23 UTC, metalgearsloth commented
@PJB3005 any thoughts?

2022-01-14 09:37 UTC, PaulRitter commented
>I don't think you should be required to provide a reason string every time you want to cancel an insertion (or removal). 

ur right

>I'm a bit suss having this in engine tbh

i think its reasonable supporting having a reason for containerinsert/remove failing. for one, i dont see a better way than this to implement it, secondly this would contribute to making inventorysystem even less of a wrapper of containersystem, moving the can(un)equip fully to containerevents

2022-01-25 13:09 UTC, PJB3005 commented
Seconding that I don't like this being in-engine. Honestly I feel like the actual "Can insert" code here should be a content-side thing instead since it's so game specific.

If you absolutely have to, don't make the reason a string. Make it an `object`.

2022-01-29 10:28 UTC, ElectroJr commented
Ok, I'll just go with content-side events specific to a given component/interaction. Currently very few things use the insert-attempt events anyways.

2022-01-29 10:28 UTC, closed without merging