Add IsQueuedForDeletion and make delete queue use hashset
space-wizards/RobustToolbox pull request #2421
Opened 2022-01-14 05:32 UTC by ElectroJr

Allows systems to check if an entity is about to be deleted before doing potentially unnecessary & expensive computations (e.g., ExtensionCableSystem)

2022-01-14 07:05 UTC, Zumorica requested changes

2022-01-14 07:05 UTC, Zumorica commented on Robust.Shared/GameObjects/EntityManager.cs
> -        protected readonly Queue<EntityUid> QueuedDeletions = new();
The reason we kept a queue as well was to maintain deletion order...

2022-01-14 07:52 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityManager.cs
> -        protected readonly Queue<EntityUid> QueuedDeletions = new();
ok, reverted that change

2022-01-15 10:33 UTC, ShadowCommander commented on Robust.Shared/GameObjects/EntityManager.cs
> +        public bool IsQueuedForDeletion(EntityUid uid) => QueuedDeletions.Contains(uid);
Is it faster to check the `QueuedDeleteionsSet`?

2022-01-15 16:35 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityManager.cs
> +        public bool IsQueuedForDeletion(EntityUid uid) => QueuedDeletions.Contains(uid);
AFAIK checking the hashset is faster, this was an accidental leftover from before where I had removed the queue and just had the hashset. I'll update this now.

2022-01-16 01:03 UTC, ShadowCommander approved these changes

2022-01-18 07:11 UTC, metalgearsloth approved these changes
conflicts

2022-01-18 08:02 UTC, merged