Fixes warnings
space-wizards/RobustToolbox pull request #2433
Opened 2022-01-17 21:33 UTC by wrexbe

I fixed the warnings I could see

2022-01-17 22:32 UTC, ShadowCommander requested changes

2022-01-17 22:32 UTC, ShadowCommander commented on Robust.Client/Debugging/DebugPhysicsSystem.cs
> +                    foreach (var fixture in _entityManager.GetComponent<FixturesComponent>(physBody.Owner).Fixtures.Values)
Is there a way to make `_physicsSystem.GetCollidingEntities()` also return the FixturesComponent? If not then this should be fine since its' a debug overlay.

2022-01-17 22:32 UTC, ShadowCommander commented on Robust.Server/ServerStatus/StatusHost.cs
> +#pragma warning disable CS0618 // For backwards compatibility
Maybe add a TODO to remove once MoMMI is refactored? If MoMMI can be refactored to async.

2022-01-17 22:32 UTC, ShadowCommander commented on Robust.UnitTesting/TestingModLoader.cs
> +#pragma warning disable CS0067 // Needed by interface
Another TODO maybe?

2022-01-18 03:09 UTC, wrexbe commented on Robust.Client/Debugging/DebugPhysicsSystem.cs
> +                    foreach (var fixture in _entityManager.GetComponent<FixturesComponent>(physBody.Owner).Fixtures.Values)
I don't see a simple way to do it, would push this PR too far out of scope.

2022-01-18 03:11 UTC, wrexbe commented on Robust.UnitTesting/TestingModLoader.cs
> +#pragma warning disable CS0067 // Needed by interface
It's kind of a false positive, this is for testing. The real class uses it, so I don't think removing this is a goal.

2022-01-18 03:15 UTC, wrexbe commented on Robust.Server/ServerStatus/StatusHost.cs
> +#pragma warning disable CS0618 // For backwards compatibility
Added a todo

2022-01-18 08:08 UTC, ShadowCommander approved these changes

2022-01-18 22:24 UTC, merged