Make OffsetRsiDir() and GetDir() public
space-wizards/RobustToolbox pull request #2434
Opened 2022-01-17 23:58 UTC by ElectroJr

Makes `SpriteComponent`'s `OffsetRsiDir()` public and moves `GetDir()` function into direction extensions.

Nice to have for [future content PR]

2022-01-21 09:34 UTC, PaulRitter requested changes

2022-01-21 09:34 UTC, PaulRitter commented on Robust.Client/Utility/DirExt.cs
> +                RSI.State.DirectionType.Dir8 => angle.GetDir().Convert(type),
just do angle.getdir.convert for both dir4 and dir8 since it accounts for that internally already

2022-01-25 13:11 UTC, PJB3005 requested changes

2022-01-25 13:11 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +        public static RSI.State.Direction OffsetRsiDir(RSI.State.Direction dir, DirectionOffset offset)
This shouldn't be in `SpriteComponent` if it's made public.

2022-01-29 10:40 UTC, ElectroJr commented on Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
> +        public static RSI.State.Direction OffsetRsiDir(RSI.State.Direction dir, DirectionOffset offset)
Fair point. I've made it an extension method and moved it to `DirExt.cs`

2022-01-29 13:40 UTC, PJB3005 approved these changes

2022-01-31 08:22 UTC, merged