Fix spinbot CBT
space-wizards/RobustToolbox pull request #2456
Opened 2022-01-25 04:01 UTC by metalgearsloth

- Cursor no longer resets to position 0 on input
- Scrolling will update cursor position as required

2022-01-25 04:02 UTC, metalgearsloth commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        public bool SetText(string newText)
The Text property defaults the cursor position to 0 which I guess is okay for copy-paste situations?

2022-01-25 04:13 UTC, mirrorcult commented
spinbot

2022-01-25 04:57 UTC, ShadowCommander requested changes

2022-01-25 04:57 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +                    _lineEdit.CursorPosition = textLength;
Could you rename `LineEdit.SetText` to `LineEdit.InternalSetText` and move this code to a new `LineEdit.SetText`?

2022-01-25 05:00 UTC, ShadowCommander requested changes

2022-01-25 05:00 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +                    _lineEdit.CursorPosition++;
Does this work if the `textLength` jumps more than one character? (e.g. 1 to 3, or 3 to 12)

2022-01-25 05:05 UTC, ShadowCommander requested changes

2022-01-25 05:05 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +                    OverrideValue(i);
This needs to call the `ValueChanged`, so either use Value again or call the event here.

2022-01-25 13:05 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        public bool SetText(string newText)
The dangerous thing about this function is that if cursor position isn't adjusted manually, you can get out of bounds errors I think.

2022-01-25 13:05 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +                    _lineEdit.CursorPosition++;
Yeah that should be a while loop instead.

2022-02-17 00:24 UTC, closed without merging

2022-02-17 00:24 UTC, metalgearsloth commented
spinbox will remain cbt