Hopefully fix appearance component mispredict reconciliation
space-wizards/RobustToolbox pull request #2460
Opened 2022-01-26 07:03 UTC by ElectroJr

fixes #2127.

The appearance component state handling code sets the component's appearance data dictionary equal to the state's dictionary. As a result, if the client then updates and dirties the component during prediction, it actually also modifies the most recently received server state. So when a client mispredicts and does not receive a new server state, it will incorrectly reset itself to the dirty value.

A partial fix would be to just make the state-handling take a shallow clone of the appearance dictionary, but that could in principle still cause difficult to diagnose reconciliation issues. So this PR just restricts the appearance data values to be value-type or `ICloneable` and makes the state handling code duplicate the appearance dictionary

. I'm really not sure if this is the correct way to go about this. It would be nice to just automatically support things like `List<ICloneable>` & similarly for dictionaries. But I don't know how to fully generalize it to allow going from something like `List<string>` -> `object` -> `List<Cloneable>`, and then easily reversing that in visualizers without iterating & casting. So just requiring that complex appearance data must be a by-value struct or cloneable class seems fine?

This also requires a content PR to avoid breaking some visualizers.

2022-02-13 19:26 UTC, PaulRitter requested changes

2022-02-13 19:26 UTC, PaulRitter commented on Robust.Shared/Utility/CollectionExtensions.cs
> +        public static List<T> ShallowClone<T>(this IReadOnlyList<T> self)
whats this about

2022-02-14 02:57 UTC, ElectroJr commented on Robust.Shared/Utility/CollectionExtensions.cs
> +        public static List<T> ShallowClone<T>(this IReadOnlyList<T> self)
IIRC I wanted this for space-wizards/space-station-14/pull/6319/files, for the `IReadOnlyList` in `SharedMapLayerData.cs`. But I changed that around and its not needed anymore, so I will get rid of this change.

2022-02-16 14:04 UTC, metalgearsloth approved these changes
@PJB3005 speak now or forever hold your peace son

2022-02-16 22:11 UTC, PJB3005 approved these changes

2022-02-16 22:26 UTC, PaulRitter approved these changes

2022-02-16 22:26 UTC, merged