Don't use worldbounds for PVS
space-wizards/RobustToolbox pull request #2473
Opened 2022-01-30 05:58 UTC by metalgearsloth

@PaulRitter 

Don't look until exams done or I cut you.

Main goal is if a grid is spinning then no new chunks should be going in range as a result.

2022-02-03 18:46 UTC, PaulRitter requested changes
get owned nerd

2022-02-03 18:46 UTC, PaulRitter commented on Robust.Shared.Maths/Vector2.cs
> +        public readonly Vector2i Ceiling()
```suggestion
        public readonly Vector2i Ceiled()
```

2022-02-03 18:46 UTC, PaulRitter commented on Robust.Server/GameStates/ChunkIndicesEnumerator.cs
> +        _y = _topRight.Y;
danger danger. this one should be `bottomLeft`

2022-02-09 14:41 UTC, metalgearsloth commented on Robust.Server/GameStates/ChunkIndicesEnumerator.cs
> +        _y = _topRight.Y;
A

2022-02-09 14:47 UTC, metalgearsloth commented on Robust.Shared.Maths/Vector2.cs
> +        public readonly Vector2i Ceiling()
Ceiled's not even a word m8

2022-02-10 08:33 UTC, PaulRitter approved these changes

2022-02-15 09:56 UTC, metalgearsloth commented
This will probably be superseded by whatever gets used for https://github.com/space-wizards/RobustToolbox/issues/2527 but okay for now.

2022-02-15 10:07 UTC, merged