Optimise PVS cangetcompstate
space-wizards/RobustToolbox pull request #2560
Opened 2022-02-20 04:55 UTC by metalgearsloth

Most of it is just going to come from the ordering swap where we check if there's even a compstate to add or get before raising the event.

2022-02-20 04:58 UTC, mirrorcult commented on Robust.Shared/GameObjects/Components/MetaDataComponent.cs
> +    }
why not just like a component

2022-02-20 05:02 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/MetaDataComponent.cs
> +    }
Fastest would just be caching the flag when we get metadata earlier to avoid the getcomponent entirely. I also foresee container culling using it unless we get better ideas but see what paul thinks.

2022-02-20 11:35 UTC, Zumorica reviewed
I'm not particularly happy about `MetaDataSystem`'s `AddFlag` and `RemoveFlag` methods not using the resolves convention, but I guess if you want it to be as performant as possible it's fine.

2022-02-27 12:56 UTC, PaulRitter commented on Robust.Shared/GameObjects/Components/MetaDataComponent.cs
> +    }
we can definitely grab the metadatacomp from earlier in 99% of cases

2022-02-27 12:56 UTC, PaulRitter requested changes
lgtm but i dont see you setting the flag on any entity yet, or am i missing smth?

2022-02-27 12:58 UTC, metalgearsloth commented
> I'm not particularly happy about `MetaDataSystem`'s `AddFlag` and `RemoveFlag` methods not using the resolves convention, but I guess if you want it to be as performant as possible it's fine.

That should be fine to change, as long as it's not in PVS it's whatever.

2022-02-27 13:08 UTC, metalgearsloth commented
Gonna re-profile before merge sometime but should be good now.

2022-02-27 13:23 UTC, PaulRitter approved these changes
a

2022-02-27 13:45 UTC, merged