Add IsInContainer bool to transform component.
space-wizards/RobustToolbox pull request #2585
Opened 2022-03-05 10:32 UTC by ElectroJr

This PR makes a couple of changes with the goal to speed up some container functions.

The main change is to just give transform component a bool for quickly checking whether an entity is in a container. This helps speed up `IsEntityInContainer` and `TryGetContainingContainer` calls, which are used for most most interactions and several entity-lookups (e.g., explosions). Adding or removing an entity to a container, and the existing is-in-container checks all already involve fetching the transform component anyways. Previously the IsInContainer functions would then try to resolve a `ContainerManagerComponent` on the entity's parent, and if one exists, iterate over all containers and their contained entities to check that the given entity is actually inside of one (instead of just parented to something that happens to have containers),

Other changes include:
- Making Insert, remove, and some other functions take in optional transform component arguments.
- Mark some `ContainerHelpers` with direct `ContainerSystem` replacements as obsolete
- Slightly extending `ContainerSystem.EnsureContainer` so that it has the same functionality as the container helper function
	- Namely: adding an `out bool` that specifies whether the container already existed, or was newly created.

2022-03-05 11:57 UTC, metalgearsloth commented
what about storing it on metadata flags?

2022-03-05 14:30 UTC, ElectroJr commented
> what about storing it on metadata flags?

Yeah could also do that, though that would then require one additional resolve on insert/remove. But that's probably fine. I'll update the PR to do that.

Having more than one flags also means the flag being removed has to be sent in the removal attempt event, which probably should have been done in the first place.

2022-03-05 15:22 UTC, ElectroJr commented
Now using metadata flags. Requires a content PR now, because some container functions had their optional transform component replaced with a metadata component. Also generalised metadata flag removal to support more than one flag

2022-03-05 16:37 UTC, mirrorcult requested changes

2022-03-05 16:37 UTC, mirrorcult commented on Robust.Shared/Containers/BaseContainer.cs
> +            DebugTools.Assert(ownerTransform == null || ownerTransform.Owner == Owner);
resolves already assert this on debug

2022-03-05 16:37 UTC, mirrorcult commented on Robust.Shared/Containers/BaseContainer.cs
> +        protected virtual void InternalInsert(EntityUid toinsert, IEntityManager entMan, MetaDataComponent? meta)
```suggestion
        protected virtual void InternalInsert(EntityUid toinsert, IEntityManager entMan, MetaDataComponent? meta=null)
```

2022-03-05 16:37 UTC, mirrorcult commented on Robust.Shared/Containers/BaseContainer.cs
> +        protected virtual void InternalRemove(EntityUid toremove, IEntityManager entMan, MetaDataComponent? meta)
```suggestion
        protected virtual void InternalRemove(EntityUid toremove, IEntityManager entMan, MetaDataComponent? meta=null)
```

2022-03-06 07:27 UTC, ElectroJr commented on Robust.Shared/Containers/BaseContainer.cs
> +            DebugTools.Assert(ownerTransform == null || ownerTransform.Owner == Owner);
Yeah, but this isn't in a system, and is just using `??= entMan.GetComponent<>()` so those checks aren't being done without this assert.

2022-03-06 23:40 UTC, metalgearsloth commented on Robust.Shared/Containers/ContainerHelpers.cs
> +        /// Am I inside a container? Only checks the direct parent.
Should put a TODO on this because functionally containers are nested everywhere else regardless if the children are also in containers.

2022-03-11 03:01 UTC, ElectroJr commented on Robust.Shared/Containers/ContainerHelpers.cs
> +        /// Am I inside a container? Only checks the direct parent.
I've just added a variant that does a recursive check.

2022-03-14 04:55 UTC, metalgearsloth approved these changes

2022-03-14 04:55 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            return IsEntityOrParentInContainer(xform.ParentUid, metas: metas, xforms: xforms);
This is similar to TryGetOuterContainer so can just update that with the flag and have this method call that one?

2022-03-14 04:55 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedGridTraversalSystem.cs
> +                meta.EntityDeleted ||
Might as well pass EntityQuery in (grid traversal pretty expensive already sooooo yeahhhh)

2022-03-15 08:26 UTC, ElectroJr commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            return IsEntityOrParentInContainer(xform.ParentUid, metas: metas, xforms: xforms);
TryGetOuterContainer will always iterate all the way up to the map looking for the outermost container, whereas this should terminate whenever it finds the first entity inside of a container. This also doesn't need to fetch the container manager component, so keeping them separate should keep this slightly faster.

But I will add flag-checks to TryGetOuterContainer.

2022-03-31 02:23 UTC, merged