Implemented auto UI Scaling :D
space-wizards/RobustToolbox pull request #2599
Opened 2022-03-13 03:32 UTC by Jezithyr

- Implemented autoUI scaling, scaling supports down to 520 by 520 pixel screens(Idk why you'd even have this)
- UI scaling can be adjusted by overriding the window root class

2022-03-13 03:33 UTC, mirrorcult commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +                return (scaleRatioX < scaleRatioY) ? scaleRatioX : scaleRatioY;
indentation is fucked here

2022-03-13 03:33 UTC, mirrorcult commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +                Logger.DebugS("DEBG", scaleRatioY.ToString());
leftover

2022-03-13 08:17 UTC, mirrorcult commented
@PJB3005

2022-03-13 11:30 UTC, PaulRitter requested changes

2022-03-13 11:30 UTC, PaulRitter commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            scaleRatioX = (scaleRatioX > autoScaleMin) ? scaleRatioX : autoScaleMin;
i think you can condense this into
```suggestion
            scaleRatioX = Math.Clamp(((float)windowSize.X-minScaleRes.X)/(maxScaleRes.X-minScaleRes.X)*osScale, autoScaleMin, osScale)
```

2022-03-13 11:30 UTC, PaulRitter commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            scaleRatioY = (scaleRatioY > autoScaleMin) ? scaleRatioY : autoScaleMin;
same here

2022-03-13 11:30 UTC, PaulRitter commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            return (scaleRatioX < scaleRatioY) ? scaleRatioX : scaleRatioY;
```suggestion
            return Math.Min(scaleRatioX, scaleRatioY);
```

2022-03-13 21:43 UTC, Jezithyr commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            scaleRatioY = (scaleRatioY > autoScaleMin) ? scaleRatioY : autoScaleMin;
Fixed

2022-03-13 22:28 UTC, PJB3005 commented on Robust.Client/UserInterface/Control.Layout.cs
> +
These properties shouldn't be on `Control` if they only get used by `WindowRoot`.

2022-03-13 22:28 UTC, PJB3005 commented on Robust.Client/UserInterface/Control.Layout.cs
> +        public virtual bool AutoScale => false;
All of these are get-only computer properties so you can't actually change them. You probably want `{ get; set; } = initialValue;` instead.

2022-03-13 22:28 UTC, PJB3005 commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            scaleRatioY = (scaleRatioY > autoScaleMin) ? scaleRatioY : autoScaleMin;
Isn't this already handled by the clamp above?

2022-03-13 22:57 UTC, Jezithyr commented on Robust.Client/UserInterface/Control.Layout.cs
> +
Fixed by moving to Window root

2022-03-13 22:58 UTC, Jezithyr commented on Robust.Client/UserInterface/Control.Layout.cs
> +        public virtual bool AutoScale => false;
Fixed

2022-03-13 22:58 UTC, Jezithyr commented on Robust.Client/UserInterface/UserInterfaceManager.cs
> +            scaleRatioY = (scaleRatioY > autoScaleMin) ? scaleRatioY : autoScaleMin;
Good catch, yeah I got confused thinking that it was the old code for the clamp below

2022-03-14 01:13 UTC, Jezithyr reviewed
Fixed

2022-03-14 02:26 UTC, merged