fix sequence node serialization issue
space-wizards/RobustToolbox pull request #2610
Opened 2022-03-18 11:13 UTC by ElectroJr

Currently `SequenceDataNode.Except()` is broken and will always return an empty sequence. If you fix that, there is a separate issue where the lack of an equality override results in it not properly removing entries (the `HashSet.Contains()` check passes when it shouldn't).

This PR tries to fix both of these,  I'm not 100% sure what the all the ramifications of the data-node changes are so someone who knows about this stuff should definitely have a look, 

Fixing this bug also requires fixing content bugs:
- `EntityStorageComponent` uses Container.ID before the containers have been initialised (ID = null).
- systems that add fixtures don't check if the fixture already exists. To help with this, this PR also adds a TryCreateFixture() function

Finally, there is an issue where fixture IDs get automatically generated, which means that when fixtures get properly serialized the fixture definitions bloat map files. Instead of updating content to ensure that all prototypes specify fixture IDs, this just sorta dodges the problem by not serializing auto-generated Ids.

2022-03-20 16:57 UTC, PaulRitter requested changes
lgtm besides the nitpick

2022-03-20 16:57 UTC, PaulRitter commented on Robust.Shared/Serialization/Markdown/Sequence/SequenceDataNode.cs
> +            foreach (var nodeNode in _nodes)
no need to copy node._nodes here. remove the `set` variable and directly use it imo

2022-03-23 12:23 UTC, metalgearsloth approved these changes

2022-03-23 12:23 UTC, metalgearsloth commented on Robust.Shared/Physics/FixtureSystem.cs
> +        ///     Attempts to add a new fixture. Will do nothing ia a fixture with the requested ID already exists.
```suggestion
        ///     Attempts to add a new fixture. Will do nothing if a fixture with the requested ID already exists.
```

2022-03-23 12:34 UTC, merged