testmerge
space-wizards/RobustToolbox pull request #2693
Opened 2022-04-05 21:38 UTC by PaulRitter

paging @PJB3005 for a vibecheck on publishing the client under the custom version, as well as how to remove the version afterwards.
the idea is that the workflow can get triggered manually & will provide a git commit hash to change the submodule to temporarily.
also im p sure i need to push the removal of the branch in the remove-testmerge workflow somehow, gotta look that up

2022-06-18 05:03 UTC, metalgearsloth commented
@PJB3005 is this a merge or a close.

2022-08-12 10:51 UTC, PJB3005 requested changes
You aren't publishing a Git tag in any of this, so there's no way for the content build scripts to correctly determine which engine version they need to use. 

Also, it isn't going to be possible to publish Robust Modules with this since the version resolution system won't be able to avoid using them. I feel like we should figure that out.

I'm also not a fan of relying on PR numbers explicitly. It may be nicer to allow any branch to be test merged and have an easy way to create test merge branches from PRs. This would allow you to merge multiple PRs into a single test merge.

2022-08-12 10:51 UTC, PJB3005 commented on .github/workflows/remove_testmerge.yml
> +        run: git branch -d testmerge-${{ github.event.inputs.pr }}
This is only gonna remove the testmerge branch off the build-runner's local repo, not the actual repo on GitHub.

2022-08-12 10:51 UTC, PJB3005 commented on .github/workflows/remove_testmerge.yml
> +      - name: Remove the client build off of centcomm (todo)
Not sure whether this is worth the trouble, we can just keep them up and have content not use them.

2022-08-12 14:21 UTC, PaulRitter commented on .github/workflows/testmerge.yml
> +      - name: Checkout PR and create new branch
im never checking out the pr branch here + this should prob just override the branch if it already exists(?)

2023-05-07 02:52 UTC, closed without merging