Create empty CODE_OWNERS file
space-wizards/RobustToolbox pull request #270
Opened 2017-07-10 09:05 UTC by psykzz

2017-07-10 09:29 UTC, PJB3005 commented
Shouldn't it be `CODEOWNERS` instead?

2017-07-11 23:10 UTC, ZoldorfTheWizard submitted a review, later dismissed

2017-07-12 18:37 UTC, PJB3005 requested changes
GitHub's documentation pretty clearly states it's `CODEOWNERS`, not `CODE_OWNERS`. Unless you're sure this works I'm marking this as request changes.

2017-07-14 23:51 UTC, ZoldorfTheWizard approved these changes

2017-07-15 10:27 UTC, PJB3005 approved these changes

2017-07-15 10:27 UTC, merged