ZSTD game states + other improvements
space-wizards/RobustToolbox pull request #2737
Opened 2022-04-15 10:25 UTC by PJB3005

2022-04-15 16:02 UTC, PaulRitter requested changes

2022-04-15 16:02 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +        private void UpdateZStdParams()
```suggestion
        private void UpdateZStdParams(int compressionLevel)
```

2022-04-15 16:02 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +            var compressionLevel = _cfg.GetCVar(CVars.NetPVSCompressLevel);
```suggestion
```

2022-04-15 16:02 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +            UpdateZStdParams();
```suggestion
            UpdateZStdParams(_cfg.GetCVar(CVars.NetPVSCompressLevel));
```

2022-04-15 16:02 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +            _cfg.OnValueChanged(CVars.NetPVSCompressLevel, _ => UpdateZStdParams(), true);
```suggestion
            _cfg.OnValueChanged(CVars.NetPVSCompressLevel, UpdateZStdParams, true);
```

2022-04-15 16:02 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +                (int i, ref PvsThreadResources resource) =>
this will no longer batch players. intended?

2022-04-15 16:41 UTC, PJB3005 commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +                (int i, ref PvsThreadResources resource) =>
`Parallel.For` basically already does a very similar internal for loop to do the range anyways, so I figured it wasn't worth the extra noise.

2022-04-15 16:43 UTC, PJB3005 commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +        private void UpdateZStdParams()
I did all the `UpdateZStdParams` like this so that if we need to add more zstd parameters in the future (idk for what) they assignment logic is self contained. This seems more much organized and self-contained IMO.

2022-04-16 12:29 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +        private void UpdateZStdParams()
fair enough, that makes sense

2022-04-16 12:36 UTC, PaulRitter commented on Robust.Server/GameStates/ServerGameStateManager.cs
> +                (int i, ref PvsThreadResources resource) =>
looking at the source, appears it does. interesting. lgtm

2022-04-16 12:36 UTC, PaulRitter approved these changes

2022-04-16 12:37 UTC, merged