Bsdiff replacement, submodule handling framework.
space-wizards/RobustToolbox pull request #275
Opened 2017-07-12 18:41 UTC by PJB3005

Replaced the `bsdiff.NET` library we were using with a Rust-based library. Should be MUCH more transparent about memory usage (Rust has no GC and everything is allocated and deallocated inside its calls) and prevent the GC from getting overworked. Thus fixing #206, probably.

Part of this is a git hooks system for managing submodules, because `SS14.Shared.Bsdiff` is a submodule.

Don't merge this yet there's some other things I want to do.

2017-07-12 21:07 UTC, ZoldorfTheWizard requested changes

2017-07-12 21:07 UTC, Silvertorch5 commented on readme.md
> +Before you go to build SS14, you should run the `RUN_THIS.py` Python script using Python 3.5+. If you don't do this, it will happen on the first build, **but the first build will fail**. This is nece
Simplify "If you don't do this, it will happen on the first build, **but the first build will fail**." to If you don't do this, **the first build will fail**.

2017-07-12 21:09 UTC, PJB3005 commented
Ok so no matter what this literally doesn't fix it the memory leak is caused by something else entirely WHAT THE HELL.

2017-07-15 11:47 UTC, PJB3005 commented
I'm closing this. When we need the submodule script, we can salvage it.

2017-07-15 11:47 UTC, closed without merging

2017-10-29 20:42 UTC, Quantomicus commented
Oh, the iron E.