Speed up map init, and unpause map on init
space-wizards/RobustToolbox pull request #2781
Opened 2022-05-01 05:28 UTC by ElectroJr

Currently the `mapinit` command un-pauses all entities, but not the map itself. This updates `MapManager.DoMapInitialize()` so that it also un-pauses the map.

This PR also removes the `RunMapInit` EntityUid extension, in favour of adding a method to EntityManager. This also fixes a problem where `MapManager.DoMapInitialize()` would do an IEntityManager resolve for every entity on the map.

It also changes some init/startup function so that they either use a metadata query or accept a metadata component as an input.

2022-05-01 05:55 UTC, ShadowCommander requested changes

2022-05-01 05:55 UTC, ShadowCommander commented on Robust.Shared/Map/MapManager.Pause.cs
> -
Remove the ClearMapPreInit method if there's no other references.

2022-05-01 13:02 UTC, ElectroJr commented
I'm gonna be busy for the next few days and I probably wont have time to update this and fix whichever test failed, so in the meantime feel free either update or replace this PR

2022-05-05 09:06 UTC, metalgearsloth commented on Robust.Server/Maps/MapLoader.cs
>              }
Entities aren't being marked as paused for a non-mapinitialized map so saltern runs for a few ticks in the failed test.

2022-05-05 09:21 UTC, merged