Significantly optimise prediction resetting
space-wizards/RobustToolbox pull request #2826
Opened 2022-05-15 13:58 UTC by metalgearsloth

Turns out just tracking dirty entities and not iterating 30k is much faster.

This is gonna be very sussy and I'm not sure the best way to add a test to make sure functionality doesn't change.

2022-05-15 15:40 UTC, ElectroJr commented on Robust.Client/GameStates/PVSSystem.cs
> +    {
probably needs to check `IsClientSide` here

2022-05-15 22:18 UTC, metalgearsloth commented
Ready for review I guess; I'm still a bit sussy on it as I'm not familiar with clientgamestatemanager's flow but none of my asserts ever tripped even with fakelag...

2022-05-16 01:03 UTC, ElectroJr commented on Robust.Client/GameStates/PVSSystem.cs
> +
Assuming everything it working properly, the `if (...) continue` should always fail, right?
So why not just make it a debug assert and speed up release slightly.

also the comment can probably just be removed.

2022-05-16 01:06 UTC, ElectroJr commented on Robust.Client/GameStates/PVSSystem.cs
> +
And if its about checking the entity is deleted, the comment in the ClientGameStateManager around the `_processor.TryGetLastServerStates()` implies that it would handle that situation

2022-05-16 01:27 UTC, ElectroJr commented on Robust.Client/GameStates/PVSSystem.cs
> +        }
I think the logic here should be reversed? Currently its only ever removing a single tick and leaving behind entities that were predicted to get dirtied.

Actually, when would partial resets actually be used. AFAIK currently this is just used to always clear all dirty entities.

2022-05-16 03:37 UTC, metalgearsloth commented on Robust.Client/GameStates/PVSSystem.cs
> +
It does get hit for reasons; I don't really know what happens with resetting entity modified ticks.

2022-05-16 04:55 UTC, ElectroJr commented on Robust.Client/GameStates/PVSSystem.cs
> +        }
maybe just 
```suggestion
        foreach (var (tick, sets) in _dirtyEntities)
        {
            sets.Clear();
            _dirtyPool.Return(sets);
        }
        _dirtyEntities.Clear();
```

2022-05-16 04:57 UTC, ElectroJr approved these changes
It seeeems to work fine? But maybe best to get someone else to also look at it.

2022-05-16 09:38 UTC, PJB3005 requested changes

2022-05-16 09:38 UTC, PJB3005 commented on Robust.Client/GameStates/PVSSystem.cs
> +    // Because the server does something identical in PVS sooooo
That doesn't sound like a very good reason to me. We're not doing PVS here so don't call it that.

2022-05-16 09:44 UTC, PaulRitter requested changes
nitpicks, otherwise lgtm

2022-05-16 09:44 UTC, PaulRitter commented on Robust.Shared/GameStates/SharedPVSSystem.cs
> +internal abstract class SharedPVSSystem : EntitySystem
why does this exist? i see no reason for it

2022-05-16 09:44 UTC, PaulRitter commented on Robust.Client/GameStates/PVSSystem.cs
> +
mucho comments

2022-05-16 12:08 UTC, merged