Remove ambiguity in sprite specifier
space-wizards/RobustToolbox pull request #2844
Opened 2022-05-19 23:07 UTC by ElectroJr

Currently it is ambiguous whether a sprite specifier defined in yaml using just a single string is meant to be an entity prototype or a texture path.

Currently this is resolved by doing a `IoCManager.Resolve<Prototypes.IPrototypeManager>().HasIndex()`, and if it fails, it assumes that the string is a resource path for a texture. This slows down entity loading / spawning.

So this PR makes entity prototype sprite specifiers use a `MappingDataNode` instead. So now:
- `ValueDataNode` implies a texture path
- `MappingDataNode` with an "entity" key implies an entity prototype
- Any other `MappingDataNode` implies an RSI

2022-05-20 02:52 UTC, wrexbe approved these changes

2022-05-20 03:59 UTC, metalgearsloth commented
@PaulRitter when you get time bb

2022-05-23 19:01 UTC, PaulRitter requested changes

2022-05-23 19:01 UTC, PaulRitter commented on Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
>              return new ValidatedValueNode(node);
just return whatever the validate call of the itypereader<tex, val> returns

2022-05-23 19:01 UTC, PaulRitter commented on Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
> +
you should have an explicit error if the entitynode is not a valuedatanode instead of just throwing it at the rsi-validator, resulting in a somewhat useless error message.

2022-05-23 19:01 UTC, PaulRitter commented on Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
>                  : new ValidatedValueNode(node);
tbqh this should not ioc.resolve but should either use the dependencycollection, or even create a dependency-field. iirc serv3 injects the typeserializers with dependencies

2022-05-23 23:03 UTC, ElectroJr commented on Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
>                  : new ValidatedValueNode(node);
It doesn't seem to inject, so for now I've switched it and two other IoCManager uses in other files to use the dependency collection.

2022-05-24 07:56 UTC, PaulRitter commented on Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
>                  : new ValidatedValueNode(node);
ahhh wait i remember, we explicitely *dont* do that bc the dependencycollection might differ iirc. either or, using the dependencycollection is good

2022-05-24 07:59 UTC, PaulRitter approved these changes

2022-05-27 00:16 UTC, merged