Ignore missing components on the client
space-wizards/RobustToolbox pull request #2846
Opened 2022-05-20 15:56 UTC by wrexbe

Made it so client doesn't care if the component isn't registered.

Content half: https://github.com/space-wizards/space-station-14/pull/8308

2022-05-24 10:31 UTC, PJB3005 requested changes
Put this behind a CVar or something. Single player games would be screwed over by this in its current state.

2022-05-25 05:17 UTC, wrexbe commented
It is now opt-in on the content client.

2022-05-25 07:44 UTC, mirrorcult approved these changes

2022-05-27 13:30 UTC, PJB3005 approved these changes

2022-05-27 13:30 UTC, merged