Add enum and custom hash set serializers
space-wizards/RobustToolbox pull request #2973
Opened 2022-06-21 23:41 UTC by ElectroJr

This adds two new custom type serializers.

Firstly, `EnumStringSerializer` which attempts to map strings onto enums via `IReflectionManager.TryParseEnumReference`. This is useful for things like sprite layers & appearance component keys, which can be either strings or enums. Currently anything that reads these from yaml has to manually call the reflection manager & has no yaml linting.

Secondly, this adds a variant of the hash set serializer that uses another custom type serializer to serialize the actual values. There should really also be list & dictionary variants of these, but initially this is just hash sets. This avoids the need to generate set/list/dict variants of each custom serializer, like is currently done for prototype Ids. So for example the `PrototypeIdHashSetSerializer` could now just be replaced with a `CustomHashSetSerializer<string, PrototypeIdSerializer<DamageGroupPrototype>>`

2022-06-23 08:48 UTC, PaulRitter requested changes
either make the enumstringserializer truly generic, making it only parse enums, or create a serializer thats explicitely for layer and appearance data keys. this will just confuse ppl

2022-06-23 08:48 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +        public IReflectionManager ReflectionManager => _reflectionManager;
kinda sus on this, i'd rather you use the dependencycollection provided to the serializer, although this saves some resolves ofc

2022-06-23 08:48 UTC, PaulRitter commented on Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/EnumStringSerializer.cs
> +public sealed class EnumStringSerializer : ITypeSerializer<object, ValueDataNode>
either make this return a enum or throw, dont return the string. for special cases like the layer and appearance data key, create a seperate serializer

2022-06-23 18:58 UTC, ElectroJr commented
> either make the enumstringserializer truly generic, making it only parse enums, or create a serializer thats explicitely for layer and appearance data keys. this will just confuse ppl

Making it only parse enums would render it useless for appearance & sprite key datafields, so I guess I'll just rename it to make it more explicit. Ill rename it to `AppearanceKeySerializer`, given that sprite keys can technically be any object (though I'll probably change this eventually).

2022-06-23 18:58 UTC, ElectroJr commented on Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/EnumStringSerializer.cs
> +public sealed class EnumStringSerializer : ITypeSerializer<object, ValueDataNode>
I'll just explicitly make this a more specialised serializer

2022-06-23 19:06 UTC, ElectroJr commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +        public IReflectionManager ReflectionManager => _reflectionManager;
Would there be an easy way to somehow have the serialization manager automatically use the collection to perform some common resolves (prototype, reflection), so that they don't need to get re-resolved for every read?

2022-06-24 07:18 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +        public IReflectionManager ReflectionManager => _reflectionManager;
not as of now, sadly. but feel free to open an issue, this could improve perf a bit

2022-07-07 03:09 UTC, ElectroJr commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +        public IReflectionManager ReflectionManager => _reflectionManager;
Actually, I just realised the write-function doesn't even get a dependency collection passed into it, so either way it would need to access ISerializationManager separately

2022-07-07 21:25 UTC, merged