Add entitylookup for components
space-wizards/RobustToolbox pull request #3065
Opened 2022-07-21 04:19 UTC by metalgearsloth

Technically entitylookup is now just "lookup" but changing it would be a pain.

I used the same API as entitylookup and it's kinda boilerplatey but don't know of an easier way to do it. The main advantage is it internally checks if it should just iterate every component directly or check the dynamic trees. This also means content has a consistent way to do component checks even if we change the internal implementation as right now people call the entitylookup methods and use their own entityquery.

Entitylookup is also pretty slow due to the hashsets everywhere but I'm mainly worried about API stability atm and we can optimise later (as PVS doesn't use this anymore it's pretty much just content calling it).

Fixes https://github.com/space-wizards/RobustToolbox/issues/2952

2022-07-29 03:40 UTC, ElectroJr requested changes

2022-07-29 03:40 UTC, ElectroJr commented on Robust.Shared/GameObjects/Systems/EntityLookupSystem.ComponentQueries.cs
> +                intersecting.Add(comp);
This doesn't respect `LookupFlags.Contained`. If the contained flag is not set, this should get the metadata & check the in-container flag. It should also check xform.Anchored & the anchored flag.

2022-08-06 04:55 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/EntityLookupSystem.ComponentQueries.cs
> +                intersecting.Add(comp);
For containers it's similar to the entitylookup side but I added the anchored check so not sure if both should change for that.

2022-09-10 21:58 UTC, ElectroJr approved these changes

2022-09-13 09:52 UTC, merged