Fix CustomHashSetSerializer bug
space-wizards/RobustToolbox pull request #3087
Opened 2022-07-28 20:11 UTC by ElectroJr

Fixes a bug in the CustomHashSetSerializer's copy function that is currently causing test failures for #3084.

Also fixes what I think are two other bugs in copying, where a failed attempt to copy will instead return a reference to the source, rather than actually copying.

2022-07-29 00:32 UTC, metalgearsloth commented
@PaulRitter

2022-07-30 12:00 UTC, PaulRitter requested changes
god i really just need to convert the copy api to use ref

2022-07-30 12:00 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> -                return source;
no! source might have a value but target may not. but what i just realized: this should not return source, this should create a copy of source if target is null. oops!

2022-07-30 12:00 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +                return null;
same here

2022-08-04 00:27 UTC, ElectroJr commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> -                return source;
For the first once, instance I guess I should just re-use `CreateCopy()` to create a copy of the source.

But I'm not sure what to do with `CopyWithTypeSerializer()`, because type serializers don't currently support copying into a null target. I guess I can just hope it has a parameterless constructor and make it use the same `CreateCopy()` function for now (effectively ignoring the "with type serializer" aspect). But I think the correct fix is to allow custom type serializers to be able copy into null (or alternatively: make them provide a constructor and just copy into a newly created object).

But that's probably out of scope for this PR. So unless there's something else that should be done, I'll just use `CreateCopy()` for both and slap a //TODO onto it for now?

2022-08-08 16:05 UTC, PaulRitter approved these changes

2022-08-08 16:05 UTC, PaulRitter commented on Robust.Shared/Serialization/Manager/SerializationManager.cs
> +            // TODO should this respect _copyByRefRegistrations? Or should the type serializer be allowed to override this?
it should be allowed to override

2022-08-08 16:05 UTC, merged