Add element picker to dev window
space-wizards/RobustToolbox pull request #3180
Opened 2022-08-23 17:10 UTC by DrSmugleaf

https://user-images.githubusercontent.com/10968691/186221670-8a116ddd-0524-42a4-a092-81ab4b6a295e.mp4

technology

2022-08-23 19:37 UTC, Visne commented
Wtf how

2022-08-26 08:02 UTC, metalgearsloth approved these changes

2022-08-26 08:02 UTC, metalgearsloth commented
we have the technology

2022-08-26 20:27 UTC, PJB3005 requested changes

2022-08-26 20:27 UTC, PJB3005 commented on Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
> +            _input.UIKeyBindStateChanged += OnUIKeyBindStateChanged;
You're not removing these subscriptions anywhere. Add them in `EnteredTree` and remove them in `ExitedTree`.

2022-08-26 20:27 UTC, PJB3005 commented on Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
> +        private bool OnUIKeyBindStateChanged(BoundKeyEventArgs arg)
Do you not want to check which UI key fired? Limit it to click?

2022-08-31 23:30 UTC, DrSmugleaf commented on Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
> +            _input.UIKeyBindStateChanged += OnUIKeyBindStateChanged;
Fixed in [`5a35f94` (#3180)](https://github.com/space-wizards/RobustToolbox/pull/3180/commits/5a35f9446949ea6dc693d8e48a7220fbfe6d3d07)

2022-08-31 23:30 UTC, DrSmugleaf commented on Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
> +        private bool OnUIKeyBindStateChanged(BoundKeyEventArgs arg)
Fixed in [`5a35f94` (#3180)](https://github.com/space-wizards/RobustToolbox/pull/3180/commits/5a35f9446949ea6dc693d8e48a7220fbfe6d3d07)

2022-08-31 23:30 UTC, DrSmugleaf commented on Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
> +        private bool OnUIKeyBindStateChanged(BoundKeyEventArgs arg)
Fixed in [`5a35f94` (#3180)](https://github.com/space-wizards/RobustToolbox/pull/3180/commits/5a35f9446949ea6dc693d8e48a7220fbfe6d3d07)

2022-09-01 04:18 UTC, merged