Allow startup to continue if prototype watching fails
space-wizards/RobustToolbox pull request #3273
Opened 2022-09-23 01:14 UTC by SpaceManiac

Example:
```
[ERRO] root: Watching resources in path /d/archives/projects/ss14/space-station-14/Resources/Prototypes threw an exception:
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Robust.Client.Prototypes.ClientPrototypeManager.WatchResources() in /d/archives/projects/ss14/space-station-14/RobustToolbox/Robust.Client/Prototypes/ClientPrototypeManager.cs:line 124
```

2022-09-25 16:39 UTC, PaulRitter requested changes

2022-09-25 16:39 UTC, PaulRitter commented on Robust.Client/Prototypes/ClientPrototypeManager.cs
>                  _watchers.Add(watcher);
ig this should also be in the try clause

2022-09-25 18:22 UTC, SpaceManiac commented on Robust.Client/Prototypes/ClientPrototypeManager.cs
>                  _watchers.Add(watcher);
Makes sense thinking about it.

2022-09-26 14:17 UTC, PaulRitter approved these changes

2022-09-26 14:18 UTC, merged