Localize commands
space-wizards/RobustToolbox pull request #3374
Opened 2022-10-25 04:46 UTC by Ygg01

A continuation of https://github.com/space-wizards/RobustToolbox/pull/2331

Just without too much complication. Localizes most commands.

Basically standardizes the `IConsoleCommand` localization to `cmd-{Command}-{help/desc}`. And reapplies to most commands.

Part of https://github.com/space-wizards/space-station-14/issues/5543

2022-10-25 04:58 UTC, Ygg01 commented
Hrm, why is entityQuery failing on transform?

2022-10-27 22:24 UTC, PJB3005 commented on Resources/Locale/en-US/commands.ftl
> +# Client site commands
```suggestion
# Client-side commands
```

2022-10-27 22:25 UTC, PJB3005 commented on Robust.Shared/Console/LocalizedCommands.cs
> +    public string Help => _loc.TryGetString($"cmd-{Command}-help", out var val) ? val : "";
These should stay virtual IMO. Some commands dynamically build the help body up from enum members etc.

2022-10-28 03:22 UTC, Ygg01 commented on Robust.Shared/Console/LocalizedCommands.cs
> +    public string Help => _loc.TryGetString($"cmd-{Command}-help", out var val) ? val : "";
Thanks, that solved some problems with VV Commands.

Here is when I point SS14/RobustToolbox to this branch.
![Content Client_pa77AcGAa6](https://user-images.githubusercontent.com/1146204/198494880-e52c21e7-aea8-47a5-ba16-8c9a0f8e7555.png)

2022-11-03 23:35 UTC, ElectroJr requested changes
This currently breaks completion hints (e.g., see `/help`'s lack of completions)

2022-11-05 16:00 UTC, merged