speeds up gamestate a bit by optimizing collection usage
space-wizards/RobustToolbox pull request #3396
Opened 2022-10-28 11:16 UTC by PaulRitter

way too many hashsets, had to cut the usage down a bit. will reduce allocations as well as general runtime due to less overhead

2022-10-28 17:00 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +                        continue;
This check has to be done after first creating new entities, to ensure that things like newly spawned bullets properly lerp during the first tick. Otherwise they weirdly stay in place before starting to move.

2022-10-28 17:01 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
>                  _prof.WriteValue("Count", ProfData.Int32(toCreate.Count));
The actual entity creation profile block is empty now? Given that if any entities are being created, then the majority of the `foreach (var es in curSpan)` loop will be spent on entity creation, I guess this profiler group can just be moved around that for loop?

Having entity creation be separated out in the client profiler isn't really necessary, its just nice to be able to see the breakdown for what's causing stuttering.

2022-10-28 17:13 UTC, PaulRitter commented on Robust.Client/GameStates/ClientGameStateManager.cs
>                  _prof.WriteValue("Count", ProfData.Int32(toCreate.Count));
well yeah, the logic was moved up ahead the function but the profiling data still needs to get logged, hence this block here. this block isn't "empty"

2022-10-28 17:15 UTC, PaulRitter commented on Robust.Client/GameStates/ClientGameStateManager.cs
>                  _prof.WriteValue("Count", ProfData.Int32(toCreate.Count));
nvm, i was wrong. will fix

2022-10-28 17:17 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
>                  _prof.WriteValue("Count", ProfData.Int32(toCreate.Count));
For example, entity creation now shows up as "0" when its really the majority of the time spent in applying state:
![state data](https://user-images.githubusercontent.com/60421075/198694954-b500029d-0068-42e9-9906-90eefe1f6843.png)

Also oh boy the lookup changes degraded detach to null performance a smidgen

2022-10-28 17:23 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +
AFAIK, this loop will `continue` most of the time, so AFAIK `new Dictionary(nextState.EntityStates.Span.Length)` significantly overestimates the size of the dict most of the time, but I have no idea if that's actually all that important.

2022-10-29 00:32 UTC, ElectroJr requested changes
Seems fine other than reordering the next-state getting to happen after ent creation, and either removing the ent creation profiler group or fixing it.

2023-01-21 02:54 UTC, closed without merging