removes beforeserialization hook
space-wizards/RobustToolbox pull request #3422
Opened 2022-10-31 15:51 UTC by PaulRitter

requires content pr

2022-10-31 22:56 UTC, ElectroJr approved these changes

2022-10-31 23:04 UTC, ElectroJr requested changes

2022-10-31 23:04 UTC, ElectroJr commented on Robust.Shared/Physics/FixturesComponent.cs
> -            if (IoCManager.Resolve<IEntityManager>().HasComponent<MapGridComponent>(Owner)) return;
Actually this bit is still needed to avoid writing the grid's fixtures to a map file.

2022-11-01 14:52 UTC, PaulRitter commented on Robust.Shared/Physics/FixturesComponent.cs
> -            if (IoCManager.Resolve<IEntityManager>().HasComponent<MapGridComponent>(Owner)) return;
should be fixed now

2022-11-03 01:50 UTC, merged