Expose more net serializer stuff to content
space-wizards/RobustToolbox pull request #3476
Opened 2022-11-13 23:34 UTC by ElectroJr

Changes some parts of `IRobustSerializer` and `IRobustMappedStringSerializer` from `internal` to `public` and adds some public methods to retrieve hashes. Or is there some reason they should be internal only? Main rationale is to make it easier for content to use `IRobustSerializer` to deserialize data.

Maybe `IRobustMappedStringSerializer` isn't meant to be used outside of engine networking, but its sort of required for things like replays that just re-use existing networked entity events.

See also #3475.

2022-11-16 19:53 UTC, PJB3005 requested changes

2022-11-16 19:53 UTC, PJB3005 commented on Robust.Shared/Serialization/IRobustMappedStringSerializer.cs
> +    public interface IRobustMappedStringSerializer
If you need something like `MappedStringsHash` you should make those properties specifically and nothing else. A lot of the functions you're making public like `Handshake` shouldn't ever be public either way.

2022-11-16 19:53 UTC, PJB3005 commented on Robust.UnitTesting/IntegrationMappedStringSerializer.cs
> +            throw new NotImplementedException();
Should this be `NotSupportedException()` instead?

2022-11-18 00:43 UTC, ElectroJr commented on Robust.UnitTesting/IntegrationMappedStringSerializer.cs
> +            throw new NotImplementedException();
yes

2022-11-18 01:44 UTC, ElectroJr commented
> If you need something like MappedStringsHash you should make those properties specifically and nothing else. A lot of the functions you're making public like Handshake shouldn't ever be public either way.

I've updated the PR so now:
- `IRobustMappedStringSerializer` and `MappedStringDict` stay internal
- `IRobustMappedStringSerializer` now has two internal functions to set and get the string mapping data.
- The public `IRobustSerializer` now has to methods for getting hashes & string mapping data.
- Changes `RobustSerializer` from public to internal & abstract
- Added an internal `ClientRobustSerializer` and public `IClientRobustSerializer` which provides a public function that enables string-mapping data to be directly set in single player games.
- Also adds an empty internal `ServerRobustSerializer`

2022-12-30 17:07 UTC, merged