Client-, shared-, and server-side ConfigurationManager
space-wizards/RobustToolbox pull request #3477
Opened 2022-11-14 00:41 UTC by ElectroJr

This splits ConfigurationManager into client and sever classes/interfaces. This is partly to reduce the number of _netManager.IsClient checks, and partly so that the client can check if `IBaseClient.RunLevel == ClientRunLevel.SinglePlayerGame` when trying to set "only server settable" cvars like tickrate.

2022-11-16 20:00 UTC, PJB3005 requested changes
Seems good, though `GetClientCVar` seems like a potential loss on the client: it could be useful for writing shared code and is sane to implement on both sides.

2022-11-16 20:00 UTC, PJB3005 commented on Robust.Client/Configuration/ClientNetConfigurationManager.cs
> +    public void ApplyClientNetVarChange(List<(string name, object value)> networkedVars, GameTick tick)
This shouldn't be public.

2022-11-18 00:35 UTC, ElectroJr commented on Robust.Client/Configuration/ClientNetConfigurationManager.cs
> +    public void ApplyClientNetVarChange(List<(string name, object value)> networkedVars, GameTick tick)
The reason I initially made this public instead of private was for replays, so that `ReceivedInitialNwVars` gets invoked properly, though looking at it further, maybe it doesn't actually need it?

Currently `ReceivedInitialNwVars` is only used by `BaseClient` after having connected to a server (which I guess makes sense). So as long as it never gets used by any other kind of set up that might be required for replays to work, I guess it can stay private?

2022-11-27 22:38 UTC, ElectroJr commented
This now also adds an optional argument to ignore normal cvar flags when setting. (again, useful when forcing server authoritative cvars in replays)

2022-12-30 17:04 UTC, merged