Adds basic delta state support
space-wizards/RobustToolbox pull request #3492
Opened 2022-11-16 05:27 UTC by ElectroJr

also makes the get-state event always include the player session data. Null now implies no client (e.g., replays).

2022-11-16 19:50 UTC, PJB3005 requested changes

2022-11-16 19:50 UTC, PJB3005 commented on Robust.Client/GameStates/GameStateProcessor.cs
> +                    }
This is not the place to do this. `GameStateProcessor` is very much a self-contained system solely concerned with shuffling component states around, it's not designed to call into the actual game state like this.

Doing this on actual entities is a no-go. It may be acceptable to figure out some way to wire up handling logic on systems, but it should be very much purely on the state, no looking at entity UIDs.

2022-11-18 02:29 UTC, ElectroJr commented on Robust.Client/GameStates/GameStateProcessor.cs
> +                    }
I've now changed this around so that the `IComponentDeltaState` interface provides an apply-state function, rather than raising this event.

2022-12-11 20:35 UTC, PaulRitter approved these changes

2022-12-11 20:36 UTC, merged