Adds a new `ResPath` struct that will replace `ResourcePath`
space-wizards/RobustToolbox pull request #3663
Opened 2023-01-06 02:13 UTC by Ygg01

Somewhat of a WIP. Wanted some feedback. ATM Serializers fail. Need to see about the details.

This relates to #2540

Needs a considerable breaking change.

2023-01-18 18:28 UTC, mirrorcult commented
if this PR isnt gonna be breaking should at least obsolete `ResourcePath`

2023-01-20 12:24 UTC, mirrorcult approved these changes
looks fine to me especially with the test but need benchmarks imo

2023-01-21 16:03 UTC, Ygg01 commented
Added Benchmarks and fix some issues using a custom enumerator.

```
|           Method |   N |        Mean |     Error |    StdDev |
|----------------- |---- |------------:|----------:|----------:|
|      ReadResPath |   1 |    349.3 ns |   6.78 ns |   9.05 ns |
|  ReadResPathFast |   1 |    186.7 ns |   3.75 ns |   5.14 ns |
| ReadResourcePath |   1 |    470.0 ns |   9.37 ns |  15.92 ns |
|      ReadResPath |  10 |  1,864.6 ns |  36.71 ns |  64.29 ns |
|  ReadResPathFast |  10 |    265.9 ns |   5.23 ns |   8.14 ns |
| ReadResourcePath |  10 |  2,572.3 ns |  50.37 ns |  51.73 ns |
|      ReadResPath | 100 | 17,050.7 ns | 332.89 ns | 444.40 ns |
|  ReadResPathFast | 100 |  1,075.6 ns |  21.23 ns |  34.87 ns |
| ReadResourcePath | 100 | 23,655.3 ns | 351.22 ns | 328.53 ns |
```

2023-01-21 16:12 UTC, AJCM-git requested changes

2023-01-21 16:12 UTC, AJCM-git commented on Robust.Shared/Utility/ResourcePath.cs
>      public sealed class ResourcePath : IEquatable<ResourcePath>
Obsolete the public fields/methods in the class with a message mentioning what their replacement in ResPath is

2023-01-21 16:37 UTC, Ygg01 commented on Robust.Shared/Utility/ResourcePath.cs
>      public sealed class ResourcePath : IEquatable<ResourcePath>
It's the same API, albeit constructors are different.

2023-01-23 15:03 UTC, Ygg01 commented
Removed branching from fast constructor. Added type serializer.

Speed is now: 
|                     Method |   N |           Mean |       Error |      StdDev |
|--------------------------- |---- |---------------:|------------:|------------:|
| CreateWithSeparatorResPath |   1 |    110.2079 ns |   1.2814 ns |   1.1986 ns |
|    CreateUnsafePathResPath |   1 |      0.0000 ns |   0.0000 ns |   0.0000 ns |
|         CreateResourcePath |   1 |    246.2445 ns |   4.7017 ns |   4.3980 ns |
| CreateWithSeparatorResPath |  10 |  1,041.1877 ns |   7.1897 ns |   6.7253 ns |
|    CreateUnsafePathResPath |  10 |      1.9065 ns |   0.0072 ns |   0.0068 ns |
|         CreateResourcePath |  10 |  1,296.2405 ns |   7.3435 ns |   6.5098 ns |
| CreateWithSeparatorResPath | 100 | 10,423.0894 ns |  61.4379 ns |  57.4691 ns |
|    CreateUnsafePathResPath | 100 |     24.3702 ns |   0.3385 ns |   0.3167 ns |
|         CreateResourcePath | 100 | 12,240.8429 ns | 234.7124 ns | 270.2951 ns |

However, it will allocate a bunch:
`ResourcePath`:
![H1GdXWtGB6](https://user-images.githubusercontent.com/1146204/214072342-c274ddd6-ed86-491d-b4f1-c667e5ca45de.png)
![U7RyablEqC](https://user-images.githubusercontent.com/1146204/214072349-27a148b2-3e77-48ee-937e-57ec322a338a.png)

`ResPath`:
![mjKsk83NLA](https://user-images.githubusercontent.com/1146204/214072410-6452df17-6cb3-49a6-895b-cb280900b912.png)
![ra8OPiuwlj](https://user-images.githubusercontent.com/1146204/214072417-6549173e-0dbf-4b31-acfc-c26e05d3e73e.png)

Some pooling or just using Refs could be a workable solution. This is why I made factory methods rather than constructors.

2023-01-29 06:00 UTC, AlexMorgan3817 requested changes

2023-01-29 06:00 UTC, AlexMorgan3817 commented on Robust.Benchmarks/Utility/ResourcePathBench.cs
> +    public int N;
Bad naming and no `///<summary>`, try to rename to something that at least hints on explanation of what is it

2023-01-29 06:00 UTC, AlexMorgan3817 commented on Robust.Shared/Utility/ResPath.cs
> +        if (TryRelativeTo(basePath, out var relative)) return relative.Value;
```suggestion
        if (TryRelativeTo(basePath, out var relative))
                return relative.Value;
```

2023-01-29 06:00 UTC, AlexMorgan3817 commented on Robust.Shared/Utility/ResPath.cs
> +        if (IsRelative) return this;
```suggestion
        if (IsRelative)
                return this;
```

2023-01-29 06:00 UTC, AlexMorgan3817 commented on Robust.Shared/Utility/ResPath.cs
> +        if (newSeparator is "." or "\0") throw new ArgumentException("New separator can't be `.` or `NULL`");
```suggestion
        if (newSeparator is "." or "\0")
                throw new ArgumentException("New separator can't be `.` or `NULL`");
```
Too long line, better to linebreak

2023-01-29 06:01 UTC, AlexMorgan3817 commented
More of formatting. And... Pendulum is based

2023-01-29 06:04 UTC, AlexMorgan3817 commented on Robust.Shared/Utility/ResPath.cs
> +    public const char SystemSeparator = '/';
```suggestion
    public const char SystemSeparator = '/';

```

2023-01-29 06:11 UTC, DrSmugleaf commented on Robust.Benchmarks/Utility/ResourcePathBench.cs
> +    public int N;
N is commonly used for the amount of iterations in a benchmark
https://github.com/dotnet/BenchmarkDotNet

2023-01-29 06:31 UTC, AlexMorgan3817 commented on Robust.Benchmarks/Utility/ResourcePathBench.cs
> +    public int N;
> N is commonly used for the amount of iterations in a benchmark https://github.com/dotnet/BenchmarkDotNet

Yes, but what is iterations, do you just iterate integer numbers? :\

2023-01-29 06:33 UTC, AlexMorgan3817 commented on Robust.Benchmarks/Utility/ResourcePathBench.cs
> +    public int N;
Okay, anyway, maybe i am just not experienced in C# enough

2023-01-29 11:09 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +    public const char SystemSeparator = '/';
I don't see any changes here. I added a new line after block.

2023-01-29 13:53 UTC, AlexMorgan3817 commented on Robust.Shared/Utility/ResPath.cs
>  #endif
```suggestion
    public const char SystemSeparator = '/';

    public const string SystemSeparatorStr = "/";
#endif
```
As you wish

2023-02-01 01:26 UTC, metalgearsloth requested changes
PJB should also take a look.

2023-02-01 01:26 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +    }
Is CreateWIthSeparator an accurate name anymore?

2023-02-01 01:26 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +    }
Should be a struct enumerator.

2023-02-01 01:26 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +        var segments = CanonPath.Split(Separator).ToArray();
Is the ToArray needed?

2023-02-01 01:26 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +            }
Is this supposed to be in the loop?

2023-02-01 01:26 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +        var segments = new List<string>();
ValueList, should also be constructed after the if check.

2023-02-01 01:52 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +    }
It's a placeholder name for constructor taking path with arbitrary separators. E.g. `a|b|c` and separator `|` result in `/a/b/c` `CanonPath`.

2023-02-01 13:02 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +            }
Honestly, it's verbatim of `ResourcePath` method, I really had no luck figuring it out at the time. That said, I maybe could try and refactor it, possibly remove the array.

2023-02-01 14:48 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +    }
Meet you halfway and make it return `string[]` it won't break interfaces.

2023-02-25 10:24 UTC, PJB3005 requested changes
Much of the complexity kept from `ResourcePath` isn't necessary and needs to be removed. The maintainer meeting for this was a year ago but we agreed all the complexities with "regular filesystem" semantics like `.` and `..` traversal should just be axed. Really the only thing you need at most is like, concatenation taking root vs relative into account.

2023-02-25 11:54 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +    }
Removed per PJB comment.

2023-02-25 11:55 UTC, Ygg01 commented on Robust.Shared/Utility/ResPath.cs
> +    }
Removed per PJB's comment.

2023-04-09 01:05 UTC, metalgearsloth approved these changes

2023-04-09 01:05 UTC, metalgearsloth commented on Robust.Shared/Serialization/TypeSerializers/Implementations/ResPathSerializer.cs
> +        path = path.ToRootedPath();
Is keeping /Textures support worth it.

2023-04-09 01:05 UTC, metalgearsloth commented on Robust.Shared/Utility/ResPath.cs
> +    public static readonly ResPath Empty = new("");
doc summary looks copied?

2023-04-09 01:05 UTC, metalgearsloth commented on Robust.Shared/Utility/ResourcePath.cs
> +        use {nameof(ResPath)} but only if '/' is the separator")]
Comment looks doubled? Should just say to use ResPath instead.

2023-04-09 02:32 UTC, Ygg01 commented on Robust.Shared/Serialization/TypeSerializers/Implementations/ResPathSerializer.cs
> +        path = path.ToRootedPath();
Shrug, no idea; I copied to make sure serialization worked in-game (when I briefly replaced `ResourcePath` with `ResPath`).

https://github.com/space-wizards/RobustToolbox/blob/40c8a3ccf78bd3f9b8f9554242e3bf373c968f89/Robust.Shared/Serialization/TypeSerializers/Implementations/ResourcePathSerializer.cs#L40-L43

2023-04-11 01:18 UTC, merged