Rich Text refactor
space-wizards/RobustToolbox pull request #3742
Opened 2023-01-28 20:48 UTC by juliangiebel

This PR replaces the current FormatedText implementation with a more flexible one that supports adding new tags by implementing the `IMarkupTag` interface.

The new parser parses the markup into a list of `MarkupTag` nodes.

It's more flexible supports the following features:
- Arbitrary tag names
- One parameter parsed into a nodes `Value` field
- An arbitrary number of attributes which are put into a nodes `Attributes` dictionary
- Escaping reserved characters using backslashes
- Self closing tags
- String, long and color parameters

New tags are created by implementing the `IMarkupTag` interface which contains methods for modifying the context for rendering the text (currently only color and font) and supplying additional text.

2023-01-31 11:03 UTC, juliangiebel commented
![grafik](https://user-images.githubusercontent.com/8915246/215743109-f5c29c36-e873-4499-989e-d5456dfb380f.png)

2023-02-08 06:08 UTC, moonheart08 requested changes
Almost all looks good.

2023-02-08 06:08 UTC, moonheart08 commented on Robust.Client/UserInterface/RichText/ItalicTag.cs
> +        var font = FontTag.CreateFont(context.Font, node, _resourceCache, "/Fonts/NotoSans/NotoSans-Italic.ttf");
Don't hardcode this. Need to figure out a better way to grab the required font from styles. @PJB3005 as i think you're the only one who'd know how.

2023-02-08 06:08 UTC, moonheart08 commented on Robust.Client/UserInterface/RichText/BoldTag.cs
> +        var font = FontTag.CreateFont(context.Font, node, _resourceCache, "/Fonts/NotoSans/NotoSans-Bold.ttf");
see italic

2023-02-08 06:08 UTC, moonheart08 commented on Robust.Client/UserInterface/RichText/FontTag.cs
> +        string fontPath = node.Value.StringValue ?? "/Fonts/NotoSans/NotoSans.ttf";
see italic

2023-02-15 19:40 UTC, juliangiebel commented on Robust.Client/UserInterface/RichText/ItalicTag.cs
> +        var font = FontTag.CreateFont(context.Font, node, _resourceCache, "/Fonts/NotoSans/NotoSans-Italic.ttf");
I implemented the `FontPrototype` which contains the fonts resource path. I hope that's decent enough as I still had to hardcode the prototype Ids

2023-02-15 22:41 UTC, merged