Move client GameState management
space-wizards/RobustToolbox pull request #375
Opened 2017-08-24 14:47 UTC by wixoaGit

Moves the client's GameState message handling to GameStateManager, and creates MsgFullState and MsgUpdateState.

2017-08-24 15:30 UTC, PJB3005 requested changes

2017-08-24 15:30 UTC, PJB3005 commented on SS14.Client/GameStates/GameStateManager.cs
> +        public GameState CurrentState
Use anonymous functions here for simple getters:
```cs
public GameState CurrentState => GameStates.Values.Last();
```

That said, doesn't this make performance a lot worse, *and* doesn't the C# documentation say that the order of dictionary iteration is undefined?

2017-08-24 15:30 UTC, PJB3005 commented on SS14.Client/GameStates/GameStateManager.cs
> +            IClientNetManager networkManager = IoCManager.Resolve<IClientNetManager>();
Because this is an IoC-managed class, you can store the network manager in a field as dependency like so:

```cs
[Dependency]
private readonly IClientNetManager networkManager;
``` 

In fact, do that for all IoC resolutions in this class.

2017-08-25 19:21 UTC, PJB3005 approved these changes

2017-08-25 19:21 UTC, merged

2017-08-26 02:38 UTC, clusterfack commented
This causes the client to get stuck in a neverending memory state patching loop if you pause and unpause the client process