Fix PanelContainer ArrangeOverride()
space-wizards/RobustToolbox pull request #3800
Opened 2023-02-22 02:39 UTC by ElectroJr

Currently the PanelContainer's `MeasureOverride()` treat style box margins/padding as physical pixels (i.e., not scaled by `UiScale`), while the `ArrangeOverride()` effectively treats them as virtual pixels. This PR changes the arrange method so that it also treats them like physical pixels, which fixes some UI layout bugs (e.g., scroll bar visibility in context menu pop-ups).

2023-02-22 11:37 UTC, PJB3005 requested changes
1. You would need to change `MeasureOverride()` as well.
2. I'm not sure it makes much sense to fix this without fixing the rest of the StyleBox rendering code to be properly scaled.

2023-02-22 23:30 UTC, ElectroJr commented
> 1. You would need to change MeasureOverride() as well.

AFAIK this change should make Arrange consistent with the current measure, they are currently inconsistent disagree.

> 2. I'm not sure it makes much sense to fix this without fixing the rest of the StyleBox rendering code to be properly scaled.

If there's no real reason why they should even be using physical pixel's I'll just open a PR to make them use virtual pixels instead if I can get it to work easily with current style boxes.

2023-02-23 09:58 UTC, PJB3005 commented
> AFAIK this change should make Arrange consistent with the current measure, they are currently inconsistent on master.

Ah wait, I see, you're right.

> If there's no real reason why they should even be using physical pixel's I'll just open a PR to make them use virtual pixels instead if I can get it to work easily with current style boxes.

I think when I wrote the UI scaling system I figured "style boxes don't scale" would be better than "style boxes scale blurrily" but please punch that past version of me if you meet them so.

2023-05-15 00:45 UTC, AJCM-git commented
@ElectroJr you coming back to this?

2023-05-15 01:30 UTC, ElectroJr commented
> @ElectroJr you coming back to this?

Yes, but it'll probably require starting from scratch anyways, so may as well close this for now

2023-05-15 01:30 UTC, closed without merging