Improve Discord Rich Presence
space-wizards/RobustToolbox pull request #3816
Opened 2023-03-02 21:30 UTC by ficcialfaint

**This PR is necessary - space-wizards/space-station-14#14350**

### What does it change?
- Removes the second "In Main Menu" string
- Adds player counter instead of only max players (now it looks like **Players: 2/10**)
- You can now change the text shown in Rich Presence without changing the engine (Localization support)
- Makes the logo primary image when in lobby
- Makes Discord RPC automatically update when a player joins the server
### Media
![image](https://user-images.githubusercontent.com/46868845/220157741-e215bd30-0320-470c-ac21-97f919f1a94b.png)
![image](https://user-images.githubusercontent.com/46868845/220157749-c871053d-5b24-46de-ab96-17d1f9a52acd.png)

2023-03-12 13:50 UTC, AJCM-git requested changes
i dont see default files for the new ftl strings

2023-03-12 13:50 UTC, AJCM-git commented on Robust.Client/Utility/DiscordRichPresence.cs
> +            };
didnt this used to also have Details and SmallImageKey

2023-03-12 13:53 UTC, ficcialfaint commented on Robust.Client/Utility/DiscordRichPresence.cs
> +            };
it is, but in my opinion there is no need in additional "in main menu" string
about the second image while in main menu: i just don't like that in main menu rich presence and on server look almost the same, so i changed it a bit 
pretty strange logic ik lol

2023-03-12 13:54 UTC, ficcialfaint commented
> i dont see default files for the new ftl strings

you mean this space-wizards/space-station-14#14350 ?

2023-03-12 14:16 UTC, metalgearsloth commented
> > i dont see default files for the new ftl strings
> 
> you mean this [space-wizards/space-station-14#14350](https://github.com/space-wizards/space-station-14/pull/14350) ?

This should be on engine.

2023-03-12 16:17 UTC, ficcialfaint commented
> > > i dont see default files for the new ftl strings
> 
> > 
> 
> > you mean this [space-wizards/space-station-14#14350](https://github.com/space-wizards/space-station-14/pull/14350) ?
> 
> 
> 
> This should be on engine.

done

2023-03-25 23:31 UTC, mirrorcult requested changes
is the PR linked in the desc still required for anything? its closed

2023-03-25 23:31 UTC, mirrorcult commented on Resources/Locale/en-US/discordRPC.ftl
> +discord-rpc-character = Character: {$username}
this isnt their character name, is it? pretty sure this is just their username, so it should be called something like that instead

2023-03-25 23:33 UTC, ficcialfaint commented
> is the PR linked in the desc still required for anything? its closed

Well, seems like it isn't since the default lines are already in the engine. I'll edit it

2023-03-25 23:39 UTC, ficcialfaint commented on Resources/Locale/en-US/discordRPC.ftl
> +discord-rpc-character = Character: {$username}
Yea, it's a username, I dunno why it's called Character tho. Haven't touched it, leaved how it was. Do I change it?

2023-03-25 23:41 UTC, mirrorcult commented on Resources/Locale/en-US/discordRPC.ftl
> +discord-rpc-character = Character: {$username}
i'd say change it

2023-03-25 23:55 UTC, ficcialfaint commented on Resources/Locale/en-US/discordRPC.ftl
> +discord-rpc-character = Character: {$username}
done

2023-03-25 23:58 UTC, mirrorcult approved these changes

2023-03-25 23:58 UTC, merged

2023-03-25 23:59 UTC, ficcialfaint commented
Thanks ^.^