Feat/exposure nightvision
space-wizards/RobustToolbox pull request #4106
Opened 2023-06-03 01:11 UTC by tom-leys

- Add Exposure to Eye which scales all lighting range and intensity. 
- High Exposure scales NightVision which creates a new pointlight centred on the player.
- Each frame, lighting brightness is measured in a small square near the player, this sampled brightness is written back into Eye for client code to use to adjust exposure
- Point lights easier to add in the lighting pass, since they rely on a simpler class than PointLightComponent
- Light measuring code might have a performance impact since we're reading a RenderTexture from the CPU. It is not noticable on my system in debug builds.
- Store texture format data in Clyde Textures
- GetPixel now works on float textures
- Engine changes alone don't add HDR exposure changes. You'll see no changes until SS14 client changes are also merged.

2023-06-03 05:55 UTC, ElectroJr commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +            var rangeMul = state.exposure * 0.2f + 0.8f;
if you want exposure to modify the range you also need to update the lights bounding boxes to account for tha. I.e., put an upper bound on exposure and use that for the bounds, otherwise you'd need to constantly update the bounds of all lights as exposure changes (+ having a different tree per eye). Alternatively, just don't scale the range unless its actually necessary.

2023-06-03 08:37 UTC, tom-leys commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +            var rangeMul = state.exposure * 0.2f + 0.8f;
1. I just expand the AABB that I pass into the tree as a query, which is much cheaper but equilivent to increasing the range of all lights in the tree. I over-expand the AABB and then rely on the second range filter here.
2. Note this is adjusting the range of a COPY of the light data, it's not modifying the PointLightComponent itself.

2023-06-03 08:39 UTC, tom-leys commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +                    bounds = bounds.Enlarged(5.0f * exposure);
@ElectroJr Here's my conservative code that increases the AABB size quite a lot (probably too much now actually) to include more lights as exposure increases.

Expanding AABB size by X is like increasing the radius of all lights in the tree by X.

2023-06-04 05:12 UTC, moonheart08 commented
- NightVision has zero business being in engine, allow content to supply non-entity lights instead
- AutoExposure also has no business being in engine, allow content to preprocess the to-be-rendered-lights list instead.

2023-06-04 19:57 UTC, tom-leys commented
> * NightVision has zero business being in engine, allow content to supply non-entity lights instead

I think you're right on this. "NightVision" here is very game specific, though it's kind of a scaling vignette?

Perhaps, though I'm unsure how to accomplish that. Some sort of callback on LightManager or Eye?

>     * AutoExposure also has no business being in engine, allow content to preprocess the to-be-rendered-lights list instead.

Being able to scale the power of the lighting system is a powerful feature. The mathematically best way to do that is to scale the lights (scaling the buffer directly loses resolution).

If you increase a light's power, you need to increase its range by sqrt(increase) because light diminishes to the sqrt of the power.

Having a callback that processes the lights seems complex and expensive, since any changes it makes can affect the filtering. It could be done, but I think it would be nicer to keep exposure specifically in-engine.

> 
>     * Scaling non shadow casting lights is no beuno.

They will look unnatural if we don't scale them but increase their power. I guess you're concerned that they will bleed through walls? Perhaps if the number of shadow-casting lights is low, some non-shadow casting lights gain shadows? 

Personally if I was a content author I'd want a powerful lighting system in the engine, but I'd appreciate the choice about how the exposure changed.

2023-06-05 01:51 UTC, tom-leys commented
I've moved AutoExposure and NightVision into client code.

Eye.Exposure is still in, I argue that it has good business being in the lighting logic. If you really really hate dynamic exposure I guess we could do a post process clientside, seems ugly to me.

I'm not sure what to do with local clientside lighting, probably a list of lights in screenspace or worldspace in Eye? In the meantime I commented out the additional light.

2023-06-11 18:10 UTC, PJB3005 requested changes
You need to update the sort calls on line ~640, you missed them because `Array.Sort()` sucks.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
> +    public struct PointLight
This struct is only used by Clyde. It should be in `Clyde.LightRendering` and be private.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
> +        }
These aren't used.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/Graphics/ClientEye/IEye.cs
> +        public bool DrawFov { get; set; }
Interface elements are by default `public`, you don't need to change this.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +            light.Radius = Math.Min(20.0f, light.Radius * rangeMul);
Make this a constant so it stands out more.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +                    bounds = bounds.Enlarged(5.0f * exposure);
Pull these constants out too so they stand out better.

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Textures.cs
> +            public Color MeasureBrightness(int x, int y, int width, int height)
This implementation is not suitable and will ruin the game's performance. You're effectively having the CPU do nothing while the GPU finishes rendering, rather than allowing them to run properly asynchronously.

You're going to need to replicate what the game does for screenshots: copy the pixels into a Pixel Buffer Object, fence it, and then map the buffer on a later frame when the copy is done. This inherently makes the operation asynchronous and yes this means you'll have to accept that the results will come in on a bit of a delay.

(If you're wondering about `GetPixel()`... the code for that one sucks and I didn't review it at the time. It's not used by SS14 IIRC, only OpenDream)

2023-06-11 18:10 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Textures.cs
> +            public Color MeasureBrightness(int x, int y, int width, int height)
Also move this code into a function on the `Clyde` class itself rather than on `ClydeTexture`.

2023-06-11 20:39 UTC, tom-leys commented on Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
> +        }
Yeah, it was a constructor added for the nightvision lighting. We need a way to inject game-specific clientside point lights into the renderer (not in this PR yet)

2023-06-11 20:41 UTC, tom-leys commented on Robust.Client/Graphics/Clyde/Clyde.Textures.cs
> +            public Color MeasureBrightness(int x, int y, int width, int height)
Thanks for the pointer on where to look for an example. Async is indeed ideal - I was also concerned about the performance impact and cpu wait nature of this operation but how to fix it was beyond me.

2023-06-11 20:42 UTC, tom-leys commented
This is a draft until I've resolved issues raised by the recent review.

2023-08-03 05:13 UTC, tom-leys commented
I've now moved the light exposure code into an async process in `Clyde.LightingSample.cs`

2024-02-01 09:16 UTC, metalgearsloth commented
I only skimmed it but wouldn't you async call it? Looks like the methods are still unsafe / void.

2024-02-11 02:16 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +                    bounds = bounds.Enlarged(5.0f * exposure);
Does this even work with PVS? The range is still just going to be 12.5

2024-02-11 05:59 UTC, deathride58 commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +    gl_FragColor = zAdjustResult(COLOR * VtxModulate * vec4(lightSample, 1.0) + bloom);
It'd probably be far saner to do the tonemapping here in a postprocess pass (whether it's an overlay in content or something more sophisticated in engine), rather than having the tonemapping be a part of the base default fragment shader. While this is fine for most shaders currently in SS14, this will have a pretty significant impact on artistic flexibility in the future, particularly when it comes to object shaders that need to sample the underlying image, but have good reason to not be using raw.

Generally, it's ideal for HDR conversion to sRGB to be handled as late into a pipeline as feasible, as this provides the finest level of artistic control, among other positives.

2024-02-11 07:11 UTC, tom-leys commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +    gl_FragColor = zAdjustResult(COLOR * VtxModulate * vec4(lightSample, 1.0) + bloom);
While this is true, I wasn't comfortable changing the RGB render buffers to be HDR or adding a post-process pass to this. 

The key here is if the sprite shows a completely black pixel but we overbrighten it, does it remain black? I've pushed it to white regardless if there is enough lighting.

2024-02-11 07:23 UTC, tom-leys commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +    gl_FragColor = zAdjustResult(COLOR * VtxModulate * vec4(lightSample, 1.0) + bloom);
Please bear in mind that I don't feel comfortable changing the whole renderer. I also doubt that my PR would ever be merged if I DID substantially change the renderer more than I have already.

A small hack is more likely to get merged, could always refactor it and make it more flexible in a later PR.

2024-02-25 04:10 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +    gl_FragColor = zAdjustResult(COLOR * VtxModulate * vec4(lightSample, 1.0) + bloom);
Talked with bhijn and this is still outstanding.

2024-04-21 18:52 UTC, Stokes52 commented
This is really amazing, and I hope that this makes it into the game. Excellent, excellent work!

2024-06-21 02:05 UTC, ElectroJr commented
I'm starting to get back into looking at light rendering stuff, mostly to try increase performance. While my motivation lasts I'll also try get around to looking at this PR again. But in the meantime, it might be best to split off the `struct PointLight` related changes into a separate PR, which would also help reduce conflicts.

2024-08-15 20:04 UTC, dragonryan06 commented
I don't know much about the engine but from a more player-facing side, this PR would be amazing as it would allow for different creatures to have different eye settings, I did a lot of digging and as-is there isn't really a way for SS14 rats to be able to see in dark maintenance tunnels without allowing them to hold flashlights or disabling the lighting engine entirely, which is quite unfortunate, but this PR would look even cooler than the hacky stuff I tried!

I also just think the fake-hdr effect it gives off is pretty neat, though there would need to be a cap on how bright the bloom can get because those flares are a little out of control

2024-09-03 20:46 UTC, ShatteredSwords commented
Had a friend say this PR could make it so Diona could feed off light. That's a really cool change.

2024-09-04 21:14 UTC, tom-leys commented
> Had a friend say this PR could make it so Diona could feed off light. That's a really cool change.

Since the lighting calculations are currently clientside this actually wouldn't be compatible with non-visual gameplay changes. It would be possible (but hard) to do enough calculations on the server to add the functionality you want - just not with this PR.

2024-10-08 03:27 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +    gl_FragColor = zAdjustResult(COLOR * VtxModulate * vec4(lightSample, 1.0) + bloom);
Having looked at this I'm also not really sure why you can't just use an overlay to adjust the rendertarget for tonemapping instead of baking it into the base shader?

2025-04-27 06:47 UTC, K-Dynamic commented
Are you still working on this

2025-04-27 07:06 UTC, tom-leys commented
No, and I have no plans to work on it in the future.

2025-05-02 04:34 UTC, metalgearsloth commented
> Had a friend say this PR could make it so Diona could feed off light. That's a really cool change.

That would be https://github.com/space-wizards/RobustToolbox/pull/5574

2025-05-02 04:34 UTC, closed without merging