Network entity ids
space-wizards/RobustToolbox pull request #4252
Opened 2023-08-10 01:58 UTC by metalgearsloth

Resolves https://github.com/space-wizards/RobustToolbox/issues/4251 but going to take me a while to get something going.

2023-08-10 04:50 UTC, ElectroJr commented
> Add some kind of safeguard (analyser, netserializable, idk?) to prevent EntityUids being used in comp states / elsewhere.

You could just remove the [NetSerializable] attribute. Though IIRC that doesn't lead to very user friendly errors if somebody does try to use them.

2023-08-10 04:52 UTC, ElectroJr commented on Robust.Client/Replays/ReplayRecordingManager.cs
> +            // TODO: Do we even care about netentity for replays?
Replays do still need to distinguish between "server-side" and client-side entities. So if the net id is going to replace the old is-client-side check, then yeah

2023-08-25 04:06 UTC, ElectroJr requested changes
This is only a partial review, I still intend to review the rest + the content PR

![chrome_vTNmdQGMuX](https://github.com/space-wizards/RobustToolbox/assets/60421075/1aaab40a-462f-4b8f-8216-73d1297608a8)

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
This should also be the setter method for the metadata component's field. This should also be a `Add()` or `TryAdd()` so it logs an error on duplicate ids.

Also, would it be worth keeping an inverse dictionary? or would uid -> component-> netId eventually be faster by the magic of non-dictionary comp fetching? Though even if it is eventually going to be faster, it wouldn't hurt to just make `GetNetEntity()` directly use a dictionary if no metadata comp is passed in.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Shared/GameObjects/NetEntity.cs
> +    public static readonly NetEntity First = new(0);
I'm pretty sure there is EntityUid code somewhere that relies on the default EntityUid value being invalid. Having default/unspecified ids be valid ids seems like its prone to introducing confusing bugs. Even if this is what arch uses I think we should stick with 0 being invalid.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
> -                $"While removing expected contained entity {ToPrettyString(uid)}, the entity was missing from the container expected set. Container: {container.ID} in {ToPrettyString(container.Owner)
If there isn't already one, there should be a `ToPrettyString(NetEntity)`, and it should be used here.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameStates/ClientDirtySystem.cs
>              return;
Now that `IsClientSide()` is slow, the order here should be changed.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/Physics/JointSystem.cs
> +                var other = state.UidA == ToNetEntity(uid) ? ToEntity(state.UidB) : ToEntity(state.UidA);
```suggestion
                var uidA = ToEntity(state.UidA);
                var other = uidA == uid ? ToEntity(state.UidB) : uidA;
```
If this comes up frequently, it might be useful to add a helper method?

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/Replays/Loading/ReplayLoadManager.Start.cs
> +            entities.Add(uid);
Need to `SetNetEntity()`.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Shared/GameObjects/Components/MetaDataComponent.cs
> +        public NetEntity NetEntity { get; internal set; } = NetEntity.Invalid;
Maybe add an access attribute for EntityManager. Also, this should get set inside of `SetNetEntity()` to ensure they never get set separately.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/Replays/Playback/ReplayPlaybackManager.Checkpoint.cs
> +            _entMan.InitializeEntity(uid, meta);
set net id

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Shared/Console/Commands/MapCommands.cs
> -        var gridId = EntityUid.Parse(args[0]);
In all shared & client-side commands, this needs to be some other functions that can parse both net-ids and normal entity uids, and I guess we need some convention for how to distinguish them as strings.

Or alternatively, the client needs to assign valid (but client-only) net ids to client-side entities. I.e., basically how the old client side ids worked.

The latter is probably better for keeping parity between server, shared, & client side code?

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/UserInterfaceSystem.cs
> +            RaiseLocalEvent(bui.Owner, new BoundUIOpenedEvent(bui.UiKey, GetNetEntity(bui.Owner), session));
The local events shouldn't ever need to use the net entity, and the client should resolve the net -> local uid when handling the BUI message

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
>          }
Even if arch does make comp fetching faster, would it be worth having the transform child list store a (uid, netUid) tuple? Because this will add another ~20+ component fetches anytime a player moves.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
> +        var mComp = _metaQuery.GetComponent(uid);
This method should take in both the netId & uid. E.g., further down you have both parent & parentNetEntity, but you only pass the netId to the function which causes a redundant  GetEntity(netEntity);

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
> +            !AddToChunkSetRecursively(in parentNetEntity, visMask, tree, set)) //did we just fail to add the parent?
Not the fault of this PR, but this causes a redundant  set.ContainsKey() check, maybe just slap //TODO on it

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
> +        _poolManager.Return(deletions);
What is the point of this? This is just copying the list, and as far as I know GetDeletedIndices() isn't pooled and shouldn't be returned?

These changes should either just be removed, or  GetDeletedIndices() needs to be properly pooled & returned. In order to minimize the chance of accidentally adding misc pooling bugs, its probably better to just add a //TODO and leave the code unchanged for now.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
> +                AddToSendSet(in childNetEntity, _metaQuery.GetComponent(child), toSend, fromTick, in entered, ref entStateCount);
Move outside of the if block and use in GetNetEntity()

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Server/GameStates/PvsSystem.cs
> +        DebugTools.Assert(meta.NetEntity.IsValid());
```
DebugTools.Assert(EntityManager.GetEntity(meta.NetEntity) == entityUid);
```

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Shared.CompNetworkGenerator/ComponentNetworkGenerator.cs
> +            component.{name} = GetEntity(state.{name});");
I just realized there is an issue here that'll break comp state networking, thought it'd also break entity coordinate networking and thus also things like & sound sources.

Previously a component could reference some other entity that the client hasn't received yet. Initially any TryComp() and such would just fail, but when the client does eventually receive the entity, things should work fine. However, now the netid -> uid  will fail and the data in the component will just be stuck in a bad state until the server dirties the component and re sends it, which it might never do.

If I get around to it ill write an actual test for this, but for now a simple test would be to just have an overlay that draws a line between two entities, and then have them enter PVS one after the other. 

For now, the only way I can think of fixing it is to have the client-side `GetEntity()` generate/reserve an entity uid if it encounters an unknown net id. ApplyGameState() would then need to check if a uid has been reserved whenever it encounters an unknown netId, and then create an entity with the reserved uid (which also means re-adding that AllocEntity arg).

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Shared/Console/CompletionHelper.cs
>      {
If we don't create valid net-ids for client-side entities, then this should me moved to Robust.Server to try and ensure that people don't accidentally write invalid commands in shared code.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
>                  {
Move the `metas.TryGetComponent` up so you can pass it into IsClientSide.

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +                        containerSys.AddExpectedEntity(_entities.GetNetEntity(ent), container);
Just use the netEntity from the foreach loop

2023-08-25 04:06 UTC, ElectroJr commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
Is there any reason we can't just keep the old clientside check? It would make this significantly faster,

2023-08-26 12:38 UTC, metalgearsloth commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
Do you mean the bitflag or?

If we're using genids then the id is going to point to its array index.

2023-08-27 17:54 UTC, ElectroJr commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
gen ids work by having some bits for the generation, while others are the index, right? is there some spare bit that can still be used to store misc "metadata"?

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityManager.cs
> +            // TODO: Dump on server
```suggestion
```

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityState.cs
> -        public EntityUid Uid { get; }
Seeing as the client will repeatedly use the state while resetting prediction, its probably worth keeping the uid field and resolving it only once. Thought that doesn't need to be done now and I might do this in a separate PR.

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntitySystem.Proxy.cs
> +    }
Having one use a nullable out, while the other is not nullable is a bit weird. It should just be one or the other.

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/Serializers/NetEntitySerializer.cs
> +    }
This confused me for a bit, so its probably worth adding some comments noting that:
- This serializer relies on a serialization context that provides an entity uid serializer.
- All entities that are to be loaded must have been allocated prior to deserialization.

Also, are there actually net id data fields that get used by existing maps?  I.e., do the map load tests implicitly test this serializer or does this need a test? (I haven't gotten to the content PR yet)

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/Serializers/NetEntitySerializer.cs
> +        return new NetEntity(source.GetHashCode());
Why not just make the int public? Also makes some debugging slightly easier

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/Map/EntityCoordinates.cs
> +    ///     A set of coordinates relative to another entity. Used for net
incomplete comment. I guess its meant to refer to the net ent coords?

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityManager.Network.cs
> +        // I wanted this to logMissing but it seems to break a loootttt of dodgy stuff on content.
Ill get around to looking at the content PR next, but how much is a lot? Should it at least log a warning?
And what causes it?

2023-08-27 18:46 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntityManager.Network.cs
> +        // I wanted this to logMissing but it seems to break a loootttt of dodgy stuff on content.
Even moreso here, when its not a try-get function

2023-09-03 04:33 UTC, metalgearsloth commented
Talked about it on disc but tl;dr currently blocked on handling entities we don't know about yet.

2023-09-06 08:39 UTC, metalgearsloth commented on Robust.Shared/GameObjects/NetEntity.cs
> +    public static readonly NetEntity First = new(0);
I think with arch they ended up changing it to start at 1 due to the propensity for default bugs so will change.

2023-09-06 08:43 UTC, metalgearsloth commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
With genids it *should* be faster to index the archetype array then index metadatacomponent's type in it rather than do a dictionary lookup but will benchmark it later.

I did the other thing.

2023-09-06 08:45 UTC, metalgearsloth commented on Robust.Client/Physics/JointSystem.cs
> +                var other = state.UidA == ToNetEntity(uid) ? ToEntity(state.UidB) : ToEntity(state.UidA);
I don't think it's that common, mainly just joints code, and box2d is getting updated to v3 at some point which refactors the entire thing which will require me to re-write most of physics for it so I'm trying to avoid changes before then.

2023-09-06 08:54 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/UserInterfaceSystem.cs
> +            RaiseLocalEvent(bui.Owner, new BoundUIOpenedEvent(bui.UiKey, GetNetEntity(bui.Owner), session));
I'll make another abstract for it.

2023-09-06 08:57 UTC, metalgearsloth commented on Robust.Server/GameStates/PvsSystem.cs
>          }
With archetypes GetComponent scales much better with getting multiple components at the same time as you have an array of component arrays, so you just index the same slot into 2 different arrays instead of 1.

With that being said I want to look at refactoring out MoveEvent from PVSSystem at some point so I'm fine dealing with the overhead in the interim.

2023-09-06 08:58 UTC, metalgearsloth commented on Robust.Shared/GameObjects/EntityState.cs
> -        public EntityUid Uid { get; }
Yeah I'm not sure where this done atm so could put the field in and put NonSerialized on it?

2023-09-06 08:58 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Serializers/NetEntitySerializer.cs
> +        return new NetEntity(source.GetHashCode());
Yeah I'll change it.

2023-09-06 09:02 UTC, metalgearsloth commented on Robust.Client/GameObjects/ClientEntityManager.Network.cs
> +    }
I don't think there's an easy way to do it to my knowledge. If it's an issue we could keep a dummy clientside world that stores entityuids that are clientside if we need the lookups to be fast as it'd just be an array index (though obviously not going to be as fast as just setting an arbitrary bit like we do atm which is somewhat hacky anyway).

2023-09-06 09:19 UTC, metalgearsloth commented on Robust.Shared/Map/EntityCoordinates.cs
> +    ///     A set of coordinates relative to another entity. Used for net
Yeah it re

2023-09-06 09:27 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Serializers/NetEntitySerializer.cs
> +    }
DoAfter I think was the main edge case of "I kinda sorta maybe need to serialize NetEntities or double stuff". There might be one or two more. It might be easier to just remove it and have content handle it.

2023-09-07 07:30 UTC, metalgearsloth commented on Robust.Server/GameStates/PvsSystem.cs
> +        _poolManager.Return(deletions);
Think it's a holdover from before I rewrote most of pvs for NetEntity so it's removeable.

2023-09-08 03:10 UTC, ElectroJr commented
I pushed some changes, should be easy to examine commit by commit:
- Moved `IEntityManager.IsClientSide(NetEntity)` into `NetEntity`
- Fixed partial state reset erroring when the state contains new entities
- Changed the `GetEntity()` in `ApplyEntityStates` and `ProcessDeletions` into a try-get
- Changed `GetEntity()` so that it returns the default value when trying to parse an unknown entity uid
  - This is what the docstrings said the method should do, and a bunch of code seemed to assume that that is how it would work.
  - If it should be changed back to throwing, then we should probably add a `GetEntityOrDefault()`
- Removed the colleciton pooling from `EntityManager.Network.cs`
  - There is no clear indication that these methods return pooled collections, and a bunch of code was just never returning the collections to the pool
  - IMo we should just add overrides that explicitly return pooled collections, or just add overrides that take in an existing collection, seeing as the caller already has to handle returning the collection to the pool anyways.

2023-09-10 17:17 UTC, ElectroJr approved these changes

2023-09-10 23:42 UTC, merged