Advertise to multiple hubs simultaneously
space-wizards/RobustToolbox pull request #4285
Opened 2023-08-21 15:04 UTC by PrPleGoo

new CVar hub_urls
CVar master_url mentioned as deprecated
HubManager will now ping all hub URLs

2023-08-21 23:24 UTC, Jezithyr requested changes

2023-08-21 23:24 UTC, Jezithyr commented on Robust.Server/ServerHub/HubManager.cs
> +            try
try to avoid using try-catch, an if check would be more efficient here. Throwing and handling exceptions is considerably more expensive than a simple if check

2023-08-21 23:24 UTC, Jezithyr commented on Robust.Server/ServerHub/HubManager.cs
> -                _sawmill.Info("Successfully advertised to hub with address {ServerHubAddress}", _advertiseUrl);
We should still log info that the server was successfully advertised. Also it would be useful to know which hub the server was advertised on.

2023-08-21 23:24 UTC, Jezithyr commented on Robust.Shared/CVars.cs
> +        /// Depricated: overwrites the value of hub.hub_urls
why deprecate this cvar instead of removing it?

2023-08-22 16:17 UTC, PrPleGoo commented on Robust.Server/ServerHub/HubManager.cs
> +            try
the try catch was already here

2023-08-22 16:18 UTC, PrPleGoo commented on Robust.Shared/CVars.cs
> +        /// Depricated: overwrites the value of hub.hub_urls
Didn't want to cause breaking changes to a setting that might already be in use by some servers.
I can remove it if that's alright.

2023-08-22 16:19 UTC, PrPleGoo commented on Robust.Server/ServerHub/HubManager.cs
> -                _sawmill.Info("Successfully advertised to hub with address {ServerHubAddress}", _advertiseUrl);
see :137

2023-08-22 18:45 UTC, Jezithyr commented on Robust.Server/ServerHub/HubManager.cs
> +            try
Still it might be worth replacing it with an if check instead to improve perf.

2023-08-22 18:46 UTC, Jezithyr commented on Robust.Shared/CVars.cs
> +        /// Depricated: overwrites the value of hub.hub_urls
Yep, removing it shouldn't break anything

2023-08-22 18:47 UTC, Jezithyr commented on Robust.Server/ServerHub/HubManager.cs
> -                _sawmill.Info("Successfully advertised to hub with address {ServerHubAddress}", _advertiseUrl);
I see that, yeah sorry I missed that the first time 😅 looks good to me

2023-08-22 18:48 UTC, Jezithyr commented
I'll need to do some tests to make sure this doesn't somehow brick the launcher when I get home from work. But this looks like it's good to merge so far

2023-08-22 23:08 UTC, Visne requested changes

2023-08-22 23:08 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +            _hubUrls = hubUrls;
```suggestion
            _hubUrls = s.Split(",", StringSplitOptions.RemoveEmptyEntries).Select(u => u.Trim()).ToArray();
```

2023-08-22 23:08 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +                        $"Error status while advertising server: [{response.StatusCode}] {errorText}, to hub: {hubUrl}");
I know the code was already like that, but you can just use `_sawmill.Error()` here. Also, passing the args separately instead of string interpolation like it was before is probably better (but not sure).

2023-08-22 23:08 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +                if (!_firstAdvertisementByHubUrl.ContainsKey(hubUrl))
This only checks if it has the key, not whether its value is `true`. It probably makes more sense anyways to just store the hub URLs that were advertised to, instead of a dictionary which will only ever have the values `true`.

2023-08-22 23:08 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +                _sawmill.Log(LogLevel.Error, e, $"Exception while trying to advertise server to hub {hubUrl}");
Probably better to use args instead of string interpolation here too.

2023-08-22 23:08 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +            try
Try-catch is fine here imo.

2023-08-22 23:10 UTC, Visne commented on Robust.Server/ServerHub/HubManager.cs
> +            _hubUrls = hubUrls;
Or just use a `List<string>`, doesn't really have to be an array.

2023-08-23 17:37 UTC, Visne approved these changes

2023-08-23 17:43 UTC, Visne commented
Code looks good to me, but definitely needs some real testing before merge.

2023-08-24 16:59 UTC, PJB3005 commented on Robust.Server/ServerStatus/StatusHost.cs
> +        private IReadOnlyList<string> _serverTagsCache = Array.Empty<string>();
Why change this file?

2023-08-24 17:18 UTC, Visne commented on Robust.Server/ServerStatus/StatusHost.cs
> +        private IReadOnlyList<string> _serverTagsCache = Array.Empty<string>();
I think they originally copy-pasted the for-loop on line 113, then I recommended to just use Linq there, and now they are also applying that here for consistency.

2023-08-26 00:36 UTC, PrPleGoo commented on Robust.Server/ServerStatus/StatusHost.cs
> +        private IReadOnlyList<string> _serverTagsCache = Array.Empty<string>();
Yeah, exactly what Visne said.

2023-08-30 19:08 UTC, Visne commented
I tested this today and it seems to work fine, even with a pretty messed up config value with multiple commas, invalid addresses, and whitespace between commas.

2023-09-05 22:25 UTC, merged