Ability to change IPlayingStream audio parameters
space-wizards/RobustToolbox pull request #4289
Opened 2023-08-22 11:06 UTC by IlinMihail

Added SetAudioParams() and GetAudioParams() methods

2023-08-22 11:11 UTC, IlinMihail commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +            return AudioParams.Default;
Idk how to retrieve current parameters since IClydeAudioSource only implements methods for setting them, if it's strictly required to make this in order for this to get merged tell me

2023-08-22 11:11 UTC, metalgearsloth requested changes

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +        SubscribeNetworkEvent<SetAudioParametersMessage>(SetAudioParamsHandler);
This should be handled as party of audio being dirtied not special-casing events.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
>      #endregion
As above and also using LINQ on hot paths is a nono.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +            Stream = stream,
Streams shouldn't contain references to systems as we use ECS and data composition.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +        public AudioStream Stream = default!;
Isn't Stream gettable through source anyway.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
>      }
Looks placeholder? Why is it always returning default audioparams.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
>      }
These shouldn't be public as content shouldn't worry about audio source handling.

2023-08-22 11:11 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
>              Identifier = id
Pulling this out is an unnecessary change.

2023-08-22 11:21 UTC, IlinMihail commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +        public AudioStream Stream = default!;
no, atleast not without typecasting source interface to more specific types

2023-08-22 11:21 UTC, IlinMihail commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
>      }
yeah wrote about it above. I'll implement it later

2023-08-22 11:24 UTC, IlinMihail commented on Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
>              Identifier = id
that was made to not write the same ternary op twice

2023-08-22 18:23 UTC, IlinMihail commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
>      }
functional now

2023-08-22 18:24 UTC, IlinMihail commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +        SubscribeNetworkEvent<SetAudioParametersMessage>(SetAudioParamsHandler);
done

2023-09-11 04:45 UTC, metalgearsloth requested changes

2023-09-11 04:45 UTC, metalgearsloth commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +
Store them by netidentifier rather than iterating potentially hundreds of sounds every time.

Also just use the latter and call it TryGetStream.

2023-09-11 05:21 UTC, metalgearsloth commented
Also for any future changes we should just bite the bullet and make audio sources entities instead.

2023-09-21 19:13 UTC, IlinMihail commented
this pr also requires https://github.com/space-wizards/space-station-14/pull/20397

2023-09-23 02:29 UTC, Partmedia commented on Robust.Shared/Audio/AudioParams.cs
> +        public Attenuation? Attenuation { get; set; } = Default.Attenuation;
Could you justify why these are now nullable, given that they are given a default? This is a breaking API change that requires a major engine version bump.

2023-09-23 02:30 UTC, Partmedia commented on Robust.Shared/Audio/AudioParams.cs
> +            float? volume,
You can make the constructor accept nullable fields without making the public fields nullable as well.

2023-09-23 20:56 UTC, IlinMihail commented on Robust.Shared/Audio/AudioParams.cs
> +        public Attenuation? Attenuation { get; set; } = Default.Attenuation;
sloth has asked to change audio parameters by sending play sound message twice, instead of using separate message. so nullable fields in audio params are for comparing new parameters with the old ones. some of the parameters cannot be (and I think shouldn't be) retrieved after setting them, so it's the only way I saw to tweak only the necessary values. if there is a better way please tell me.

2023-09-23 20:58 UTC, IlinMihail commented on Robust.Shared/Audio/AudioParams.cs
> +            float? volume,
uhm, but they should be nullable I'm currently implementation.

2023-09-27 17:58 UTC, IlinMihail commented
not working on the feature this pr was made for anymore

2023-09-27 17:58 UTC, closed without merging