Convert `Tile.TypeId` to an int
space-wizards/RobustToolbox pull request #4307
Opened 2023-08-24 05:33 UTC by ike709

Fixes #4306

OpenDream didn't explode:
![image](https://github.com/space-wizards/RobustToolbox/assets/5714543/2baa6802-9459-4c37-8f79-d585978dbdff)

2023-08-24 05:34 UTC, ike709 commented on Robust.Shared/Map/Tile.cs
> -    public static explicit operator uint(Tile tile)
![image](https://github.com/space-wizards/RobustToolbox/assets/5714543/e20c49c4-b0fe-48e8-9e58-a797f6e43609)

2023-08-24 06:19 UTC, ike709 commented
I'm not sure why these tests are failing still:
![image](https://github.com/space-wizards/RobustToolbox/assets/5714543/164d5c22-f5db-4bf3-b49f-735e812727cd)

2023-08-25 13:21 UTC, metalgearsloth requested changes

2023-08-25 13:21 UTC, metalgearsloth commented on Robust.Server/Maps/GridSerializer.cs
>                  var variant = reader.ReadByte();
None of the old maps were saved with this in mind so you should bump the map format version and check if the version is earlier than latest then use the old method.

2023-08-26 12:16 UTC, merged