Localization support for any prototypes
space-wizards/RobustToolbox pull request #4335
Opened 2023-08-30 00:14 UTC by ficcialfaint

# About the PR
The PR adds ability to turn any prototype into `localized prototype` that supports localization in fluent file with custom prefix as entities do with `ent-` prefix. 
## How does it work?
There is now a new `ILocalizedPrototype` interface. You simply implement it in your prototype and add:
- `SetName` -- the default name you set in the prototype, in YAML files
- `SetDesc` -- same as `SetName` but for descriptions
- `Name` -- the localized name
- `Description` -- the localized description
- `CustomLocalizationPrefix` - the prefix that will be used in `.ftl` files. For example, entities use `ent-` prefix: `ent-BaseItem = base item`
Then you have to set `Name`'s and `Description`'s getters to `ILocalizationManager.GetPrototypeData<YourPrototype>(ID).Description` / `.Name`.

**Here is a small example for a localized prototype:**
```cs
[Prototype("construction")]
public sealed class ConstructionPrototype : IPrototype, ILocalizedPrototype, ISerializationHooks
{
    private ILocalizationManager _loc = default!;

    [DataField("name")]
    public string? SetName { get; private set; }

    [DataField("description")]
    public string? SetDesc { get; private set; }

    [ViewVariables]
    public string Name => _loc.GetPrototypeData<ConstructionPrototype>(ID).Name;

    [ViewVariables]
    public string Description => _loc.GetPrototypeData<ConstructionPrototype>(ID).Desc;

    public string CustomLocalizationPrefix { get; private set; } = "cnt"; // e.g. cnt-BaseCraft = cool name

    void ISerializationHooks.AfterDeserialization()
    {
        _loc = IoCManager.Resolve<ILocalizationManager>();
    }
}
```

2023-09-14 19:01 UTC, ElectroJr requested changes
The given example is bad because it uses ISerializationHooks which are obsolete.
The localized strings should just get resolved once after prototypes have been (re)loaded, which would also mean you could just get rid of the caching dictionary.

2023-09-14 19:01 UTC, ElectroJr commented on Robust.Shared/Localization/LocalizationManager.Prototypes.cs
> +        foreach (var prototype in _prototype.EnumerateParents(kind, prototypeId, true))
This doesn't recursively iterate up through a prototypes parents, this is just the direct parent list

2023-09-14 19:01 UTC, ElectroJr commented on Robust.Shared/Localization/LocalizationManager.Prototypes.cs
> +        var lproto = (ILocalizedPrototype)prototype;
try cast

2023-09-14 19:01 UTC, ElectroJr commented on Robust.Shared/Prototypes/IPrototype.cs
> +        [ViewVariables] public string Description { get; }
I might be wrong, but I don't think the data-field attributes do anything on interfaces?
I'm also not sure about whether VV works on interfaces.

2023-09-14 19:01 UTC, ElectroJr commented on Robust.Shared/Prototypes/IPrototype.cs
> +        [ViewVariables] public string Description { get; }
Also, these should have documentation comments

2023-10-01 20:46 UTC, ficcialfaint commented
I just noticed the review, I'll see what I can do, thanks

2023-10-09 17:54 UTC, ElectroJr commented on Robust.Shared/Localization/LocalizationManager.Prototypes.cs
> +    private readonly ConcurrentDictionary<string, PrototypeLocData> _prototypeCache = new();
Needs to be per-prototype

2023-10-09 17:57 UTC, ElectroJr commented on Robust.Shared/Localization/LocalizationManager.Prototypes.cs
> +        FlushPrototypeCache();
This should enumerate over kinds and only flush the cache for prototypes that actually changed.
Also FlushPrototypeCache() is broken, its just a copy paste of FlushEntityCache()

2023-12-21 03:28 UTC, LightVillet commented
@ficcialfaint when

2024-02-03 02:28 UTC, Ygg01 commented
This is probably too old to merge anymore. Close?

2025-03-24 00:55 UTC, closed without merging