Added method to search nested containers for a specified component
space-wizards/RobustToolbox pull request #4337
Opened 2023-08-30 05:36 UTC by chromiumboy

Adds two new methods to SharedContainerSystem that allow you to recursively search the parent objects of a contained entity for a specified component

The first method returns the first matching component found, and the second returns a list of matching components found across all recursive parent entities

2023-08-30 05:48 UTC, metalgearsloth requested changes

2023-08-30 05:48 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            EntityQuery<TransformComponent>? xforms = null) where T : Component
Just put the entityquery on the system and also require the user to pass in EntityQuery<T>

2023-09-02 05:03 UTC, metalgearsloth requested changes

2023-09-02 05:03 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +        }
This is going to allocate a new list for every parent which is expensive, better to just pass it in and re-use it. This also avoids the additional Concat and ToList calls.

2023-09-02 15:18 UTC, chromiumboy commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +        }
Fair point, the requested changes have been made

2023-09-04 11:13 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +        }
You're setting the list to null every loop when it should just be passed in.

2023-09-04 11:19 UTC, metalgearsloth requested changes

2023-09-04 11:19 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            T? foundComponent = null;
Remove this as it looks like you don't even use it.

2023-09-04 11:19 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            ref List<T> foundComponents,
Don't need to pass ref types by ref.

2023-09-04 15:45 UTC, chromiumboy commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            T? foundComponent = null;
foundComponent is required to the entity query on line 281 and 282

2023-09-04 15:49 UTC, chromiumboy commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            ref List<T> foundComponents,
Not sure what you mean here, don't we need to pass the ref for the recursion to work on line 284?

2023-09-05 02:25 UTC, metalgearsloth commented on Robust.Shared/Containers/SharedContainerSystem.cs
> +            T? foundComponent = null;
Just use TryGetComponent instead of a dummy resolve.

2023-09-06 00:24 UTC, merged