Print stack trace when adding a component while iterating net comps in ResetPredictedEntities
space-wizards/RobustToolbox pull request #4541
Opened 2023-11-01 04:47 UTC by DrSmugleaf

2023-11-04 16:10 UTC, ElectroJr requested changes

2023-11-04 16:10 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +                        return;
AddedComponentEventArgs could just include either the net id or whole registration, which'd save a dict lookup per component addition.

2023-11-04 16:10 UTC, ElectroJr commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +            {
I dunno if it also makes a performance difference, but IMO this should just be an actual function, mainly cause its nicer to read.

2023-11-08 07:55 UTC, DrSmugleaf commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +                        return;
Fixed in https://github.com/space-wizards/RobustToolbox/pull/4541/commits/24691c4713c5a62a2c68c5117036270c67a193e5

2023-11-08 07:55 UTC, DrSmugleaf commented on Robust.Client/GameStates/ClientGameStateManager.cs
> +            {
Fixed in https://github.com/space-wizards/RobustToolbox/pull/4541/commits/24691c4713c5a62a2c68c5117036270c67a193e5

2023-11-12 18:26 UTC, ElectroJr approved these changes

2023-11-12 18:26 UTC, merged