Add `EntityQuery<T>.Get()`
space-wizards/RobustToolbox pull request #4550
Opened 2023-11-05 20:35 UTC by ElectroJr

Adds a method to `EntityQuery<T>` that returns an `Entity<T>`

2023-11-06 00:23 UTC, DrSmugleaf requested changes

2023-11-06 00:23 UTC, DrSmugleaf commented on Robust.Shared/GameObjects/EntitySystem.Resolve.cs
> +        protected bool Resolve<TComp>(ref Entity<TComp?> entity, bool logMissing = true)
This won't actually be enough for the IDE to think the component isn't nullable, so you would still need to suppress the warning.
There is a way to fix that which is putting the resolve method in Entity<T> and making it use the MemberNotNullWhen attribute. I'm not sure if that attribute works outside of the same type though.

2023-11-08 04:24 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntitySystem.Resolve.cs
> +        protected bool Resolve<TComp>(ref Entity<TComp?> entity, bool logMissing = true)
I was led astray by Rider's nullability analysis, which seems to have no issue with this, but build still fails.

Moving it into the entity class means you'd also need to pass in `IEntityManager`, and at that point it'd jus be easier to use `Resolve(ent.Owner, ref ent.comp)`. 

So I've just removed these functions. Maybe one day we'll have the technology.

2023-11-08 04:24 UTC, DrSmugleaf approved these changes

2023-11-08 04:24 UTC, merged