PrototypeAttribute name parameter is optional now
space-wizards/RobustToolbox pull request #4672
Opened 2023-12-07 18:06 UTC by ficcialfaint

With this PR you can now do the following:
```cs
[Prototype]  // No need to do [Prototype("something")]
public sealed partial class SomethingPrototype : IPrototype
{
}
```
If the name isn't specified in the attribute, it takes the class name, converts it into camelCase and gets rid of `Prototype` at the end (This is now required for classes that don't specify custom prototype name via attribute parameter; similar like comps do)

2023-12-07 18:35 UTC, DrSmugleaf approved these changes

2023-12-07 18:46 UTC, DrSmugleaf requested changes

2023-12-07 18:46 UTC, DrSmugleaf commented on Robust.Shared/Prototypes/PrototypeManager.cs
> +            return $"{char.ToLowerInvariant(name[0])}{name[1..][..^prototype.Length]}";
```suggestion
            return $"{char.ToLowerInvariant(name[0])}{name[1..^prototype.Length]}";
```

2023-12-21 08:01 UTC, DrSmugleaf requested changes

2023-12-21 08:01 UTC, DrSmugleaf commented on Robust.Shared/Prototypes/PrototypeManager.cs
> +    public class InvalidPrototypeNameException : Exception
[Virtual] is in case you intend for this class to be inherited. I don't think there's much of a reason to let content inherit this exception type.

```suggestion
    public sealed class InvalidPrototypeNameException : Exception
```

2023-12-21 08:16 UTC, ficcialfaint commented on Robust.Shared/Prototypes/PrototypeManager.cs
> +    public class InvalidPrototypeNameException : Exception
Oh I just copied it from component. InvalidComponentName exception is virtual, perhaps it makes sense to just inherit it?

2023-12-21 08:42 UTC, DrSmugleaf commented on Robust.Shared/Prototypes/PrototypeManager.cs
> +    public class InvalidPrototypeNameException : Exception
The two should be separate though I don't know why the component one is virtual either

2023-12-23 06:36 UTC, merged

2023-12-23 07:08 UTC, ficcialfaint commented
thank you