Make RobustMappedStringSerializer use frozen dictionaries
space-wizards/RobustToolbox pull request #4717
Opened 2023-12-15 23:24 UTC by ElectroJr

2023-12-15 23:59 UTC, ElectroJr commented on Robust.Shared/Serialization/RobustMappedStringSerializer.MappedStringDict.cs
> +                _sawmill.Info($"Freezing mapped strings took {st.Elapsed.TotalMilliseconds:f2}ms");
about 30ms on my machine

2023-12-16 02:09 UTC, PJB3005 commented
Could overlap the string dictionary freezing with the compression. Otherwise good choice.

2023-12-16 02:13 UTC, PJB3005 requested changes

2023-12-16 02:13 UTC, PJB3005 commented on Robust.Shared/Serialization/RobustMappedStringSerializer.MappedStringDict.cs
> +                _sawmill.Info($"Freezing mapped strings took {st.Elapsed.TotalMilliseconds:f2}ms");
Verbose or debug log level

2023-12-16 04:48 UTC, merged