Add background color setting to the richtext
space-wizards/RobustToolbox pull request #4788
Opened 2023-12-31 00:36 UTC by c4llv07e

Add the ability to change the background color of the text in the markup language using "[bgcolor]". This works similarly to "[color]", but it can also be null.

Highlighting words in a chat as an example:

![image](https://github.com/space-wizards/RobustToolbox/assets/38111072/ffada5c6-e8c0-4940-bb3d-3a85979457aa)

2024-01-01 02:41 UTC, metalgearsloth requested changes
Please use C# style guide for variable naming i.e. camelCase.

2024-01-01 02:41 UTC, metalgearsloth commented on Robust.Client/UserInterface/RichText/MarkupDrawingContext.cs
> +        BackgroundColor = new Stack<Color?>(capacity);
This should be nullable.

2024-01-06 17:55 UTC, PJB3005 requested changes

2024-01-06 17:55 UTC, PJB3005 commented on Robust.Client/Graphics/Font.cs
> +            if (background_color is Color bg_color)
This is not a good way to implement this. Large spans of background-colored text will break sprite batching and ruin performance.

You should have the text drawing code do separate drawing of the background in one go.

2024-01-07 05:11 UTC, c4llv07e commented
Okay, then I'll think how to do it. Closing for now.

2024-01-07 05:11 UTC, closed without merging