Implement OSWindowStyles.* on linux
space-wizards/RobustToolbox pull request #4790
Opened 2023-12-31 06:54 UTC by LetterN

Title; also adds `OSWindowStyles.NoTitleBar` for tgui-like windows with their custom titlebar and such

also implements ownerWindow on linux

2023-12-31 10:06 UTC, PJB3005 requested changes
Add `<RobustLinkAssemblies Include="TerraFX.Interop.Xlib" />` to the csproj btw free size savings.

2023-12-31 10:06 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
> +                if ((parameters.Styles & OSWindowStyles.NoTitleBar) != 0)
You can use `GLFW_DECORATED` instead of manually setting it like this. The problem I'm worried about with enabling this for OpenDream is that I doubt we can ever make tgui's custom dragging logic work.

2023-12-31 10:06 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
> +                        var propName = Xlib.XInternAtom(x11Display, (sbyte*)Marshal.StringToCoTaskMemUTF8("_NET_WM_WINDOW_TYPE"), Xlib.False);
Aren't you leaking this memory every time a window is made?

2023-12-31 10:06 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
> +                        DebugTools.Assert(x11Window != Xlib.None);
This is not guaranteed to be the case if the user is using Wayland GLFW.

2023-12-31 11:59 UTC, PJB3005 requested changes

2023-12-31 11:59 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
> +                            Marshal.FreeCoTaskMem(newPropVal);
Uh, I don't think it's safe to just free these like this?

2023-12-31 17:32 UTC, LetterN commented on Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
> +                            Marshal.FreeCoTaskMem(newPropVal);
whoops; the server does delete these on exit or when x11 server restarts

2024-01-02 17:05 UTC, PJB3005 approved these changes

2024-01-03 00:04 UTC, merged