removed a bunch of vulnerabilities
space-wizards/RobustToolbox pull request #481
Opened 2017-11-25 00:57 UTC by KroshkaMu

2017-11-27 15:29 UTC, YotaXP commented on SS14.Client.Graphics/texture/TextureCache.cs
> +        public Image Image { get => image; set => image = value; }
Instead of writing properties and backing fields, why not just use auto-properties?
```diff
- public Texture Texture;
+ public Texture Texture {get; set;}
```

2017-11-27 15:29 UTC, ZoldorfTheWizard approved these changes

2017-11-27 15:31 UTC, ZoldorfTheWizard requested changes
Appveyor not happy

2017-11-27 15:32 UTC, ZoldorfTheWizard approved these changes

2017-12-02 16:29 UTC, PJB3005 requested changes
Auto-implemented properties, please.

2017-12-08 16:38 UTC, PJB3005 requested changes

2017-12-08 16:38 UTC, PJB3005 commented on SS14.Client.Graphics/Render/RenderImage.cs
> -        private BlendMode blendSettings = BlendMode.Alpha;
Now this doesn't default to `BlendMode.Alpha` anymore. You can just re-add the `= BlendMode.Alpha` before the semicolon.

2017-12-16 18:08 UTC, PJB3005 approved these changes

2017-12-16 18:08 UTC, merged