Double-clicking in LineEdit
space-wizards/RobustToolbox pull request #4831
Opened 2024-01-11 18:18 UTC by ficcialfaint

Closes #1093
Only for LineEdit (no TextEdit support yet™)

---

Two clicks count as a double-click if
* The delay between them is less than or equal to **25 ms**
* The distance between the clicks is less than **10 pixels**

Double-clicking a word selects it. Double-clicking an empty place selects two words along its edges

2024-01-12 02:17 UTC, PJB3005 commented
God fucking bless

2024-01-24 06:26 UTC, ike709 commented
please god merge this

2024-03-29 08:47 UTC, ShadowCommander requested changes

2024-03-29 08:47 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        private const int DoubleClickRange = 10;
Are you able to make these client CVars?

2024-03-29 08:47 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +                     && (_lastClickPosition.Value - args.PointerLocation.Position).Length() < DoubleClickRange)
```suggestion
                     && (_lastClickPosition.Value - args.PointerLocation.Position).IsShorterThan(DoubleClickRange))
```
We now have methods for comparing with vectors.

2024-03-31 04:25 UTC, merged