Add more ValueList conveniences
space-wizards/RobustToolbox pull request #4911
Opened 2024-02-21 03:56 UTC by metalgearsloth

Should also speedup a couple things on contentTM.

2024-02-26 01:03 UTC, PJB3005 requested changes

2024-02-26 01:03 UTC, PJB3005 commented on Robust.Shared/Collections/ValueList.cs
> +        Capacity = count;
`Capacity` is directly the size of the underlying array, so setting it after the array resize doesn't matter.

That said, I'd just replace this with a `_items = new T[count];` to clearly specify intent.

2024-02-26 01:03 UTC, PJB3005 commented on Robust.Shared/Collections/ValueList.cs
> +        liSpan.CopyTo(target);
This doesn't make much sense to me. Usually when you have a function taking `List<T> list, int start, int count` I would expect the `start` and `count` to be in the source list, not the destination (which is what this code does).

Assuming that's intentional, this code is bugged because the array capacity would need to be allocated to `start + count`, not `count`.

2024-02-26 01:03 UTC, PJB3005 commented on Robust.Shared/Collections/ValueList.cs
> +        }
You could get the span of the new region instead and `.Clear()` it. Much faster.

2024-03-02 10:51 UTC, metalgearsloth commented on Robust.Shared/Collections/ValueList.cs
> +        Capacity = count;
oop

2024-03-02 11:15 UTC, merged