Feature/refine robust random and cleanup
space-wizards/RobustToolbox pull request #4975
Opened 2024-03-17 18:10 UTC by Fildrance

Refined xml-doc for **`IRobustRandom`**
Changed **`RobustRandom`** namespace to be file-scoped
Added new methods to **`RandomExtensions`** for getting list of random items from collections:
```
    IReadOnlyCollection<T> GetItems<T>(this IRobustRandom random, IList<T> collection, int count, bool allowDuplicates = true);

    ValueList<T> GetItems<T>(this IRobustRandom random, ValueList<T> collection, int count, bool allowDuplicates = true);

    Span<T> GetItems<T>(this IRobustRandom random, Span<T> collection, int count, bool allowDuplicates = true);
```
Main scenarios for new methods:

- Need to pick item random from list of items
- Need to pick several random items from list, only unique
- Need to pick items from list several times, duplicates allowed.

Separated refactoring and adding code into separate commits for comfortable code-review.

2024-03-17 18:17 UTC, ElectroJr commented on Robust.Shared/Random/RandomExtensions.cs
> +        var maxCollectionIndex = collection.Count - 1;
IIRC the random.Next() upper bound is exclusive, so you don't need the -1?

2024-03-17 18:26 UTC, Fildrance commented on Robust.Shared/Random/RandomExtensions.cs
> +        var maxCollectionIndex = collection.Count - 1;
True, i missed that point. Fixed that, gonna double-check documentation for IRobustRandom that i wrote, i feel it needs fixing on that part too...

2024-03-17 18:34 UTC, ElectroJr requested changes

2024-03-17 18:34 UTC, ElectroJr commented on Robust.Shared/Random/RandomExtensions.cs
> +                }
I'm fairly sure this won't lead to a random selection if allowDuplicates is false, because it will preferentially select items that are adjacent to an already selected item. E.g., if you have a list {a, b, c, d}, and the first item picked is a, then for the next item there's a 50% chance to pick b instead of c or d.

It's probably better to just create a new array, and then do something like:
```cs
var tmp = collection.ToArray();
        
for (int i = 0; i < count; i++)
{
	var j = random.Next(tmp.Length - i);
	rolled[i] = tmp[j];
	tmp[j] = tmp[tmp.Length - i - 1]
}
```



Also, however it ends up being implemented, it should avoid creating a list/hashset unless required by the `allowDuplicates` option,

2024-03-17 19:07 UTC, Fildrance commented on Robust.Shared/Random/RandomExtensions.cs
> +                }
Ah, solution is simple! i just need to roll for 1 less each time - this way there won't be 'bonus-chance' for first element after already picked block, it'll be more like virtual mapping!

2024-03-17 20:57 UTC, Fildrance commented on Robust.Shared/Random/RandomExtensions.cs
> +                }
fixed

2024-03-20 15:37 UTC, Fildrance commented
@ElectroJr can u pls close comments if they are fixed correctly?

2024-03-24 02:56 UTC, metalgearsloth commented
Just bulldoze https://github.com/space-wizards/RobustToolbox/pull/4980

I woulda merged yours first but wasn't sure on some changes.

2024-03-24 02:56 UTC, metalgearsloth requested changes
Needs release notes.

2024-03-24 09:22 UTC, Fildrance commented
> Needs release notes.

Done (question mark)

2024-03-24 09:23 UTC, Fildrance commented
> Just bulldoze #4980
> 
> I woulda merged yours first but wasn't sure on some changes.

merged as well as i could

2024-03-27 01:30 UTC, ElectroJr approved these changes
I pushed some changes including:
- Reducing some code duplication by having the ValueList implementation reuse the Span  one
- Removing some of the "This is O(n)." comments, because AFAIK they were incorrect
- Removing an old internal shuffle extension that is no longer required after dotnet 8
- Reordering the method a bit to reduce nesting.

2024-03-29 23:42 UTC, merged