Add FullscreenUI
space-wizards/RobustToolbox pull request #5041
Opened 2024-04-15 18:20 UTC by notquitehadouken

adds a simple thing for making XAML containers that are fullscreen (as per suggestion of Jezithyr)

2024-04-15 20:15 UTC, moonheart08 requested changes

2024-04-15 20:15 UTC, moonheart08 commented on Robust.Client/UserInterface/CustomControls/DefaultFullscreen.xaml.cs
> +        public sealed class SS14ContentCollection : ICollection<Control>, IReadOnlyCollection<Control>
Please don't copypaste these things. Generalize the original type by making it internal and generic, then create an empty inheritor, maybe?

2024-04-17 13:57 UTC, notquitehadouken commented
if you ignore the part where it doesn't work, it works.

2024-06-26 21:19 UTC, PJB3005 commented
Stale.

2024-06-26 21:19 UTC, closed without merging