add SetUi to shared ui system
space-wizards/RobustToolbox pull request #5092
Opened 2024-04-30 15:06 UTC by deltanedas

evil refactor removed it

2024-05-01 13:46 UTC, deltanedas commented
@metalgearsloth

2024-05-01 13:57 UTC, metalgearsloth requested changes

2024-05-01 13:57 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +    /// It cannot be added already.
This comment is false because the code doesn't care if it's added already. SetUi is probably a better name for it too as Add implies it will throw if it exists already.

2024-05-01 13:57 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +            return;
Should this just ensure instead.

2024-05-01 14:02 UTC, deltanedas commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +            return;
yeah userinterface doesnt actually need anything funny anymore

2024-05-06 21:39 UTC, deltanedas commented
@metalgearsloth a

2024-05-20 01:19 UTC, AJCM-git commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +            ent.Comp = AddComp<UserInterfaceComponent>(ent);
why not use the normal EnsureComp?

2024-05-20 01:22 UTC, AJCM-git commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +            ent.Comp = AddComp<UserInterfaceComponent>(ent);
if its cuz of the cursed Entity<> edge case, just do `var comp = ensure(ent.Owner)`  and access it that way

2024-05-20 02:11 UTC, deltanedas commented on Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs
> +            ent.Comp = AddComp<UserInterfaceComponent>(ent);
ensurecomp wont check if uid == comp.Owner i think, doing resolve does

2024-06-05 05:25 UTC, merged