Hidden tiles
space-wizards/RobustToolbox pull request #5102
Opened 2024-05-04 12:18 UTC by TheShuEd

A small addition that allows you to hide some tiles from the spawn menu. This is useful for downstrimes, disabling the ability to see standard tiles, but not causing huge problems with cutting them from everywhere they are used.

2024-05-04 12:24 UTC, TheShuEd commented
I wonder how I should initialize this field in an object that is not in the engine?

2024-05-04 12:34 UTC, TheShuEd commented
requires https://github.com/space-wizards/space-station-14/pull/27666

2024-05-04 21:44 UTC, PJB3005 requested changes
I'd rename the property to `EditorHidden` or something, so people don't mistake it for a rendering property or something.

2024-05-04 21:55 UTC, TheShuEd commented
Done

2024-05-04 22:03 UTC, PJB3005 commented on Robust.Client/UserInterface/Controllers/Implementations/TileSpawningUIController.cs
> +            if (entry.EditorHidden) continue;
Didn't realize this on the first pass: it's probably better to do this filter *before* the name filter and sort, i.e. put it on line 133 with a `.Where()`.

2024-05-04 22:06 UTC, TheShuEd commented on Robust.Client/UserInterface/Controllers/Implementations/TileSpawningUIController.cs
> +            if (entry.EditorHidden) continue;
Ok, but tomorrow. Im sleeping now

2024-05-16 17:01 UTC, PJB3005 commented on Robust.Client/UserInterface/Controllers/Implementations/TileSpawningUIController.cs
> +                s.ID.Contains(searchStr, StringComparison.OrdinalIgnoreCase)) && !s.EditorHidden);
Doing it like this only applies the hidden when you have a search string.

2024-05-16 17:05 UTC, merged