Add analyzer and fixer for redundant DataField tag arguments
space-wizards/RobustToolbox pull request #5134
Opened 2024-05-13 23:58 UTC by Tayrtahn

Adds an analyzer to provide an editor hint when a DataField attribute specifies a name that matches what the automatically generated name would be. Also adds a code fixer to automate the removal of these issues.

<img width="773" alt="Screenshot 2024-05-13 at 7 51 27 PM" src="https://github.com/space-wizards/RobustToolbox/assets/85356/0838295a-c52d-4777-814c-a6bc816db740">
<img width="463" alt="Screenshot 2024-05-13 at 7 51 38 PM" src="https://github.com/space-wizards/RobustToolbox/assets/85356/14549e49-b1b2-4587-b892-b03ac7a26902">
<img width="463" alt="Screenshot 2024-05-13 at 7 51 48 PM" src="https://github.com/space-wizards/RobustToolbox/assets/85356/b827762a-cd06-48cd-998d-0580d51b3c42">

That Fix All option looks pretty tempting...

2024-05-14 00:02 UTC, mirrorcult commented
zased

2024-05-16 16:59 UTC, PJB3005 requested changes

2024-05-16 16:59 UTC, PJB3005 commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +    private static readonly DiagnosticDescriptor DataFieldRedundantTagRule = new(
The C# term is "attribute", probably best to use it?

2024-05-16 16:59 UTC, PJB3005 commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +            return false;
This feels like it's not a good way to test this?

Is the reason it "could be something else" if you have a named arg? Can't you just check if it's a named arg in that case?

2024-05-16 16:59 UTC, PJB3005 commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +        var automaticName = $"{char.ToLowerInvariant(fieldName[0])}{fieldName.Slice(1).ToString()}";
This code needs to really be shared with the relevant engine code. Use the same MSBuild magic as we use for all the attributes to get access to the code from this project.

2024-05-16 17:11 UTC, Tayrtahn commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +    private static readonly DiagnosticDescriptor DataFieldRedundantTagRule = new(
I went with "tag" since that's the name of the property/arg that's checked: DataField.Tag

2024-05-16 17:12 UTC, Tayrtahn commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +        var automaticName = $"{char.ToLowerInvariant(fieldName[0])}{fieldName.Slice(1).ToString()}";
Yep, agreed.

2024-05-16 17:14 UTC, PJB3005 commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +    private static readonly DiagnosticDescriptor DataFieldRedundantTagRule = new(
Makes sense.

2024-05-16 17:28 UTC, Tayrtahn commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +            return false;
I agree that it's funky, and will totally break if we ever add another string arg to DataFieldAttribute.

Yeah, named args were the reason I had in mind.

I'm not sure how to work out if it's a named arg with the API here. `ConstructorArguments` is just an `ImmutableArray<TypedConstant>`, so I can't see a way to check for a name there. `NamedArguments` is an `ImmutableArray<KeyValuePair<String, TypedConstant>>`, but it doesn't seem to include positional args.

I wonder if it would work to iterate over the Values in NamedArguments and see if there's a match? I can give that a shot.

2024-05-16 17:32 UTC, PJB3005 commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +            return false;
... do positional arguments actually *go* into `ConstructorArguments`?

2024-05-17 01:47 UTC, Tayrtahn commented on Robust.Analyzers/DataDefinitionAnalyzer.cs
> +        var automaticName = $"{char.ToLowerInvariant(fieldName[0])}{fieldName.Slice(1).ToString()}";
Well, trying to include the relevant code proved to be a nightmarish mess of requirements, so I just put the tag autogeneration method into a static method on a new utility class and included that. Hope that's okay.

2024-05-17 05:44 UTC, merged