Makes ScrollContainer scrollbars public
space-wizards/RobustToolbox pull request #5151
Opened 2024-05-19 21:50 UTC by AJCM-git

Dont really see a reason why content can't use these to manipulate the scrollbars behavior and position

2024-05-20 14:37 UTC, PJB3005 commented
What do you need this for?

2024-05-21 01:43 UTC, AJCM-git commented
> What do you need this for?

To access the scrollbar position methods, for example, I'm making a messenger PDA app and i want to scroll to the bottom when entering a profile or when sending/being sent a message

![image](https://github.com/space-wizards/RobustToolbox/assets/60196617/7b6995a4-968c-42d4-b898-e53093ba6386)


https://github.com/space-wizards/RobustToolbox/assets/60196617/9f3be7cc-5501-4570-9b8c-14b594156d7e


I assumed having access to the engine-side children of a control to change behavior was guzzy since things like AnimatedTextureRect.DisplayRect do it, is it a problem here?

2024-05-21 01:45 UTC, moonheart08 commented
It would be better API design to add a scroll-to-target API to ScrollContainer instead.

2024-06-01 15:44 UTC, AJCM-git commented
> It would be better API design to add a scroll-to-target API to ScrollContainer instead.

Took a small break and did that

2024-06-15 21:39 UTC, PJB3005 requested changes

2024-06-15 21:39 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ScrollContainer.cs
> +        public void SetScrollValueToPercentage(int? hValue, int? vValue)
These functions should be called "ratio", take float parameters and take values on the scale 0->1, not 0->100

2025-03-24 01:20 UTC, closed without merging