more placement manager fixes
space-wizards/RobustToolbox pull request #5186
Opened 2024-05-30 20:26 UTC by EmoGarbage404

the last change from using entitycoordinates to mapcoordinates broke the rotation on rotated grids. This remedies that by changing it to use entitycoordinates again and simply updates the SpawnAttachedTo method to support using rotation like the mapcoordinate method.

2024-05-31 02:59 UTC, ShadowCommander requested changes

2024-05-31 02:59 UTC, ShadowCommander commented on Robust.Shared/GameObjects/EntityManager.cs
> +            _xforms.SetCoordinates(newEntity, xformComp, coordinates, rotation: newRotation, unanchor: false);
```suggestion
            _xforms.SetCoordinates(newEntity, xformComp, coordinates, rotation: rotation, unanchor: false);
```

2024-05-31 19:59 UTC, ShadowCommander approved these changes
Have you tested it?

2024-06-01 17:00 UTC, EmoGarbage404 commented
> Have you tested it?

yes

2024-06-01 17:13 UTC, merged