Remove obsolete anchor entity functions
space-wizards/RobustToolbox pull request #5210
Opened 2024-06-05 02:50 UTC by Plykiya

Requires https://github.com/space-wizards/space-station-14/pull/28613

2024-06-05 03:19 UTC, Plykiya commented
hrmmmm
all the tests use .anchor which is another, different obsoleted thing... let's see if changing that out fixes the test fails

2024-06-05 03:43 UTC, Plykiya commented
Okay so I went from 9 test failures to 7 test failures, so the two tests that I properly handed over the tile indices over to the AnchorEntity() function are now succeeding...

2024-06-05 03:49 UTC, Plykiya commented
oh wow... another test fail gone
I guess I'll do the same thing for the other six then?

2024-06-05 04:23 UTC, Plykiya commented
Guh, don't know what to do about that last test

2024-06-05 19:12 UTC, Plykiya commented
Rather than adding TileIndices at every possible turn to get this to work
Maybe I should just... not, add the TileIndices and deal with the Debug Assertion on line 99 of SharedTransformSystem.Component.cs as a sign that something is very wrong if the variant of AnchorEntity() without TileIndices fails to pass

2024-06-05 19:24 UTC, Plykiya commented
So my working theory is that specific debug assert is just flat out... wrong... 
So I removed that specific debug assert condition on line 99 of [SharedTransformSystem.Component.cs](https://github.com/space-wizards/RobustToolbox/pull/5210/files#diff-c3a411183a1e422acc4dee6caaef3f81aaec6c9f6550fc42c5d9a7f3ae329144)[SharedTransformSystem.Component.cs](https://github.com/space-wizards/RobustToolbox/pull/5210/files#diff-c3a411183a1e422acc4dee6caaef3f81aaec6c9f6550fc42c5d9a7f3ae329144)[SharedTransformSystem.Component.cs](https://github.com/space-wizards/RobustToolbox/pull/5210/files#diff-c3a411183a1e422acc4dee6caaef3f81aaec6c9f6550fc42c5d9a7f3ae329144) and removed all the TileIndices from AnchorEntity() usages that I added, so I'm not holding their hand anymore so they all use the AnchorEntity() version that was throwing the dumb debug assertion error

2024-06-05 19:33 UTC, Plykiya commented
oh hey it worked, nice

2024-06-05 19:35 UTC, Plykiya commented
so in summary
the tests weren't actually failing
the tests were "failing" because there was just an AnchorEntity() function with an unnecessary debug assertion even though the code works in the conditions it assumed would be problematic. every test passes with that debug assertion removed

2024-06-30 15:30 UTC, Plykiya commented
I'll take a look at this again and double-check there aren't any test fails

2024-07-13 05:35 UTC, metalgearsloth requested changes

2024-07-13 05:35 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
> -
This assert shouldn't be removed.

The problem is when an entity is not parented to a grid but is trying to be anchored anyway.

2025-02-07 00:09 UTC, closed without merging