Added multi prototype loading
space-wizards/RobustToolbox pull request #5224
Opened 2024-06-10 03:46 UTC by Tornado-Technology

## About PR
The server and client prototype manager now accept the directory list when loading standard prototypes

## Why
It's weird that we only have 1 single folder that we can sub prototypes from by default

2024-06-11 01:44 UTC, PJB3005 commented
What is the use case for this? Why do you need an extra prototypes directory in content?

2024-06-11 01:55 UTC, deltanedas commented
would be *mildly* useful downstream to have say /Resources/DeltaVPrototypes instead of /Resources/Prototypes/DeltaV but then its inconsistent with textures etc so idk

2024-06-11 01:59 UTC, PJB3005 commented
That really doesn't seem useful enough to warrant the extra complexity this introduces IMO.

2024-06-16 11:34 UTC, Tornado-Technology commented
> That really doesn't seem useful enough to warrant the extra complexity this introduces IMO.

Now all prototypes Shared we do not have to make a separate folder with prototypes visible only to the server or client, and also do not add them to the build. Perhaps it will also be convenient to make folders for forks, with completely their own prototypes

2024-06-16 11:37 UTC, PJB3005 commented
Slight problem with this implementation then at least: content can't actually add more prototype paths with this PR.

2024-06-17 12:19 UTC, Tornado-Technology commented
> Slight problem with this implementation then at least: content can't actually add more prototype paths with this PR.

Why?
```cs
using Content.Server._Harmony;
using Robust.Server;
using Robust.Shared.Utility;

namespace Content.Server
{
    internal static class Program
    {
        public static void Main(string[] args)
        {
            Patch.Load();

            var options = new ServerOptions();
            options.PrototypeDirectories.Add(new ResPath("/MyPrototypeDir"));
            
            ContentStart.StartLibrary(args, options);
        }
    }
}
```

2024-06-17 12:57 UTC, deltanedas commented
bruh

2024-06-18 16:30 UTC, Tornado-Technology commented
xd

2024-08-03 01:02 UTC, PJB3005 commented
> > Slight problem with this implementation then at least: content can't actually add more prototype paths with this PR.
> 
> Why?

This is not a supported distribution method of the game for SS14 scenarios. If you actually want to be able to use this for an SS14 server, you cannot use this.

2024-08-03 11:12 UTC, Tornado-Technology commented
> This is not a supported distribution method of the game for SS14 scenarios. If you actually want to be able to use this for an SS14 server, you cannot use this.

It's not for ss14, it's for OTHER games on this cool engine

2024-08-03 13:22 UTC, PJB3005 requested changes

2024-08-03 13:22 UTC, PJB3005 commented on Robust.Client/GameControllerOptions.cs
> +            new("/EnginePrototypes/"),
Do not include `EnginePrototypes` in this list. These need to remain engine internal so content has no business touching it.

2025-03-08 03:42 UTC, metalgearsloth commented
ping if you come back to it.

2025-03-24 01:21 UTC, closed without merging