Added separate localization & clean up
space-wizards/RobustToolbox pull request #5227
Opened 2024-06-11 05:01 UTC by Tornado-Technology

## About PR
Now localization is separate for server and client!

## Why
Maybe in the context of SS14 it might be, a bit odd, but in the context of a game engine it's a basic function

## How it works
All the magic happens thanks to the ``LocalizationManager.LoadDefault`` method, it gets the current localization for the server or client from `CVars`, and loads it. Also for ``LocalizationManager.AddFunction`` to work, it returns the loaded CultureInfo.

2024-06-11 06:09 UTC, ElectroJr commented on Robust.Shared/Localization/LocalizationManager.cs
> +            LoadCulture(culture);
`LoadCulture` only sets the default culture if it is currently null, so shouldn't this method still set it after loading it?

2024-06-11 06:13 UTC, ElectroJr commented
> Now localization is separate for server and client!

> Maybe in the context of SS14 it might be, a bit odd, but in the context of a game engine it's a basic function

While this is a necessary part of a full solution and will help with client-side text, note that it doesn't fully fix the client-side localization issue. This is because a lot of the in game text gets resolved by the server into a string using the server's locale, and then that string gets sent to clients. So a lot of the non-UI text that the client will see will still be in another language. A full fix probably requires replacing all of those strings with some kind of struct with the Loc string id & arguments. 

Also, fully supporting client side languages still requires the server to provide the resources for the language, and at least for ss14 I'm not sure how any forks will bother actively maintaining multiple languages.

2024-06-11 06:16 UTC, PJB3005 requested changes
Remove useless formatting changes, they make review harder.

2024-06-11 06:16 UTC, PJB3005 commented on Robust.Shared/CVars.cs
> +        public static readonly CVarDef<string> CultureName =
This CVar is named incorrectly, it should be `LocCultureName`.

2024-06-11 06:18 UTC, ElectroJr commented on Robust.Shared/CVars.cs
> +            CVarDef.Create("loc.culture_name", "en-US", CVar.ARCHIVE);
This should  have a subscription that actually changes the default value when the cvar gets set, and the command should probably just change the default value by setting the cvar. It should probably also be replicated, so the client can know what value the server is using.

2024-06-11 06:20 UTC, ElectroJr commented on Robust.Shared/CVars.cs
> +            CVarDef.Create("loc.culture_name", "en-US", CVar.ARCHIVE);
Unless I'm misremembering how server->client replicated cvars work. I know for client->server replicated values the server can differentiate between its own value, and client-side values

2024-06-11 06:21 UTC, PJB3005 requested changes

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Console/Commands/LocalizationCommands.cs
> +    public override string Description => "Set DefaultCulture for the client LocalizationManager";
Why does this say client? It's defined in shared.

Also this isn't how `LocalizedCommands` works. Ironic for this kind of PR.

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Console/Commands/LocalizationCommands.cs
> +        var localization = IoCManager.Resolve<ILocalizationManager>();
This needs to be injected via `[Dependency]`.

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Console/Commands/LocalizationCommands.cs
> +        shell.WriteLine($"Loaded culture {culture.Name} not found, loading is in progress");
You really do not need to log this. Hell on the client this will not be displayed before the next message is.

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Console/Commands/LocalizationCommands.cs
> +        var culture = new CultureInfo(args[0]);
This needs to catch errors if the user provides an invalid language.

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Localization/LocalizationManager.cs
> +            var culture = new CultureInfo(name);
This needs to handle an invalid culture being specified in the config.

2024-06-11 06:21 UTC, PJB3005 commented on Robust.Shared/Console/Commands/LocalizationCommands.cs
> +        localization.LoadCulture(culture); // It's also to set culture as default
Uh, `LoadCulture` explicitly does *not* set it as default if something else already is.

2024-06-11 06:23 UTC, PJB3005 commented
While this PR does add some fairly innocent convenience methods to `LocalizationManager`, this isn't going to address any of the *actual* issues blocking different languages between client and server, which Electro already covered.

This can be fine for small games on RT, I guess, but for SS14-based games this isn't helping anything.

2024-08-03 11:08 UTC, Tornado-Technology commented
> While this PR does add some fairly innocent convenience methods to `LocalizationManager`, this isn't going to address any of the _actual_ issues blocking different languages between client and server, which Electro already covered.
> 
> This can be fine for small games on RT, I guess, but for SS14-based games this isn't helping anything.

It's PR for small games, pls do something!!!!

2025-03-24 09:55 UTC, PJB3005 requested changes, later dismissed
I'll fix these issues myself.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Utility/CultureInfoExtension.cs
> +    }
`CultureInfo`s are more complicated than this. Overriding a base `Equals` like this is not a correct "equals" check. This function should be called `NameEquals` or something at the very least.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Localization/Loc.cs
1. Do not do large file formatting changes like this.
2. The changes to this file (to add a static variable) are absolutely not good. If you want to avoid the overhead, get a dependency to `ILocalizationManager`. Do *not* break global state like this.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Client/Console/Commands/LocalizationCommands.cs
> +    public override string Help => $"{Name} <cultureName>";
These localizations still aren't fixed.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Client/Console/Commands/LocalizationCommands.cs
> +    [Dependency] private readonly ILocalizationManager _localization = default!;
You already have access to this via the `LocalizedCommands` field.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Utility/CultureInfoHelper.cs
> +            throw new InvalidCastException();
This is not the correct exception type to use here. Just remove the check, let the `CultureInfo` constructor throw.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Utility/CultureInfoHelper.cs
> +    public static readonly FrozenSet<string> CultureNames = GenerateAllCultureNames();
I am not sure what use it is to cache this large set in the engine like this. This only really feels barely useful for the completions of the command you added.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Utility/CultureInfoHelper.cs
I am unsure about the entire purpose of this file. I would expect it would be best that we used `CultureInfo.GetCultureInfo()` with the option to accept non-existent cultures, for robustness' sake. The game's ability to load localization files on disk shouldn't really be tied to "does the operating system think this language exists."

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Localization/LocalizationManager.cs
> +            foreach (var name in _res.ContentGetDirectoryEntries(new ResPath("/Locale")))
Don't hardcode this path.

2025-03-24 09:55 UTC, PJB3005 commented on Robust.Shared/Localization/LocalizationManager.cs
> +            Debug.Assert(!HasCulture(culture));
This is a public API, so this should not be an assert that's compiled out on debug.

2025-03-24 09:56 UTC, PJB3005 commented on Robust.Shared/CVars.cs
> +            CVarDef.Create("loc.culture_name", "en-US", CVar.ARCHIVE);
The entire point of this API is that it's for non-client-server scenarios right now, so it doesn't (and in fact, can't) be synchronized.

2025-04-02 00:51 UTC, PJB3005 commented on Robust.Shared/Localization/LocalizationManager.cs
> +            }
This isn't guarding against "we don't have localization files for this culture", it's guarding against "the OS doesn't know about this culture". This feels like a weird failure mode to account for, when there's a pretty obvious fallback mechanism that should work well enough: just use a non-predefined culture.

2025-04-02 14:41 UTC, merged

2025-04-02 23:17 UTC, Tornado-Technology commented
Wow