Make unshaded sprite layers not require shader/texture changes.
space-wizards/RobustToolbox pull request #5248
Opened 2024-06-18 07:29 UTC by ElectroJr

Currently drawing an unshaded sprite layer requires switching to the "unshaded" shader, which requires changing textures and creating a new render batch, which generally slows things down. It could be changed to set a shader uniform instead, which is faster than changing textures but still somewhat slow.

This PR changes the default shader so it infers whether lighting should be enabled or disabled from a vertex attribute. Instead of adding a new attribute, it re-uses the colour modulation attribute, where negative values now imply that the lightmap shouldn't get sampled. It's kind of janky, but avoids having to send more vertex data. 

This is a revival of a year+ old branch, and when I benchmarked it back then it did help increased the fps I got on my laptop [by a bit](https://discord.com/channels/310555209753690112/900426319433728030/1102466865382568027).

This PR also renames some of the local variables used in the default shader template to try be somewhat more consistent and to help avoid accidental variable name conflicts (which happened with the `modulate` variable while working in this, which is what prompted this change). Requires a content PR to update the outline shader.

2024-06-21 13:25 UTC, PJB3005 commented
> This PR also renames some of the local variables used in the default shader template to try be somewhat more consistent and to help avoid accidental variable name conflicts (which happened with the modulate variable while working in this, which is what prompted this change). Requires https://github.com/space-wizards/space-station-14/pull/29150to update the outline shader.

Please no breaking changes.

2024-06-21 13:38 UTC, PJB3005 approved these changes
Revert the breaking changes but otherwise looks good

2024-06-21 13:44 UTC, PJB3005 requested changes
Actually, nevermind.

2024-06-21 13:44 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +        LIGHT = texture2D(LIGHTMAP, Pos);
I double checked the GLSL spec after not finding info anywhere else.

Sampling a texture inside non-uniform control flow like this is undefined. Either move the texture sample to always happen or use a function like `textureLod()` which doesn't need implicit derivatives.

2024-06-22 00:33 UTC, ElectroJr commented on Robust.Client/Graphics/Clyde/Shaders/base-default.frag
> +        LIGHT = texture2D(LIGHTMAP, Pos);
I've just moved it outside of the branch.

2024-06-22 00:35 UTC, ElectroJr commented
> Revert the breaking changes but otherwise looks good

I've reverted some of the changes, but there will still be breaking change due to the fact that `VtxModulate` may now contain negative values and people should be using the `MODULATE` field instead.

2025-03-24 01:36 UTC, PJB3005 approved these changes

2025-03-24 01:37 UTC, merged