Add ObjectSerializer, make AppearanceData a DataField
space-wizards/RobustToolbox pull request #5324
Opened 2024-07-30 23:00 UTC by SlamBamActionman

This PR adds ObjectSerializer, a serializer for the generic `object` type. The serializer attempts to get the type from the .yaml (use `!type:<type>` e.g. `!type:string`) via `ISerializationManager` and `IReflectionManager.TryLooseGetType`.

This is necessary for `AppearanceData` in `AppearanceComponent` to be able to be a DataField, allowing it to be set in the base prototype directly via .yaml instead of going through a separate system to set it.

2024-07-31 06:51 UTC, metalgearsloth requested changes
Also obviously needs a release note.

2024-07-31 06:51 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Appearance/AppearanceComponent.cs
> +    public Dictionary<Enum, object> AppearanceData = new();
This must use access attribute.

2024-07-31 06:51 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedAppearanceSystem.cs
> +    }
Having one ensure and one resolve as hidden behaviors is pretty nasty, you should just be consistent between them.

2024-07-31 06:51 UTC, metalgearsloth commented on Robust.Shared/Serialization/TypeSerializers/Implementations/Generic/ObjectSerializer.cs
> +
Last time I tried something like this it broke pretty easily on primitive types so this needs accompanying tests.

2024-07-31 07:33 UTC, deltanedas commented on Robust.Shared/GameObjects/Components/Appearance/AppearanceComponent.cs
> +    public Dictionary<Enum, object> AppearanceData = new();
why shouldnt the entire component have access, theres api for modifying stuff

2024-07-31 10:41 UTC, SlamBamActionman commented on Robust.Shared/GameObjects/Systems/SharedAppearanceSystem.cs
> +    }
The resolve is for the source, which must have the component. The EnsureComp is for the destination, which is not guaranteed to have the component, and will add it if it doesn't. This is the same behavior as in CopyData.

2024-08-01 13:32 UTC, SlamBamActionman commented on Robust.Shared/Serialization/TypeSerializers/Implementations/Generic/ObjectSerializer.cs
> +
The current tests for prototypes already go through and attempt the serialization; would they not count for this Serializer too?

If not, how would such a test look like?

2024-08-28 12:43 UTC, merged