Add a copy to clipboard button on alert popups.
space-wizards/RobustToolbox pull request #5336
Opened 2024-08-05 09:40 UTC by Titian3

This is my first RT PR, Apologies if have done any of this incorrectly.

Changes:
- Added copy button that stores UI alert message popups to clipboard. 

For fixing [this issue](https://github.com/space-wizards/space-station-14/issues/28560) about copying out ban messages but would be good for relaying connection issues and other errors shown here.

![image](https://github.com/user-attachments/assets/0442a1a9-e45d-4505-804e-5337d0dc3ff8)

2024-08-05 12:18 UTC, PJB3005 commented
Ban messages in-game aren't shown with this alert dialog, that's part of `LauncherConnecting` in content.

In general this dialog is pretty bad design wise and not used much, but I don't mind merging this as it can't really hurt.

2024-08-05 12:36 UTC, PJB3005 requested changes

2024-08-05 12:36 UTC, PJB3005 commented on Robust.Client/UserInterface/IUserInterfaceManager.cs
> +        void Popup(string contents, string title = "Alert!", string clipboardButton = "Copy");
I would rather this be a boolean that indicates whether there is a copy button or. I can't imagine many reasons the button would need to be renamed, and as it stands this can't be localized practically.

2024-08-05 12:36 UTC, PJB3005 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +            var grid = new GridContainer
Use a `BoxContainer` instead of a grid for vertical layout like this.

2024-08-05 12:36 UTC, PJB3005 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +            var buttonContainer = new GridContainer
Again, `BoxContainer` but horizontal this time.

2024-08-05 14:08 UTC, Titian3 commented on Robust.Client/UserInterface/IUserInterfaceManager.cs
> +        void Popup(string contents, string title = "Alert!", string clipboardButton = "Copy");
I'm just paranoid for localization now after doing it so much in SS14.
Flag based:
False:
![image](https://github.com/user-attachments/assets/14172246-9827-4388-a9af-793e151c142d)
True:
![image](https://github.com/user-attachments/assets/6a4f6e5d-881b-4765-87c6-1d9125cbcce4)

Both with the boxContainer now.

2024-08-05 14:09 UTC, Titian3 commented
> Ban messages in-game aren't shown with this alert dialog, that's part of `LauncherConnecting` in content.
> 
> In general this dialog is pretty bad design wise and not used much, but I don't mind merging this as it can't really hurt.

Thanks will go do another PR for that one too.

2024-08-05 14:39 UTC, PJB3005 requested changes

2024-08-05 14:39 UTC, PJB3005 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +                    Text = "Copy",
Localize this.

2024-08-05 14:39 UTC, PJB3005 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +                };
You can just give the parent container `HAlignment.Right` and then you don't need to bother with a spacing control like this.

2024-08-08 01:03 UTC, Titian3 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +                    Text = "Copy",
Also localized the title as it was a hardcoded default param.

2024-08-08 01:05 UTC, Titian3 commented on Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
> +                };
Updated this and removed all unnecessary comments etc too.

2024-08-08 16:56 UTC, merged