Fix ResPath CanonPath
space-wizards/RobustToolbox pull request #5452
Opened 2024-09-18 07:40 UTC by metalgearsloth

Apparently this is supposed to standardise to / but this isn't always the case. Alternatively we could just assert for performance reasons I'm good with either. The comment as written says this should happen. I think it's mostly DirLoader stuff can end up mixing the separators around.

2024-09-18 07:40 UTC, metalgearsloth commented on Robust.Server/ServerOptions.cs
> +        public ResPath PrototypeDirectory { get; init; } = new(@"/Prototypes/");
This is just to be consistent with client.

2024-09-18 13:31 UTC, PJB3005 reviewed
Uh, what does this fix? You absolutely shouldn't be able to pass a `\` into a `ResPath` and expect it to work.

2024-09-22 15:37 UTC, PJB3005 commented
Adding a significant amount of logic to the constructor for `ResPath` also is a bad idea. It's intentionally designed to "just" be a string wrapper for performance, this breaks that.

2024-09-28 04:08 UTC, metalgearsloth commented
> Adding a significant amount of logic to the constructor for `ResPath` also is a bad idea. It's intentionally designed to "just" be a string wrapper for performance, this breaks that.

I'll chuck an assert in? IIRC it's conversions to/from file directories but would have to double-check.

2024-09-28 04:36 UTC, metalgearsloth commented
Okay I double-checked my hot reload branch and it's just the getcontentroot iterator so I can just sanitise those inputs before they go to respath? There might be some other ones internally but nothing that seemed to trip the assert so would need to find them as they come up.

2024-09-28 15:40 UTC, PJB3005 requested changes

2024-09-28 15:40 UTC, PJB3005 commented on Robust.Shared/ContentPack/ResourceManager.cs
> +                    var rootDir = loader.GetPath(new ResPath(@"/")).Replace(Path.DirectorySeparatorChar, '/');
This should be done by the dir loader, not the resource manager.

2025-03-08 03:54 UTC, metalgearsloth commented on Robust.Shared/ContentPack/ResourceManager.cs
> +                    var rootDir = loader.GetPath(new ResPath(@"/")).Replace(Path.DirectorySeparatorChar, '/');
yeah nfi what I was thinking

2025-03-08 04:02 UTC, merged