EntityPrototypeView has become disposable
space-wizards/RobustToolbox pull request #5466
Opened 2024-09-27 06:59 UTC by Ertanic

EntityPrototypeView does not delete an entity unless done manually via `SetPrototype(null)`. This causes the test to fail in https://github.com/space-wizards/space-station-14/pull/32339.

2024-09-28 04:25 UTC, metalgearsloth commented on Robust.Client/UserInterface/Controls/EntityPrototypeView.cs
> +    }
ExitedTree handles this

2024-09-28 05:14 UTC, Ertanic commented on Robust.Client/UserInterface/Controls/EntityPrototypeView.cs
> +    }
> ExitedTree handles this, it seems like you're having an issue elsewhere.

Before adding explicit entity deletion in the `Dispose` method, [DeleteAllThenGhost](https://github.com/space-wizards/space-station-14/blob/caac678fa6e5c5a8f0602dd5b4ffbf1eea3b34ef/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs#L9) test was crashing with 100% chance. In debug mode, breakpoints and call stack I realized that the problem is in EntityPrototypeView, it generates undeletable entities. For some reason `ExitedTree` method does not work. As I [wrote](https://ptb.discord.com/channels/310555209753690112/310555209753690112/1289076513391644694) in Discord, after adding `Dispose`, the test started to pass.

2024-09-28 06:16 UTC, metalgearsloth commented on Robust.Client/UserInterface/Controls/EntityPrototypeView.cs
> +    }
Seems like ExitedTree is not being called when it should be then?

2024-09-28 06:19 UTC, Ertanic commented on Robust.Client/UserInterface/Controls/EntityPrototypeView.cs
> +    }
> Seems like ExitedTree is not being called when it should be then?

It looks like, but `Dispose` is enough for my PR to work

2024-09-28 21:52 UTC, PJB3005 requested changes
This is not a good fix, find the real root cause.

2024-09-29 00:50 UTC, Ertanic commented
> This is not a good fix, find the real root cause.

I found the bug, I fixed it as far as my motivation goes. My PR will probably work. I don't really care why something doesn't work. If you are not satisfied with my solution - I can close the PR, and look for the root cause yourself. I won't do more than that. My PR is aimed at making my main PR work, not at fixing your engine.

2024-09-29 01:41 UTC, metalgearsloth commented
If you want to fix the other bug feel free to open another PR then.

2024-09-29 01:41 UTC, closed without merging