Night Vision Light Sensetivity
space-wizards/RobustToolbox pull request #5486
Opened 2024-10-07 07:10 UTC by Rinary1

adds light sensetivity for night vision systems.

2024-10-07 07:16 UTC, metalgearsloth requested changes

2024-10-07 07:16 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +
GL.Clear is already being called above.

2024-10-07 07:16 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +
Rather than baking this in this is better done on the content side or alternatively via event.

2024-10-07 07:19 UTC, metalgearsloth requested changes
Also another option is just drawing a texture to the LightRenderTarget in an overlay depending how you want to do it.

2024-10-26 13:24 UTC, Rinary1 commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +
> Rather than baking this in this is better done on the content side or alternatively via event.

wdym?

2024-10-27 04:45 UTC, darkrell commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +
> Rather than baking this in this is better done on the content side or alternatively via event.

Could you explain how you see this? Sending an event here would be incredibly inefficient.

2024-10-27 04:47 UTC, darkrell commented
> Also another option is just drawing a texture to the LightRenderTarget in an overlay depending how you want to do it.
Also, that solves a slightly different issue. we would still prefer to have local options for users to adjust their sensitivity to light

2024-10-29 01:21 UTC, metalgearsloth commented on Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
> +
As opposed to calling GL.ClearColor twice in a row...?

The lighting cap is incredibly small anyway.

2024-10-29 01:21 UTC, metalgearsloth commented
> Also, that solves a slightly different issue. we would still prefer to have local options for devs to adjust species sensitivity to light

I still don't see why this can't just update the lighting render target from content.

2024-10-29 01:23 UTC, metalgearsloth commented
At this stage the only useful part of this I see is adding more customisation around what clearcolor is used but none of the other changes are necessary on the engine.

2024-10-30 18:32 UTC, ss14-Starlight commented
@metalgearsloth 

Rewritten to use the event; is it better now?

2025-02-07 07:54 UTC, closed without merging