Replace all obsolete usages of MapGridComponent methods
space-wizards/RobustToolbox pull request #5547
Opened 2024-11-30 22:52 UTC by MilenVolf

For [#33279](https://github.com/space-wizards/space-station-14/issues/33279)

2024-11-30 22:54 UTC, MilenVolf commented on Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
> +                var gridPosition = pManager.EntityManager.System<SharedMapSystem>().MapToGrid((EntityUid)gridUid!, pManager.EyeManager.ScreenToMap(Vector2.Zero));
I hate it here

2024-11-30 22:55 UTC, MilenVolf commented on Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
> +                var gridUid = pManager.EntityManager.System<SharedTransformSystem>().GetGrid(MouseCoords);
Not sure about this one with MouseCoords

2024-12-02 17:33 UTC, MilenVolf commented on Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
> +                var gridUid = pManager.EntityManager.System<SharedTransformSystem>().GetGrid(MouseCoords);
Nah, it's good

2024-12-14 17:04 UTC, PJB3005 requested changes

2024-12-14 17:04 UTC, PJB3005 commented on Robust.Client/Placement/PlacementManager.cs
> +        private readonly ISawmill _sawmill = default!;
You're never initializing this?

2024-12-14 17:04 UTC, PJB3005 commented on Robust.Client/Placement/PlacementManager.cs
> +                _sawmill.Log(LogLevel.Warning, nameof(PlacementManager), $"Invalid placement mode `{CurrentPermission.PlacementOption}`");
This is incorrect, you're passing `nameof(PlacementManager)` to the actual log message.

2024-12-15 04:06 UTC, MilenVolf commented on Robust.Client/Placement/PlacementManager.cs
> +                _sawmill.Log(LogLevel.Warning, nameof(PlacementManager), $"Invalid placement mode `{CurrentPermission.PlacementOption}`");
Fixed in [9258fb7](https://github.com/space-wizards/RobustToolbox/pull/5547/commits/9258fb7f62c4c56cf8c55f54e395a6e07868ad54)

2024-12-18 17:46 UTC, PJB3005 approved these changes

2024-12-18 17:46 UTC, merged