Always request publickey on connection and perform serverside validation of client version
space-wizards/RobustToolbox pull request #5563
Opened 2024-12-19 03:29 UTC by Simyon264

This PR allows clients to connect to other servers running the same codebase. Useful for multiserver servers such as minigame forks.

2024-12-19 03:32 UTC, Aidenkrz approved these changes

2025-07-19 20:20 UTC, PJB3005 requested changes

2025-07-19 20:20 UTC, PJB3005 commented on Robust.Shared/Network/NetManager.ServerAuth.cs
> +                if ((engineVersion != expectedEngineVersion || clientVersion != expectedClientVersion)
Engine version is allowed to mismatch the server due to security updates. This check isn't correct.

2025-07-19 20:20 UTC, PJB3005 commented on Robust.Shared/Network/NetManager.ClientConnect.cs
> +                var keyBytes = encRequest.PublicKey;
Always getting the public key dynamically breaks the security model so that `ss14s://` isn't actually secure anymore. You should be getting the public key from the server's HTTP API dynamically. Normally the launcher does this.

2026-05-08 10:06 UTC, closed without merging

2026-05-08 10:06 UTC, PJB3005 commented
Stale.