Augment audio system with the ability to have captions
space-wizards/RobustToolbox pull request #5567
Opened 2024-12-22 04:42 UTC by pontaoski

Currently based on top of #5540, look at the changes of the latest commit only (or look at https://github.com/pontaoski/RobustToolbox/pull/1)

Mainly manages `CaptionComponent`s attached to the audio entities whenever they should display a visible caption. Can't use a `Caption` field on the `AudioComponent` due to the `ComponentTreeSystem` wanting to listen to the `ComponentStartup`/`ComponentShutdown` events that are already being listened to by the client `AudioSystem`.

2025-05-10 11:32 UTC, metalgearsloth requested changes

2025-05-10 11:32 UTC, metalgearsloth commented on Robust.Client/Audio/AudioSystem.cs
> +
Already a dependency on systems.

2025-05-10 11:32 UTC, metalgearsloth commented on Robust.Client/Audio/AudioSystem.cs
> +        if (_entityManager.TryGetComponent(uid, out CaptionComponent? caption) && _entityManager.TryGetComponent<TransformComponent>(uid, out var xform))
Use the other trygetcomponent as it has a direct xformcomp overload.
Also add EntityQuery<CaptionComponent> as well.

2025-05-10 11:32 UTC, metalgearsloth commented on Robust.Client/ComponentTrees/CaptionTreeSystem.cs
> +{
Needs doc comments explaining please.

2025-05-10 11:32 UTC, metalgearsloth commented on Robust.Client/ComponentTrees/CaptionTreeSystem.cs
> +
Same here on entmanager + trygetcomp.

2025-10-03 18:18 UTC, slarticodefast commented on Robust.Client/Audio/AudioSystem.cs
> +        if (_captionQuery.TryGetComponent(uid, out var caption) && EntityManager.TryGetComponent(uid, out TransformComponent? xform))
No need to do a TryComp for the TransformComponent, all entities have that component.
And if it was deleted the first one would fail.
So you can just use the `Transform(uid)` shorthand, which uses a query

2025-10-03 18:18 UTC, slarticodefast commented on Robust.Shared/Audio/Components/CaptionComponent.cs
> +    public LocId? Caption { get; set; }
add documentation to all of these

2025-10-03 18:18 UTC, slarticodefast commented on Robust.Shared/Audio/SoundCollectionPrototype.cs
> +    public LocId? Caption { get; private set; }
documentation

2026-08-15 00:09 UTC, closed without merging