Illumination measuring system to determine how "lit up" entities are
space-wizards/RobustToolbox pull request #5574
Opened 2024-12-23 22:15 UTC by Chubbygummibear

Please bear with me since this is my first large PR and like 2nd PR ever for SS14/RT, so I expect I made a lot of mistakes that will need to be rectified upon review.

# Overview
This is an entirely new system that is designed to serve as a tool for content systems that would like to know the illumination level of a given entity. This is achieved by querying a PointLightComponent Tree on the server to determine which lights are nearby, then uses a raycast query of the Occluder Tree System to check for occlusion. Any lights after that which are both in range and unoccluded have their light power multiplied by an attenuation function to get the final light value applied to the entity. Only the most powerful light value on the entity is kept. That value is cached in the corresponding component and returned upon calling the TryGetLightLevel function.

The system does nothing on its own and needs to be triggered by other systems calling TryGetLightLevel which will cause the light calculations to occur. There is a cooldown of 0.5 Seconds on getting the light level re-calculated unless a boolean to force the update is called. If many calls are made to the function in a short time span, the cached value will be returned without rerunning the calculation. This way, if numerous systems call for the light level in the same tick, and every tick. The most expensive operation will not be called every time.

# Demonstration

https://github.com/user-attachments/assets/f04bca65-624b-4e4f-8698-29f814449d6c

It does work with masked lights as well, although i had to refactor the way light mask prototypes work to accomplish this.

# Limitations and concerns
- Naturally performance is a concern, as this is using raycasting frequently to check for occlusion. I did my best to mitigate the impact by implementing a cooldown for how often the system should be allowed to do so, as well as implementing the ability to define cooldowns on a per system that calls this system basis.
- Animations is a big one. With animations like spinning lights, flickering lights, and dimming areas being handled entirely on the client, there's no way to access this effectively on the server to know that the lights have changed in some way.
- Client and Server PointLightTrees function independently of one another. This is due to the fact that the `SharedPointLightComponent` is abstract, and ComponentTrees do not like abstract or virtual classes at all. To make these trees synced, all the Client and Server PointLightComponent attributes would need to be moved up into the Shared space. Which in and of itself is a large refactor.
- Small gripe but I'm not sure if `LightSensitive` makes sense anymore, because initially this component/system was going to send out networked events on regular intervals, but i later opted to just put the onus on other systems to call this one. Maybe it should be `EntityIllumination` or something

Anwyay, I did my best to bring back this functionality that was pretty core to old SS13 and hope we can work together to get this in and further develop with the new design space

2024-12-30 10:14 UTC, Fansana commented
I would love this feature,

2025-03-08 03:37 UTC, metalgearsloth requested changes
I don't think the changes are that bad however I think you need to consider the fact content will likely need to call this inside of parallelism due to how expensive it will be even after you optimise it.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +
Please don't just copy-paste unperformant code from content to engine. This raycast doesn't even work properly and should be using the new raycastsystem and avoid allocating so much.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
This is just duplicating the sub anyway? This method is pointless as is.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
Resolving getentityquery every time isn't cheap, is this supposed to be on the system.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +        {
You're resolving worldposition twice for no reason, between the AABB and MapCoordinates.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
Disabled lights shouldn't even be stored in the lighttree, it's a massive waste of performance to be moving hundreds of these (PDAs for example) per tick.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            var calculatedLight = 0f;
Raycasting is significantly more expensive than checking illumination contribution if we're just going to take max and not accumulate them (though I suspect not accumulating will cause other issues) so you're better off doing that first and earlying out.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
TryDistance is also too expensive to use when you already have mapcoordinates for both above. It's doing a dozen+ trycomps when you can just do a vector subtraction.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
The query is making no distinction between clientside vs shared lights so client and server will inherently mispredict values (ignoring the fact that it will be mispredicted anyway due to ping).

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            }
Lots of redundant Math.Abs here.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
This should be doing NextUpdate so it applies properly on first tick.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +
Please don't do this, you're misunderstanding what containeroccluded is for. There's a reason UpdateEntity is the method updating this.

Containers are recursive so this event doesn't get fired off a lot of the time. E.g. a PDA light will never fire this event because it's a nested container.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +
Content should not be setting this as they will break contained lights so remove as mentioned above.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/LightMaskPrototype.cs
> +[Prototype("lightMask")]
Redundant string.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/LightMaskPrototype.cs
> +}
Redundant datafield strings, also why is it default null suppress this will just blow up if hot reloaded.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/LightMaskPrototype.cs
> +}
No reason not to be a struct also datafield strings redundant, and don't just do null suppress.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/LightSensitiveComponent.cs
> +
These should really be getting saved as datafields considering they're stateful

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/PointLightComponentState.cs
>  }
I think it's sufficient enough that this gets derived on UpdateEntity and doesn't need networking.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Components/Light/SharedPointLightComponent.cs
>      }
Needs engine CL as a breaking change, also datafield string redundant.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +        [Dependency] private readonly OccluderSystem _occluder = default!;
Please document your systems, especially on engine.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +
You should be checking if the value is equal before dirtying as dirtying is expensive.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +}
Same here, delete all of this. Even GetAngle should not be getting called in a hot loop when you already have the data inside of the loop, just assume every transform method is 1,000 times more expensive than the basic maths operations.

2025-03-08 03:37 UTC, metalgearsloth commented on Robust.Shared/GameObjects/Systems/SharedPointLightSystem.cs
> +
As above delete as content will kneecap itself with this.

2025-04-14 06:16 UTC, metalgearsloth commented
Also I would note that content can entirely override this as it sees fit, e.g. they can draw directly to the light render target for tile emissive or rooves or whatever and it probably needs an event attached.

2025-04-14 06:44 UTC, metalgearsloth commented
Note that I don't expect you to actually do it in this PR but I do expect content PRs to be frozen from using this until it is implemented.

2025-04-14 19:17 UTC, Chubbygummibear commented
> Note that I don't expect you to actually do it in this PR but I do expect content PRs to be frozen from using this until it is implemented.

i would be willing to try fixing this up in a more optimized manner and in a way that better fits into the content/engine schema, but I would definitely need help since I'm very unfamiliar with the ECS paradigm, and content/server/shared system. I have enough experience to get things working, but when you say like "consider parallelism", or when I should or shouldn't dirty a component, it's totally new to me.

2025-07-03 18:43 UTC, Chubbygummibear commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
the problem i was trying to solve here is that the ComponentTreeSystem automatically subscribes to ComponentStartup for the purpose of updating the tree. However the PointLightSystem also subscribes to the Startup event because it wants to call UpdatePriority for the metadata. This caused a duplicate subscription error that i could not figure out how to get around without making a hacky call chain. I tried asking around the server but didn't find a good workaround to the duplicate subs issue

2025-07-03 18:49 UTC, Chubbygummibear commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
i'm afraid i don't understand what you mean by "on the system". this behavior is just copied from the AmbientSoundTreeSystem, since a while into this project, i reasoned that the local sound system that used line of sight and occlusion to determine what an entity "heard" wasn't all that different from light. However i do recognize that the cost would be different performing this on the server as opposed to the client

2025-07-03 19:23 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
what would be a good solution to avoiding mispredictions? also i would like to make the component trees between client and server synchronized, but i don't know the best way to do that when i tried to put everything in Shared before and it caused a large number of errors because it did not like the abstract and virtual methods touching the component trees

2025-07-04 16:45 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +        {
yeah that's true. i wanted the sanity checks that come with the GetMapCoordinates or GetWorldPositionRotation, but those don't return every value i need at the same time, so i'll probably add a new function to this system that's a copy of those but returns all the values i need in one pass

2025-07-04 17:03 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
good point

2025-07-04 17:03 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            }
will simplify to a single var

2025-07-04 17:04 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +
ah yeah that makes sense. i'll change it to that

2025-09-19 08:02 UTC, ElectroJr requested changes

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +    protected override bool Recursive => true;
Recursive component trees are really expensive, and probably need to be re-worked somehow. If there's **any** recursive tree, then anytime a MoveEvent is fired it has to recursively iterate through all children of that entity and try to fetch components. Currently there are no server-side recursive trees for specifically that reason, it'd hurt server performance quite a bit. E.g,, players generally contain many (100+) entities, so just handling player movement would be relatively expensive.

I'm not sure what the best solution in the long term is. I think recursive trees should be replaced with some setup where entities with the component being being attached to other entities should add a component & metadata flag to their parent. I.e., the mover entity has some ListListComponent that points directly to any children with a light component, thus avoiding the recursive move events. But thats beyond the scope of this PR and probably something I'll work on

But at the very least for now this whole tree should be locked behind a cvar for any server that doesn't want to use the feature. Even if recursive trees are updated to be faster, it should probably stay toggleable. I.e., give the base tree system some virtual `IsEnabled` bool that skips init, shutdown, and maybe prints warnings/errors when people try to use queries. Being able to disable the trees is probably just something I should've added from the beginning. E.g., I don't even know if opendream or whatever else needs to use things like the ocluder & light trees.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
One of the common solutions is to have some startup event that exists specifically for that component, e.g. `GridStartupEvent` or `TransformStartupEvent`. And thats probably a better solution in case other content systems want to extend light startup logic without having to somehow give all lights a new component.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +
Sloth just means having a field on the system itself that stores the query. I.e. use a `private EntityQuery<TComponent> _query` field  that gets set on system init. Regarding the other tree systems, those should be updated. I either messed that up when writing them or maybe I just wrote them system before we started caching/reusing queries.

Though in the specific where its for TransformComponent or MetadataComponent, you shouldn't even need to cache the queries at all, as metadata system already does that for you. I.e., just using `Transform(uid)` will use `EntityManager.TransformQuery.GetComponent(uid)`

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/Components/PointLightComponent.cs
> +        public EntityUid? TreeUid { get; set; }
Except for the `DynamicTree` field, cant all of the fields be moved to shared?
Though like I said in another comment, you can probably move even that to shared if you get rid of the new constraint.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Shared/GameObjects/Components/Light/LightMaskPrototype.cs
> +[Prototype("lightMask")]
what sloth said + data fields should all default to vv read+write.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Shared/GameObjects/Components/Light/LightMaskPrototype.cs
> +}
I thought hot reloading would work fine with required data-fields? Though this probably can just be null or optional.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +public sealed class LightTreeSystem : ComponentTreeSystem<LightTreeComponent, PointLightComponent>
> Client and Server PointLightTrees function independently of one another. This is due to the fact that the SharedPointLightComponent is abstract

I **think** you can just remove the `where TComp : new()` requirement in `ComponentTreeSystem<TTreeComp, TComp>`? It doesn't seem to actually be required, and then you can just point to the abstract shared component, and have a shared tree system. Thought you might still want a server/client specific version that inherits from the abstract shared system for `DoFrameUpdate` or cvar toggling.

If you do this, you might have to update some of the rendering code so it casts shared light comp to the client comp to access the mask texture, but its probably worth it to avoid duplicating the systems

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +    {
This just seems like a variant of physics system method that also returns the world position? If thats the case, that should just be an overload in physics system, not a method here.

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +            TState state, Func<EntityUid, TState, bool> predicate, bool ignoreInsideBlocker = true, IEntityManager? entMan = null)
I didn't read through this all that carefully, but I assume this just just a direct port of content's `ExamineSystemShared.InRangeUnOccluded` to engine? I don't know if this is the best spot for it, but I guess `OccluderSystem` is client-side. Though maybe its better in a shared point light system?

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +public sealed class LightSensitiveSystem : SharedLightSensitiveSystem
I think engine should just provide a more minimalist "LightLevel" system that can be used to compute the light level at a given position, probably with the caveat in the documentation that its generally expensive. 

Then content can use that to do more complex things if it wants (e.g., cache it on comp on entities that auto-update, or create a tile map or something like that)

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +    public sealed class PointLightSystem : SharedPointLightSystem
indent

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +        _lightTree.QueueTreeUpdate(uid, component);
This shouldn't be getting called here, it should be getting used wherever something is being modified that will require a tree update.

get state gets called once per player that needs to receive a state, not once per dirty

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +
This was originally my bad, I should've made the client-side method internal a while ago. Seeing as this has breaking changes anyway may as well make it internal now. And again, hopefully the tree system can be moved to shared so that most of the code duplication can be removed and this can all be handled in the shared system

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            {
I think this if block should be extract to a separate apply mask method to make it easier to read

2025-09-19 08:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +                    calculatedLight = Math.Max(calculatedLight, coneLight);
`lightComp.Energy * attenuation * attenuation` appears in all branches, so you can probably just move that before the if-mask check.

Also `calculatedLight` is always zero on this branch up until the math.max, so I'm not sure why you need the max

2025-09-19 08:29 UTC, ElectroJr commented on Robust.Server/ComponentTrees/LightTreeSystem.cs
> +    protected override bool Recursive => true;
See #6211

2025-09-20 06:46 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            var attenuation = 1 - (denom * denom);
It's probably worth actually making this match how `float val` is calculated in `light_shared.swsl

2025-09-20 06:46 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            // I really don't want to deal with multiplicative or additive illumination
IMO its probably worth supporting this I think you'd just need to do what the light shader does. I.e., compute `val` like in `light_shared.swsl`, multiply the light's color (a "black" light should have zero illumination), add all the colors together, and then map that somehow onto an illumination value. The specifics of how the color -> illumination mapping is done can always be changed later.

2025-09-20 06:46 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            var (lightComp, lightXform) = val;
IMO this should default to ignoring all lights with `LightComponent.CastShadows` set to false, as they should all be quite small lights and it'd help a bit with performance

2025-09-20 07:02 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +        {
This should stay in shared code, and it also has a hidden conflict with #6160 due to the missing `Falloff` & `CurveFactor`

2025-09-20 08:07 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +    {
I'm also not sure if this is really needed, because we're not averaging the light level over an entity's bounds, its just being computed at the entity's centre. So you should be able to just use a "point box" (`Box2(pos, pos)`) to get all lights that intersect the point.

2025-09-20 08:21 UTC, ElectroJr commented on Robust.Shared/GameObjects/Systems/SharedLightSensitiveSystem.cs
> +            TState state, Func<EntityUid, TState, bool> predicate, bool ignoreInsideBlocker = true, IEntityManager? entMan = null)
Actually, there's quite a few problems with this method which also needs fixing in content. Instead of just listing them all and making you fix them I'm just going to create a separate PR that migrates the method to engine and fixes all the issues I can think of.

2025-09-24 18:38 UTC, Lumminal commented
it'd be amazing if this was finished properly, we really need it to unlock a new area of content (light-based mechanics). Author doesn't seem active on this anymore so its kinda sad

2025-09-24 20:46 UTC, Chubbygummibear commented
> it'd be amazing if this was finished properly, we really need it to unlock a new area of content (light-based mechanics). Author doesn't seem active on this anymore so its kinda sad

oh don't worry i'm still suffering away at this. it got review again because i poked different devs. i was pretty confused on what needed to be done and the best way to do it, so i needed head dev help. i've had like 2 different ss14 servers poke me recently asking if it would be possible to get a portable version of this, but not really without touching the engine, so i basically have to keep at this even though it's in a nightmare state of bandaids and workarounds

2025-10-03 19:56 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +        {
Understood, but I was also hesitant to touch the shared code version because it was static and cannot be overwridden. Do you know if it's static for a specific reason? other component states just seem to be internal, virtual, or abstract

2025-10-03 19:57 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            var (lightComp, lightXform) = val;
I went back and forth on this a lot and maybe the best option is a cvar for that because on one hand, calculating lights that don't cast shadows means every glowing corn cob from botany would turn up in the light query for every lightsensitive entity in the area, which i'm sure would kill performance, but on the other hand i saw many entities that don't cast shadows such as glowing floor tiles which i believe SHOULD be factored in

2025-10-03 19:59 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            // I really don't want to deal with multiplicative or additive illumination
color has now been factored in by getting the Max of the RGB values, which is how luminosity is determined for HSL. however i still don't have a good answer for getting light mask calculations to multiply against the light level, which may need to be a future separate PR where we read the pngs as a 2d matrix of rgb values

2025-10-03 20:00 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            var attenuation = 1 - (denom * denom);
mission accomplished, my attenuation has been removed in favor of the shader's formula

2025-10-03 20:00 UTC, Chubbygummibear commented on Robust.Server/GameObjects/EntitySystems/LightSensitiveSystem.cs
> +            {
on the todo list for if we can come up with a better way of extracting a mask value from the images of the mask itself, or we just stick with what i have now

2025-10-09 06:39 UTC, ElectroJr commented on Robust.Server/GameObjects/EntitySystems/PointLightSystem.cs
> +        {
No idea why it was static, theres no real reason it needs to be.

2026-03-05 20:49 UTC, Chubbygummibear commented
we are merge conflict free once again

someone please end this nightmare

2026-03-08 05:58 UTC, Golubgik commented
you won't give up 💪

2026-07-06 16:58 UTC, Chubbygummibear commented
this pr may be one of the oldest on this repo but i assure you it is still a bear trap waiting for another maintainer to acknowledge me. on god whoever does is going to be stuck with me

2026-07-06 17:46 UTC, Chubbygummibear commented
<img width="1215" height="940" alt="image" src="https://github.com/user-attachments/assets/dd675297-f9d8-4e54-aead-099f9636dc11" />

2026-07-23 13:09 UTC, merged