Add WeakEntityReference
space-wizards/RobustToolbox pull request #5577
Opened 2024-12-27 07:18 UTC by ElectroJr

This adds a new `WeakEntityReference` struct that is intended to be used by component data-fields to refer to entities that may or may not still exist, or in the case of `WeakEntityReference<T>` that might no longer have an otherwise required `T` component. Feel free to suggest better names for the struct, maybe it should just be abbreviated?.

## Why
The current convention is that a a non-null EntityUid? (or NetEntity) should correspond to a valid non-deleted entity. Saving or loading entities that have components with invalid / deleted entity uids currently logs an error or completely fails, because the assumption is that you forgot to include an entity in the save or something has gone wrong. 

Ensuring that entities delete or clear references to themselves when deleted or components are removed is a PITA (device linking, ghosts following, etc). So it'd be nice to have some kind of struct that points to an entity that may or may not still exist, that doesn't need to be manually cleaned up, and which entity serialization knows it can just ignore if the entity is deleted or not included in the save file. Though it also shouldn't get overused, its obviously slower than directly using an EntityUid.

## How

The struct is is just a simple wrapper around `NetEntity`, and there are some new IEntityManager methods & EntitySystem proxy methods to convert back to either an `EntityUid?` or `Entity<T>?` and is meant to be used with 'is' casting (i.e., `if (Resolve(weakRef) is not {} ent)`). Previously it used an EntityUid instead of NetEntity, but I switched mostly just to avoid having to update the auto component state generator.

2025-03-28 17:53 UTC, Tayrtahn commented
This would be very helpful for solving issues like https://github.com/space-wizards/space-station-14/issues/32642, and the more general problem of tracking projectile sources.

2025-06-30 16:55 UTC, Tayrtahn commented
A few suggested additions:

`IEntityManager.GetWeakReference(EntityUid uid)` - as a shortcut for `new WeakEntityReference(sEntMan.GetNetEntity(uid))`

`IEntityManager.TryResolve(WeakEntityReference weakRef)` - expand the suite of Resolve methods for parity with the `NetEntity` resolvers.

2025-07-01 00:43 UTC, Tayrtahn commented on Robust.Shared/GameObjects/EntitySystem.Proxy.cs
> +    protected EntityUid? Resolve(ref WeakEntityReference weakRef)
Since these don't modify the reference, should they use `in` instead of `ref`?

2025-07-06 16:07 UTC, Tayrtahn commented
Also consider adding these: https://github.com/ElectroJr/RobustToolbox/pull/1 https://github.com/ElectroJr/RobustToolbox/pull/2

2025-07-10 07:39 UTC, ElectroJr commented on Robust.Shared/GameObjects/EntitySystem.Proxy.cs
> +    protected EntityUid? Resolve(ref WeakEntityReference weakRef)
I've changed them to match the EntityManager method signature. I think this was just a holdover from an older version.

2025-07-10 07:41 UTC, ElectroJr commented
> `IEntityManager.TryResolve(WeakEntityReference weakRef)` - expand the suite of Resolve methods for parity with the NetEntity resolvers.

I've added `TryGetEntity` methods

> Also consider adding these

I've merged all those changes i

2025-07-11 16:12 UTC, Tayrtahn requested changes
Should remove `ref` from these too.

2025-07-11 16:12 UTC, Tayrtahn commented on Robust.Shared/GameObjects/EntitySystem.Proxy.cs
> +    protected WeakEntityReference GetWeakReference(ref EntityUid uid, MetaDataComponent? meta = null)
```suggestion
    protected WeakEntityReference GetWeakReference(EntityUid uid, MetaDataComponent? meta = null)
```

2025-07-11 16:12 UTC, Tayrtahn commented on Robust.Shared/GameObjects/EntitySystem.Proxy.cs
> +    protected WeakEntityReference? GetWeakReference(ref EntityUid? uid, MetaDataComponent? meta = null)
```suggestion
    protected WeakEntityReference? GetWeakReference(EntityUid? uid, MetaDataComponent? meta = null)
```

2025-07-23 01:09 UTC, Tayrtahn approved these changes

2025-07-29 15:12 UTC, merged