ECS - ComponentManager Restructure
space-wizards/RobustToolbox pull request #620
Opened 2018-07-24 21:18 UTC by Acruid

* Switch from storing the components on each entity to a central database inside of ComponentManager.
* Better deferred component remove.
* Turn the IEntity component functions into proxies of the ComponentManager functions.
* Remove Update() base function from Components. If components need to update, an EntitySystem needs to do it.

Resolves #618.

2018-07-25 00:30 UTC, Acruid commented on SS14.Server/Maps/MapLoader.cs
> +                    var entity = _entityMan.CreateEntity(protoName);
@PJB3005 Don't forget to change this in your branch.

2018-07-26 19:59 UTC, PJB3005 requested changes

2018-07-26 19:59 UTC, PJB3005 commented on SS14.Client/GameObjects/EntitySystems/AppearanceSystem.cs
> +                    typeof(AppearanceTestComponent),
`AppearanceTest` is a complete separate thing from `Appearance`. It just sets a test key on/off periodically.

It shouldn't be handled by this system, that or make it a separate query that gets ran before. Right now the way you've got that trygetcomponent set up it'll break and never be ran.

2018-07-26 19:59 UTC, PJB3005 commented on SS14.Client/GameObjects/EntitySystems/SpriteSystem.cs
> +                    typeof(ISpriteComponent),
Can't this use `TypeEntityQuery` too?

2018-07-26 19:59 UTC, PJB3005 commented on SS14.Shared/GameObjects/Component.cs
> +                throw new InvalidOperationException("Cannot Add an Initialized entity!");
You mean component instead of entity here?

2018-07-26 21:06 UTC, PJB3005 approved these changes

2018-07-26 21:10 UTC, merged