Adds exception handling for the main loop.
space-wizards/RobustToolbox pull request #700
Opened 2018-10-29 21:07 UTC by ShiftyRail

Fixes #596. I think.

I have no idea if this is correct or not. Also, I don't really know how to send the return value in a meaningful way.

2018-10-29 23:02 UTC, PJB3005 requested changes

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +    class RuntimeLog
I'd just go ahead and make this class public to be honest.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +        private List<Exception> exceptions { get; set; }
You don't need the `{ get; set; }`, it's a private property after all.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +        private List<Exception> exceptions { get; set; }
Also, you're never actually initializing these lists so they'll throw null refs.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +        private Dictionary<Type, int> exp_count { get; set; }
This really isn't as useful as you think it'll be.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +            exp_count.Add(E.GetType(), exp_count[E.GetType()] + 1);
This will throw an exception reliably because `exp_count` won't contain the type the first time this is called.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +            var ret = "";
Use a [`StringBuilder`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=netframework-4.7.2) here.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +                    foreach (Object x in E.Data)
Looping over a dictionary returns a `KeyValuePair<object, object>`, not an enumerator over the keys like you clearly intended here. You want to do `foreach (var x in E.Data.Keys)`

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +                ret += "Exception in " + E.Source.ToString() + ", " + E.TargetSite.ToString() + ". \n";
Pretty sure the source is included inside the stack trace so this is probably redundant.

You may be better off just running `E.ToString()` and using that.

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +                ret += "Exception in " + E.Source.ToString() + ", " + E.TargetSite.ToString() + ". \n";
Also, you can do format strings with `$"Exception in: {E.Source} ..."`

2018-10-29 23:02 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> +                runtimeLog.AddException(exp);
Right now this just silently eats the exceptions with no way to be aware of them. The general idea behind the system is definitely a step in the right direction but taking out the logging is not a good idea.

2018-10-31 11:43 UTC, ShiftyRail commented
@psykzz What could end execution early, the throw ?

2018-10-31 11:44 UTC, psykzz commented
Yeah.

2018-10-31 11:55 UTC, ShiftyRail commented
I see. I tried it on a small project and you're right.
I am used to Byond's exception handling only killing the current method.

2018-10-31 19:57 UTC, captkirk88 commented
Your going to want to put the Cleanup(); in a finally block.

2018-10-31 21:32 UTC, PJB3005 requested changes

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> +                _mainLoop.Run();
It just occurred to me that because this try catch wraps the main `Run` method, you're still gonna have the game crash because the main loop will die on an exception.

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> +            System.IO.File.WriteAllText($"Runtime-{DateTime.Now.ToShortDateString()}", runtimeLog.Display());
This location is working directory relative so this won't always be next to the executable. See `PathHelpers.ExecutableRelativeFile`

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +public struct ExceptionAndTime
Don't put this outside the namespace.

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +            this.exceptions = new Dictionary<Type, List<ExceptionAndTime>>();
You can put this initializer inside the field declaration like in BYOND.

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +                ExceptionAndTime EandD = new ExceptionAndTime();
You're pretty much duplicating these 4 lines.

What I would do:

```cs
if (!exceptions.TryGetValue(E.GetType(), out var list))
{
    list = new List<ExceptionAndTime>();
    exceptions[E.GetType()] = list;
}

list.Add(new ExceptionAndTime
{
    exp = E,
    time = D,
});
```

2018-10-31 21:32 UTC, PJB3005 commented on SS14.Shared/Exceptions/RuntimeLog.cs
> +                ret.AppendLine($"{exceptions[T].Count().ToString()} exception {((exceptions[T].Count() > 1) ? "s" : "")} {T.ToString()}");
You don't need to explicitly call `ToString()` for arguments to format strings.

2018-11-20 08:39 UTC, PJB3005 requested changes
You need to register the runtime log class next to all the other IoC registrations. Check `GameController.cs`, `SS14.Server/Program.cs` and `SS14UnitTest.cs`

2018-11-20 08:39 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> -        private Shared.Exceptions.RuntimeLog runtimeLog;
You can put `[Dependency]` in front of this field, and then it'll automatically be filled in. You won't have to resolve it explicitly down below.

2018-11-20 08:39 UTC, PJB3005 commented on SS14.Shared/Timing/GameLoop.cs
> +                try
I think you put this `try` a bit to broad. If one of the handlers throws an exception the main loop's timing system could still mess up. You should wrap the `Update?.Invoke(this, simFrameEvent);` and such instead.

2018-11-20 08:40 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> +            System.IO.File.WriteAllText($"{PathHelpers.ExecutableRelativeFile(logPath)}/Runtime-{DateTime.Now.ToShortDateString()}", runtimeLog.Display());
You should use `System.IO.Path.Join` instead of string concat to make the file path.

2018-12-12 20:06 UTC, PJB3005 commented
@ShiftyRail Any chance of this being fixed?

2019-01-17 17:24 UTC, PJB3005 commented
Ding dong @ShiftyRail do you still want to finish this? I can take it off your hands if you'd prefer.

2019-01-18 00:54 UTC, ShiftyRail commented
Sorry school got me and then I forgot this
I'll get back to it tommorow and hopefully finish it this week-end

2019-01-19 17:02 UTC, ShiftyRail commented on SS14.Server/BaseServer.cs
> +            System.IO.File.WriteAllText($"{PathHelpers.ExecutableRelativeFile(logPath)}/Runtime-{DateTime.Now.ToShortDateString()}", runtimeLog.Display());
I couldn't find that method (my IDE didn't like it), but there is `Combine()` which apparently does the job.
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=netcore-2.2

2019-01-19 17:19 UTC, PJB3005 commented on SS14.Server/BaseServer.cs
> +            System.IO.File.WriteAllText($"{PathHelpers.ExecutableRelativeFile(logPath)}/Runtime-{DateTime.Now.ToShortDateString()}", runtimeLog.Display());
Ah hell you're absolutely right, I was mixing it up with Python.

2019-01-20 15:26 UTC, PJB3005 commented on SS14.Shared/Timing/GameLoop.cs
> +                try {
You still have this try placed way too broadly, put it around the `Invoke()` calls themselves only.

2019-01-21 10:38 UTC, ShiftyRail commented on SS14.Shared/Timing/GameLoop.cs
> +                try {
How about defining a `TryInvoke` method that wraps a try/catch around it ?

2019-01-21 10:40 UTC, PJB3005 commented on SS14.Shared/Timing/GameLoop.cs
> +                try {
I mean, sure, if it makes the code cleaner.

2019-02-23 19:33 UTC, ShiftyRail commented
I swear I had pushed something on this

2019-02-24 15:20 UTC, PJB3005 commented on SS14.Shared/Timing/GameLoop.cs
> +                catch (Exception)
Hrm? Not gonna catch this one?

2019-03-13 12:09 UTC, PJB3005 commented
Again, I'm totally fine with doing this myself.

2019-03-17 09:52 UTC, ShiftyRail commented
Then please do
Sorry for being slow and dumb

2019-03-21 22:22 UTC, PJB3005 commented
Superseded by #759

2019-03-21 22:22 UTC, closed without merging