Initial Discord Rich Presence support
space-wizards/RobustToolbox pull request #770
Opened 2019-03-28 08:47 UTC by occune

but we still need to tweak cosmetic aspects (like gamestates etc) and change the timer
huge thanks to @Injazz

2019-03-28 09:05 UTC, PJB3005 requested changes
I guess it would be nice to have some things like changing the status when connecting to a server but oh well.

2019-03-28 09:05 UTC, PJB3005 commented on BuildChecker/BuildChecker.csproj
> +  <ItemGroup>
I think you added these references to the RPC assembly in a bit too much projects there. It should only be in `SS14.Client`

2019-03-28 09:05 UTC, PJB3005 commented on SS14.Client/GameController.cs
> +            RichPresenceClient presence = new RichPresenceClient();
This should be made an IoC dependency:

https://github.com/space-wizards/space-station-14/wiki/IoC-(Inversion-of-Control)

2019-03-28 09:05 UTC, PJB3005 commented on SS14.Client/Utility/RichPresenceClient.cs
> +                State = "/vg/station",
Not sure whether referring to /vg/ directly is a good idea.

I think a more agnostic name might be better.

2019-03-28 09:05 UTC, PJB3005 commented on SS14.Client/Utility/RichPresenceClient.cs
> +                Timestamps = Timestamps.FromTimeSpan(10)
Shouldn't this value actually be incremented periodically? If it isn't wouldn't it be better to leave it out?

2019-03-28 09:05 UTC, PJB3005 commented on SS14.Client/Utility/RichPresenceClient.cs
> +        public void Free()
You should implement `IDisposable` and rename this to `Dispose()`.

2019-03-28 09:09 UTC, Injazz commented
I also want to note that there is a bug in DiscordRPC causing discord pipe to fail connection on Mono.
https://github.com/Lachee/discord-rpc-csharp/issues/54
you need fresh nuget version (which gonna update soon), or do it manually

2019-03-29 00:47 UTC, Silvertorch5 commented on SS14.Client/GameController.cs
> +            RichPresenceClient presence = new RichPresenceClient();
+1 ^

2019-04-02 17:22 UTC, PJB3005 commented
Superseded by #776

2019-04-02 17:22 UTC, closed without merging