Improved ItemLists
space-wizards/RobustToolbox pull request #863
Opened 2019-09-07 22:56 UTC by Zumorica

2019-09-08 14:01 UTC, PJB3005 requested changes

2019-09-08 14:01 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +        public void Add(Item item)
These `Item` instances should be made by the `ItemList` itself. With the current implementation you can theoretically add the same item to multiple lists at once, which will absolutely go haywire.

So more something like this:
```cs
public Item AddItem(string text, Texture icon = null, bool selectable = true)
```

2019-09-08 14:01 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +        public string Text;
All of these should be properties.

2019-09-08 14:43 UTC, Zumorica commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +        public string Text;
Done.

2019-09-08 23:11 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +        void ICollection<Item>.Add(Item item)
This doesn't actually prevent the item from being added by external code.

2019-09-08 23:28 UTC, Zumorica commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +        void ICollection<Item>.Add(Item item)
Hmm, should I make Add do nothing, or just outright remove the IList<Item> interface from ItemList?

2019-09-12 20:33 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +    public sealed class Item
Keep this as a nested class on `ItemList`

2019-09-12 20:49 UTC, gradientvera commented on Robust.Client/UserInterface/Controls/ItemList.cs
> +    public sealed class Item
Done! As I've mentioned in a comment, apparently [indexers compile into a property called "Item" by default](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers#remarks) so I had to use an attribute there.

2019-09-13 13:22 UTC, PJB3005 approved these changes

2019-09-13 13:23 UTC, merged