Implemented SpinBox and added a filter to LineEdit
space-wizards/RobustToolbox pull request #866
Opened 2019-09-10 18:38 UTC by ShadowCommander

Implemented SpinBox which is a number input using a LineEdit and a variable amount of Buttons.
Added a filter for input to LineEdits.
SpinBox.SetButtons takes two lists of ints and makes them into buttons surrounding the LineEdit.

I'd like some feedback on this.

2019-09-13 13:21 UTC, PJB3005 requested changes

2019-09-13 13:21 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/LineEdit.cs
> +        public Func<string, bool> IsValid;
Make this a property.
```suggestion
        public Func<string, bool> IsValid { get; set; }
```

2019-09-13 13:21 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +    public class SpinBox : BoxContainer
Make this inherit from `HBoxContainer` instead and remove the `Vertical` override.

2019-09-13 13:21 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +            var button = new Button { Text = text };
You can add these to the container and then change the order with `SetPositionInParent()`. Then you can add them immediately in this method instead of requiring an easy-to-miss `UpdateButtonOrder()` to be called.

2019-09-13 13:21 UTC, PJB3005 commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +        protected internal override void MouseWheel(GUIMouseWheelEventArgs args)
I'm not sure I like the idea of being able to control these with mousewheel. It always carries the risk of "scrolling through a page and accidentally changing something" which is really bad.

2019-09-13 20:06 UTC, ShadowCommander commented on Robust.Client/UserInterface/Controls/SpinBox.cs
> +        protected internal override void MouseWheel(GUIMouseWheelEventArgs args)
Ah, yeah, I forgot to add a check so that it only scrolls while the LineEdit is selected.

2019-09-15 18:07 UTC, PJB3005 approved these changes

2019-09-15 18:07 UTC, merged