Adds Midi playback, Midi input, etc.
space-wizards/RobustToolbox pull request #873
Opened 2019-09-26 15:03 UTC by Zumorica

Also:
- Added OnClosed event to ServerUserInterfaceComponent
- Added CloseAll method to ServerUserInterfaceComponent

2019-10-05 00:38 UTC, PJB3005 submitted a review, later dismissed

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        public static readonly string[] LinuxSoundfonts =
Make all of these private, and also make the implementation `internal`. You can keep the interface public though.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +#pragma warning enable 169
You're disabling the wrong warning here. CS0169 (the one you disabled) is "unused field". The one you want to disable is CS0649 (unassigned readonly field).

Muting the wrong warning here means that it won't be apparent if the field is unused at all, instead of simply ignoring the false positive caused by the compiler not recognizing `[Dependency]`.

Oh, also, the syntax for "enable" is actually "restore", which is probably why the syntax highlighter choked here.

It also can't hurt to mark these fields as readonly.

So apparently GitHub implemented multi-line review comments but didn't make multi-line suggestions, *sigh*:

```cs
#pragma warning disable 649
        [Dependency] private readonly IClydeAudio _clydeAudio;
        [Dependency] private readonly IResourceCache _resourceCache;
#pragma warning restore 649
```

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        /// <summary>
Put these doc comments in the interface declaration. Down here they're not so useful.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            _renderers.Add(renderer);
`List<T>` is not thread safe. You should `lock(_renderers)` the list while mutating and reading it to prevent data races.

Also, it's probably best if you added the renderer to the list when all the sound font loading is done, not before. So the renderer thread won't start rendering before the sound fonts are correctly loaded.

As an example of what can go wrong, with the implementation of `List<T>` in CoreFX, adding to the list while you are doing a classic for loop over the list like down below can end with you landing [perfectly between the increment of the size and the actual setting of the element](https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Generic/List.cs,205), potentially causing the render thread to pull a null and throw a nullref. Yay!

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                    if(renderer != null && !renderer.Rendering)
What could cause `renderer.Rendering` to be true here? As far as I can tell the only thing changing it is `Render` itself, which doesn't get called from any other thread, so it seems impossible to me for this to ever matter.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        public void Dispose()
It would probably be best wait on the renderer thread to stop with `.Join()` after setting `_alive` here, before running the rest of the shutdown.

Otherwise you might run into weird race conditions with the disposal of the renderers while they are being used.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            "/usr/share/soundfonts/FluidR3_GM.sf2",
Does Fluidsynth smartly avoid loading the entire soundfont if you only need a few instruments?
`FluidR3_GM.sf2` is 130 MB which is absolutely *insane* to load into the game at once.

Probably best to just exclude it from this list, IMO.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                }
This is not at all how you should be using `fixed`. The point of `fixed` is that you can safely access the data via the pointer INSIDE the block. Once your code goes outside the fixed block again (the return), the GC could decide to move the array and your pointer would get invalidated... then again you're not actually using that pointers later anyways it seems so cool..

You need to either pin the array with `GCHandle` to ensure the pointer remains valid, or copy the data to unmanaged memory (allocated/freed via `Marshal.AllocCoTaskMem`/`Marshal.FreeCoTaskMem`) where this isn't an issue.

That said, none of those solutions are ideal either. You're loading the ENTIRE sound font from disk in one read call. Depending on how the disk feels this can take quite a while, and the GC won't be very happy with you either. This loader callbacks API is designed explicitly so that you can wrap the underlying `Stream` provided by the OS with the read/seek calls, so fluidsynth can request the data in smaller chunks and avoid the aforementioned issues.

TL;DR keep the `Stream` around, map the `Read`/`Seek`/`Tell` callbacks onto the C# stream, get good performance.

By the way, the handle you're returning here is something for how C APIs work. C doesn't have capturing closures like C# does so they're necessary. They're not necessary with C# however so you can just return `IntPtr.Zero` here and then keep ignoring `IntPtr sfHandle` like you are below.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +        void OpenMidi(Span<byte> stream);
Slight nitpick: `Span<byte>` is a buffer, not a stream.

Also, you can make this use `ReadOnlySpan`, looking at the implementation.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            _source = AL.GenSource();
The OpenAL calls should really be isolated to Clyde.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                var empty = new Span<ushort>(new ushort[length]);
Move the array creation and pinning out of the loop, so it only has to happen once. It'll improve performance and reduce GC pressure.

Also, you don't need to wrap the array in a `Span<>` to be able to pin it.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                    AL.SourceQueueBuffers(_source, 1, new []{_buffers[i]});
Can't you do this for every buffer at once, after the for loop?

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +        bool IsMidiOpen { get; }
Are you ever supposed to be able to play both a midi file and from input with the same renderer? If not, make these two properties represented with an enum and make the methods like `OpenInput` fail if something is already running.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            EmptyBuffers();
Wouldn't filling all the buffers initially with empty just cause the audio to be delayed for one second, or does that not happen?

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                OnMidiPlayerFinished?.Invoke();
Right now this will be invoked from the audio thread. It would probably be wise to run this on the main thread with `ITaskManager.RunOnMainThread`.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            if (IsMidiOpen && _player.Status == FluidPlayerStatus.Done)
Here's a fun race condition for you: Since this block of code doesn't lock the player, it's possible for somebody to run `CloseMidi()` between `IsMidiOpen` and `_player.Status == FluidPlayerStatus.Done`, thus causing a null reference exception.

You should be able to solve this one by just wrapping the if statement in a `lock (_player)`. C#'s lock statement is re-entrant so it won't cause a problem with the lock happening inside `CloseMidi`.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        left = left.Zip(right, (x, y) => (ushort) (x + y)).ToArray();
Shouldn't you also be dividing these by two to average them, or is that not how audio works?

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        left = new ushort[length];
You should probably *really* cut down on the amount of allocations here. Right now this code allocates 200,000 bytes per second for a single MIDI renderer, and it has to be low latency too. That's not accounting for the amount of LINQ either.

The easiest way is probably to use `stackalloc` to just allocate a buffer, since they're quite small anyways. You can re-use it outside the for loop too.

Also note, in both the Mono and Stereo case your buffers add up to the same length, so you can always `Span<ushort> samples = stackalloc ushort[length*2]`.

For the Mono case, just give the right audio channel the top half and then merge it with a plain for loop, and only give OpenAL the bottom half when you're done. For the stereo case you can just interleave it like you're doing right now.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            catch (FluidSynthInteropException interopException)
Why are you ignoring exceptions here?
If you have a good reason, please do elaborate in a comment.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                            }
You can replace this with `goto case 128;`

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        if (_notesPlaying.Contains(midiEvent.Key))
This seems identical to the note off? In that case you should probably just remove the `case 128` entirely and let this default handle it.

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            if (_audioSources.ContainsKey(source))
Uuuh, what? How could this ever pass sanely?

2019-10-05 00:38 UTC, PJB3005 commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +            foreach (var stream in PlayingClydeStreams.ToArray())
Why was this change necessary? The contents of the loop here really shouldn't be adding or removing any streams.

2019-10-06 20:23 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        left = left.Zip(right, (x, y) => (ushort) (x + y)).ToArray();
Nope, dividing by two would mess up the sound. It's a bit unintuitive, but this has to do with the superposition principle since audio is essentialy a wave

2019-10-07 18:23 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        public static readonly string[] LinuxSoundfonts =
Done.

2019-10-07 18:24 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +#pragma warning enable 169
Ah, fuck. I screwed up here, yeah. (And in the end I didn't even need those dependencies...)

2019-10-07 18:26 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            _renderers.Add(renderer);
Ow. I locked the list of renderers, and also added the new renderer after the soundfont has been loaded. Should be good now.

2019-10-07 18:26 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        /// <summary>
Done.

2019-10-07 18:28 UTC, gradientvera commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                    if(renderer != null && !renderer.Rendering)
Yeah, I'm not actually using 'rendering' anymore... ...But I forgot to remove it. Whoops. 
I removed it now tho.

2019-10-07 18:29 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        public void Dispose()
Done!

2019-10-07 18:32 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +                }
Uh, seems I misunderstood what fixed does, then... Should be _mostly_ good now, I ended up using the code you wrote for this. (However there's still the "double linked list corruption crash" issue whenever you delete a few instruments... I fear it has to do with this class, somehow)

2019-10-07 18:35 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +        void OpenMidi(Span<byte> stream);
That's funny! The argument in the implementation is called "buffer", yet the one in the interface is called "stream"... At first, OpenMidi used `Stream` instead of `Span`, so that might be the reason. Done.

2019-10-07 18:38 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            _source = AL.GenSource();
Hmm, how should I go about this? Should I wrap some OpenAL stuff in Clyde for "low-level access" to the audio system?

2019-10-07 18:46 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                var empty = new Span<ushort>(new ushort[length]);
Why didn't I think of that before... Done now

2019-10-07 18:47 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                    AL.SourceQueueBuffers(_source, 1, new []{_buffers[i]});
Oh, indeed. Done now.

2019-10-07 19:00 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +        bool IsMidiOpen { get; }
Yeah, you're supposed to either be playing from a midi file, playing from midi input or none. Done now.

2019-10-07 19:02 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            EmptyBuffers();
I think it adds a very minor delay, but unless I do this the source automatically stops before any audio is rendered at all...

2019-10-07 19:37 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                OnMidiPlayerFinished?.Invoke();
Oh gosh, I wish I knew about that much sooner... Done.

2019-10-07 19:39 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            if (IsMidiOpen && _player.Status == FluidPlayerStatus.Done)
Ow, seems I still need to play some more Deadlock Empire! Done now.

2019-10-08 09:43 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        left = new ushort[length];
This is now done, thanks to the changes you made to WriteSample16!

2019-10-08 09:49 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            catch (FluidSynthInteropException interopException)
At first I was ignoring all exceptions because trying to send a NoteOff event for a key that's not on threw an exception... However, after adding the list of played notes this isn't the case anymore. Furthermore, I think a fluidsynth exception shouldn't crash the game, so I think I'll add a log message here instead of throwing the exception. Is that fine?

2019-10-08 09:54 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                            }
Done.

2019-10-08 09:56 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                        if (_notesPlaying.Contains(midiEvent.Key))
Indeed it is. I moved the case 128 so it's the same as default now:
`case 128:`
`default:`
`[...]`

2019-10-08 10:00 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            if (_audioSources.ContainsKey(source))
...multi-threading. Yeah, I'll change these back since I don't even use clyde.audio directly anymore.

2019-10-08 10:00 UTC, Zumorica commented on Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
> +            foreach (var stream in PlayingClydeStreams.ToArray())
Changed this one as well.

2019-10-08 10:02 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            "/usr/share/soundfonts/FluidR3_GM.sf2",
The problem is that FluidR3_GS.sf2 doesn't include most instruments, as it's an extension to FluidR3_GM.sf2... And freepats is 190mb. Honestly, this is a bit of a mess. Got any ideas for this?

2019-10-08 10:06 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        }
Something is seriously wrong with this class. Disposing a few instruments triggers a double-linked list corruption when using this.

2019-10-08 18:21 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            catch (FluidSynthInteropException interopException)
Yeah, that's fine.

2019-10-08 18:25 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            "/usr/share/soundfonts/FluidR3_GM.sf2",
Damnit...

At that point I'd rather dynamically download the sound font from our server and default to fallback.

2019-10-08 18:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        }
I did some googling. Looks like an issue related to double frees etc?

I have no idea why the code would be doing double frees here, though..

2019-10-08 19:05 UTC, elwray commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        }
Maybe because IntPtr has a 64 bit size and you cast it to 32 bit integer?

2019-10-08 19:29 UTC, elwray commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            public override unsafe int Read(IntPtr buf, long count, IntPtr sfHandle)
Does methods `Read` and `Seek` should return 0 or actual number of bytes that readed / skipped?

2019-10-08 19:53 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +            public override unsafe int Read(IntPtr buf, long count, IntPtr sfHandle)
Both return 0 ([FLUID_OK](http://www.fluidsynth.org/api/misc_8h.html#ae4efb1c3ce0d550c922504adfb0fb886)) if the read/seek operation executed correctly. ([API reference](http://www.fluidsynth.org/api/sfont_8h.html#a5ad574cbab9c9413932d51faaa5d10a8))

2019-10-09 12:47 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        }
Well, seems the problem wasn't this class, but SoundfontLoader being deleted by Synth on their own deletion. I'm resolving this one, for now.

2019-10-11 23:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            _source = AL.GenSource();
Probably? As long as it's semi sane and OpenAL is specific to Clyde I'm fine with it.

2019-10-13 17:27 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +            _source = AL.GenSource();
Resolving this in favor of #877

2019-10-16 11:36 UTC, Zumorica commented
I guess the only thing missing from this now is... Solving the "issue" with soundfonts on linux.

We've already discussed this a bit, and we concluded that shipping a big soundfont with the repo isn't ideal, and that the common soundfonts used on linux are way too big. 
Since the soundfont needs to be loaded into memory at least once, it would be ideal if it was small. Maybe less than 10mb.

Does anyone have any suggestions as to what to do with this issue?

2019-10-16 11:40 UTC, Injazz commented
ship soundfonts ourselves

2019-10-16 11:55 UTC, Zumorica commented
> ship soundfonts ourselves

Maybe the launcher could download a soundfont from the builds server or something?

2019-10-22 22:30 UTC, PJB3005 requested changes

2019-10-22 22:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        bool DisposeRenderer(IMidiRenderer renderer);
You really shouldn't have this separate dispose method. It should all be handled by `MidiRenderer.Dispose`

2019-10-22 22:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                lock(Position)
This lock is not at all enough to avoid thread safety issues here, since no other code actually locks entities (and it shouldn't, it'd kill performance).

You should update the position from a frame update from the main loop instead, like how `AudioSystem` does it.

2019-10-22 22:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                lock(_player)
You still aren't correctly locking the state related to the synth or the player here.

You should make a separate plain `object`, and use that as a guard to lock all the state related to the player and the synth.

2019-10-22 22:30 UTC, PJB3005 commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                _taskManager.RunOnMainThread(() => Logger.ErrorS("midi",
Logging is thread safe actually, if you store the `ISawmill` to log to somewhere when creating the midi renderer.

2019-10-26 17:16 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                _taskManager.RunOnMainThread(() => Logger.ErrorS("midi",
Should be good now.

2019-10-26 17:16 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                lock(_player)
Done, I think.

2019-10-26 17:28 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiManager.cs
> +        bool DisposeRenderer(IMidiRenderer renderer);
I removed this method, but I still needed to remove disposed/null renderers from the renderer list, so I let the thread method handle that. Should be alright, but please let me know if you can think of a better solution!

2019-10-26 17:57 UTC, Zumorica commented on Robust.Client/Audio/Midi/MidiRenderer.cs
> +                lock(Position)
This is done now.

2019-10-30 15:33 UTC, PJB3005 approved these changes

2019-10-30 15:45 UTC, merged