Add BufferedAudioSource to Clyde.Audio
space-wizards/RobustToolbox pull request #877
Opened 2019-10-13 17:00 UTC by Zumorica

Required by #873

2019-10-14 21:26 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            public int[] GetBuffersProcessed()
I would really prefer if there was a variant of this API that does not allocate, for example something that writes into a `Span<int>`.

2019-10-14 21:26 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            public void QueueBuffers(int[] handles)
Again, this should be doable without allocations by passing a `ReadOnlySpan<int>`

2019-10-14 21:26 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/ClydeHeadless.cs
> +        private sealed class DummyBufferedAudioSource : IClydeBufferedAudioSource
Make this inherit `DummyAudioSource` maybe?

2019-10-14 22:37 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            public int[] GetBuffersProcessed()
Done, although I changed all those to use `Span<uint>` instead.

2019-10-14 22:37 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/ClydeHeadless.cs
> +        private sealed class DummyBufferedAudioSource : IClydeBufferedAudioSource
Done as well.

2019-10-14 22:38 UTC, Zumorica commented
I also mapped all buffer handles internally so we don't leak any OpenAL buffer handles, and added some simple checks for those.

2019-10-14 22:56 UTC, PJB3005 requested changes

2019-10-14 22:56 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            public unsafe Span<uint> GetBuffersProcessed()
You can't actually return a span like this. A span is just a section of memory. Note how you aren't actually allocating any memory to put the data in here.

You will need to have this function *take in* a `Span<uint>` and write `min(span.Length, GetNumberOfBuffersProcessed())` into this span. The user of the API can use `GetNumberOfBuffersProcessed()` themselves to correctly allocate enough space for all the buffers.

2019-10-14 22:56 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                var realHandles = new Span<uint>();
Again, creating a new `Span<>` won't allocate any memory for you, so this will fail.

What you want to do here is create `realHandles` like so, using `stackalloc` to actually allocate space:

```cs
Span<uint>() realHandles = stackalloc uint[handles.Length];
```

This is significantly cheaper than a full array allocation still, and works with dynamic sizes.

2019-10-14 22:56 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                fixed(uint* ptr = handles)
I believe you mean to pass `realHandles` here.

2019-10-14 23:59 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                fixed(uint* ptr = handles)
Whoops. Fixed now...

2019-10-15 00:00 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +            public unsafe Span<uint> GetBuffersProcessed()
Done! (I also updated the midi pr to use these changes)

2019-10-15 00:00 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                var realHandles = new Span<uint>();
Done as well!

2019-10-15 09:31 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                for (var i = 0; i < handles.Length; i++)
You're only writing to the bottom `Math.Min(handles.Length, GetNumberOfBuffersProcessed())` of the buffers handles here, so you should only map that lower section.

2019-10-15 09:46 UTC, Zumorica commented on Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
> +                for (var i = 0; i < handles.Length; i++)
Oh, you're right... Fixed now!

2019-10-15 10:06 UTC, Zumorica commented
I just made it delete buffers on dispose, since I'm pretty sure deleting the source isn't enough to free them.

2019-10-15 10:21 UTC, PJB3005 approved these changes

2019-10-16 23:52 UTC, merged