Cursor styles
space-wizards/RobustToolbox pull request #943
Opened 2020-01-27 21:00 UTC by tentekal

Please ignore hacky implementation of CreateCursor. I plan to fix some of these added empty lines and squash some unnecessary commits. 

Placeholder addressing #807

2020-01-28 14:20 UTC, PJB3005 requested changes

2020-01-28 14:20 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +        public override void CreateCursor(GlfwImage image, int x, int y)
1. GLFW should not be exposed directly.
2. Just make this take an `Image<Rgba32>`

2020-01-28 14:20 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +            List<Image<Rgba32>> cursorIcons = LoadCursorIcon("/Textures/UserInterface/cursorIcons");
Uh, why even take in an image then?

2020-01-28 14:20 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +            _cursor = GLFW.CreateCursor(image, x, y);
You need to destroy the previous cursor (if we have any) or else there's a memory leak here.

2020-01-28 14:20 UTC, PJB3005 commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +        private GlfwImage SetCursorIcon(IEnumerable<Image<Rgba32>> cursorIcons)
You don't have to do all this stuff with taking in a list. You're just returning the result for the first image aren't you?

Also, you're doing a memory violation here. You can't return the `GlfwImage` allocated since it contains a pointer to managed memory (that gets unpinned at the end of the method).

To actually get a `GlfwImage` from a *single* `Image<Rgba32>` you can just do the following:

```cs
fixed (Rgba32* pixPtr = image.GetPixelSpan())
{
	var glfwImage = new GlfwImage(image.Width, image.Height, (byte*) pixPtr);
	// DO NOT use glfwImage after leaving the `fixed` block. Call `glfwCreateCursor` in here or something. 
}
```

2020-01-28 14:23 UTC, tentekal commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +            _cursor = GLFW.CreateCursor(image, x, y);
My mistake, I thought I read somewhere in documentation the CreateCursor() destroyed the previous cursor automatically. Not sure why I thought that.

2020-01-28 18:58 UTC, tentekal commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +        public override void CreateCursor(GlfwImage image, int x, int y)
Understood, I'll implement via IClyde.cs.

2020-01-28 19:00 UTC, tentekal commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +            List<Image<Rgba32>> cursorIcons = LoadCursorIcon("/Textures/UserInterface/cursorIcons");
I intend to pass a PNG path from a component to CreateCursor. This was just a lazy way of making something render without worrying about components yet.

2020-01-28 19:01 UTC, tentekal commented on Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
> +        private GlfwImage SetCursorIcon(IEnumerable<Image<Rgba32>> cursorIcons)
Copy-paste of the method used for loading window icons, I originally had something similar to your method implemented but it was accidentally removed.  This is super helpful though, thanks.

2020-04-17 13:07 UTC, PJB3005 commented
I am gonna do this myself since the PR is stale.

2020-04-17 13:07 UTC, closed without merging